"""Type stubs for aster package.

Phase 2: All bindings now use aster_transport_core as the backend.
Phase 1b: Includes datagram completion, connection info, remote-info, and hooks.
"""

from typing import Any, Coroutine, Optional


class IrohError(Exception): ...
class BlobNotFound(IrohError): ...
class DocNotFound(IrohError): ...
class ConnectionError(IrohError): ...
class TicketError(IrohError): ...

__version__: str
__all__: list[str]


class NodeAddr:
    endpoint_id: str
    relay_url: Optional[str]
    direct_addresses: list[str]

    def __init__(
        self,
        endpoint_id: str,
        relay_url: Optional[str] = ...,
        direct_addresses: Optional[list[str]] = ...,
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> "NodeAddr": ...
    @staticmethod
    def from_dict(data: dict[str, Any]) -> "NodeAddr": ...


class EndpointConfig:
    relay_mode: Optional[str]
    alpns: list[bytes]
    secret_key: Optional[bytes]
    enable_monitoring: bool  # Phase 1b
    enable_hooks: bool  # Phase 1b
    hook_timeout_ms: int  # Phase 1b

    def __init__(
        self,
        alpns: list[bytes],
        relay_mode: Optional[str] = ...,
        secret_key: Optional[bytes] = ...,
        enable_monitoring: bool = ...,
        enable_hooks: bool = ...,
        hook_timeout_ms: int = ...,
    ) -> None: ...


class ConnectionInfo:  # Phase 1b
    connection_type: str
    bytes_sent: int
    bytes_received: int
    rtt_ns: Optional[int]
    alpn: bytes
    is_connected: bool


class RemoteInfo:  # Phase 1b
    node_id: str
    relay_url: Optional[str]
    connection_type: str
    last_handshake_ns: Optional[int]
    bytes_sent: int
    bytes_received: int
    is_connected: bool


class IrohNode:
    @staticmethod
    def memory() -> Coroutine[Any, Any, "IrohNode"]: ...
    @staticmethod
    def persistent(path: str) -> Coroutine[Any, Any, "IrohNode"]: ...
    def node_id(self) -> str: ...
    def node_addr(self) -> str: ...
    def node_addr_info(self) -> NodeAddr: ...
    def close(self) -> Coroutine[Any, Any, None]: ...
    def shutdown(self) -> Coroutine[Any, Any, None]: ...
    def add_node_addr(self, other: "IrohNode") -> None: ...
    def export_secret_key(self) -> bytes: ...


class BlobStatusResult:
    status: str  # "not_found", "partial", or "complete"
    size: int


class BlobObserveResult:
    """Snapshot of a blob's local bitfield."""
    is_complete: bool
    size: int  # total blob size in bytes; 0 if not yet known


class BlobLocalInfo:
    """Local availability info for a blob from the Remote API."""
    is_complete: bool
    local_bytes: int  # bytes already present locally


class TagInfo:
    name: str
    hash: str
    format: str  # "raw" or "hash_seq"


class BlobsClient:
    def add_bytes(self, data: bytes) -> Coroutine[Any, Any, str]: ...
    def read_to_bytes(self, hash_hex: str) -> Coroutine[Any, Any, bytes]: ...
    def create_ticket(self, hash_hex: str) -> str: ...
    def add_bytes_as_collection(self, name: str, data: bytes) -> Coroutine[Any, Any, str]: ...
    def create_collection_ticket(self, hash_hex: str) -> str: ...
    def download_blob(self, ticket_str: str) -> Coroutine[Any, Any, bytes]: ...
    # Phase 1c: Tag methods
    def tag_set(
        self, name: str, hash_hex: str, format: str
    ) -> Coroutine[Any, Any, None]: ...
    def tag_get(self, name: str) -> Coroutine[Any, Any, Optional["TagInfo"]]: ...
    def tag_delete(self, name: str) -> Coroutine[Any, Any, int]: ...
    def tag_delete_prefix(self, prefix: str) -> Coroutine[Any, Any, int]: ...
    def tag_list(self) -> Coroutine[Any, Any, list["TagInfo"]]: ...
    def tag_list_prefix(self, prefix: str) -> Coroutine[Any, Any, list["TagInfo"]]: ...
    def tag_list_hash_seq(self) -> Coroutine[Any, Any, list["TagInfo"]]: ...
    # Phase 1c.3: Blob status
    def blob_status(self, hash_hex: str) -> Coroutine[Any, Any, "BlobStatusResult"]: ...
    def blob_has(self, hash_hex: str) -> Coroutine[Any, Any, bool]: ...
    # Phase 1d: Blob observability
    def blob_observe_snapshot(
        self, hash_hex: str
    ) -> Coroutine[Any, Any, "BlobObserveResult"]: ...
    def blob_observe_complete(self, hash_hex: str) -> Coroutine[Any, Any, None]: ...
    def blob_local_info(self, hash_hex: str) -> Coroutine[Any, Any, "BlobLocalInfo"]: ...


def blobs_client(node: IrohNode) -> BlobsClient: ...


class DocEntry:
    author_id: str
    key: bytes
    content_hash: str
    content_len: int
    timestamp: int


class DocEvent:
    """Live document event. Check `kind` to determine which fields are populated.

    kind values: "insert_local", "insert_remote", "content_ready",
                 "pending_content_ready", "neighbor_up", "neighbor_down", "sync_finished"
    """
    kind: str
    entry: Optional["DocEntry"]   # InsertLocal / InsertRemote
    from_peer: Optional[str]      # InsertRemote
    hash: Optional[str]           # ContentReady
    peer: Optional[str]           # NeighborUp / NeighborDown / SyncFinished


class DocEventReceiver:
    def recv(self) -> Coroutine[Any, Any, Optional["DocEvent"]]: ...


class DocDownloadPolicy:
    """Download policy for a document.

    mode values:
      "everything"        — download all entries (default)
      "nothing_except"    — download only entries matching one of the prefixes
      "everything_except" — download all entries except those matching one of the prefixes
    """
    mode: str
    prefixes: list[bytes]


class DocsClient:
    def create(self) -> Coroutine[Any, Any, "DocHandle"]: ...
    def create_author(self) -> Coroutine[Any, Any, str]: ...
    def join(self, ticket_str: str) -> Coroutine[Any, Any, "DocHandle"]: ...
    # Phase 1c.8
    def join_and_subscribe(
        self, ticket_str: str
    ) -> Coroutine[Any, Any, tuple["DocHandle", "DocEventReceiver"]]: ...


class DocHandle:
    def doc_id(self) -> str: ...
    def set_bytes(
        self, author_hex: str, key: bytes, value: bytes
    ) -> Coroutine[Any, Any, str]: ...
    def get_exact(
        self, author_hex: str, key: bytes
    ) -> Coroutine[Any, Any, Optional[bytes]]: ...
    def query_key_exact(
        self, key: bytes
    ) -> Coroutine[Any, Any, list["DocEntry"]]: ...
    def query_key_prefix(
        self, prefix: bytes
    ) -> Coroutine[Any, Any, list["DocEntry"]]: ...
    def read_entry_content(
        self, content_hash_hex: str
    ) -> Coroutine[Any, Any, bytes]: ...
    def share(self, mode: str) -> Coroutine[Any, Any, str]: ...
    def subscribe(self) -> Coroutine[Any, Any, "DocEventReceiver"]: ...
    # Phase 1c.5: Sync lifecycle
    def start_sync(self, peers: list[str]) -> Coroutine[Any, Any, None]: ...
    def leave(self) -> Coroutine[Any, Any, None]: ...
    # Phase 1c.6: Download policy
    def set_download_policy(
        self, mode: str, prefixes: list[bytes]
    ) -> Coroutine[Any, Any, None]: ...
    def get_download_policy(self) -> Coroutine[Any, Any, "DocDownloadPolicy"]: ...
    # Phase 1c.7: Share with full address
    def share_with_addr(self, mode: str) -> Coroutine[Any, Any, str]: ...


def docs_client(node: IrohNode) -> DocsClient: ...


class GossipClient:
    def subscribe(
        self, topic_bytes: bytes, bootstrap_peers: list[str]
    ) -> Coroutine[Any, Any, "GossipTopicHandle"]: ...


class GossipTopicHandle:
    def broadcast(self, data: bytes) -> Coroutine[Any, Any, None]: ...
    def recv(
        self,
    ) -> Coroutine[Any, Any, tuple[str, Optional[bytes]]]: ...


def gossip_client(node: IrohNode) -> GossipClient: ...


class NetClient:
    def connect(self, node_id: str, alpn: bytes) -> Coroutine[Any, Any, "IrohConnection"]: ...
    def connect_node_addr(
        self, addr: NodeAddr, alpn: bytes
    ) -> Coroutine[Any, Any, "IrohConnection"]: ...
    def accept(self) -> Coroutine[Any, Any, "IrohConnection"]: ...
    def endpoint_id(self) -> str: ...
    def endpoint_addr(self) -> str: ...
    def endpoint_addr_info(self) -> NodeAddr: ...
    def close(self) -> Coroutine[Any, Any, None]: ...
    def closed(self) -> Coroutine[Any, Any, None]: ...
    def export_secret_key(self) -> bytes: ...
    # Phase 1b: Remote-info & monitoring
    def remote_info(self, node_id: str) -> Optional[RemoteInfo]: ...
    def remote_info_list(self) -> list[RemoteInfo]: ...
    def has_monitoring(self) -> bool: ...
    def has_hooks(self) -> bool: ...


class IrohConnection:
    def open_bi(self) -> Coroutine[Any, Any, tuple["IrohSendStream", "IrohRecvStream"]]: ...
    def accept_bi(self) -> Coroutine[Any, Any, tuple["IrohSendStream", "IrohRecvStream"]]: ...
    def open_uni(self) -> Coroutine[Any, Any, "IrohSendStream"]: ...
    def accept_uni(self) -> Coroutine[Any, Any, "IrohRecvStream"]: ...
    def send_datagram(self, data: bytes) -> None: ...
    def read_datagram(self) -> Coroutine[Any, Any, bytes]: ...
    def remote_id(self) -> str: ...
    def close(self, code: int, reason: bytes) -> None: ...
    def closed(self) -> Coroutine[Any, Any, dict[str, Any]]: ...
    # Phase 1b: Datagram completion
    def max_datagram_size(self) -> Optional[int]: ...
    def datagram_send_buffer_space(self) -> int: ...
    # Phase 1b: Connection info
    def connection_info(self) -> ConnectionInfo: ...


class IrohSendStream:
    def write_all(self, data: bytes) -> Coroutine[Any, Any, None]: ...
    def finish(self) -> Coroutine[Any, Any, None]: ...
    def stopped(self) -> Coroutine[Any, Any, Optional[int]]: ...


class IrohRecvStream:
    def read(self, max_len: int) -> Coroutine[Any, Any, Optional[bytes]]: ...
    def read_exact(self, n: int) -> Coroutine[Any, Any, bytes]: ...
    def read_to_end(self, max_size: int) -> Coroutine[Any, Any, bytes]: ...
    def stop(self, code: int) -> None: ...


def net_client(node: IrohNode) -> NetClient: ...
def create_endpoint(alpn: bytes) -> Coroutine[Any, Any, NetClient]: ...
def create_endpoint_with_config(config: EndpointConfig) -> Coroutine[Any, Any, NetClient]: ...


# Phase 1b: Hooks


class HookConnectInfo:  # Phase 1b
    remote_endpoint_id: str
    alpn: bytes

    def __init__(
        self,
        remote_endpoint_id: str = ...,
        alpn: bytes = ...,
    ) -> None: ...


class HookHandshakeInfo:  # Phase 1b
    remote_endpoint_id: str
    alpn: bytes
    is_alive: bool

    def __init__(
        self,
        remote_endpoint_id: str = ...,
        alpn: bytes = ...,
        is_alive: bool = ...,
    ) -> None: ...


class HookDecision:  # Phase 1b
    is_allowed: bool
    error_code: Optional[int]
    reason: Optional[bytes]

    def __init__(self) -> None: ...
    @property
    def allow(self) -> bool: ...
    @staticmethod
    def create_allow() -> "HookDecision": ...
    @staticmethod
    def create_deny(error_code: int, reason: bytes) -> "HookDecision": ...


class HookReceiver:  # Phase 1b
    def has_pending(self) -> bool: ...


class HookRegistration:  # Phase 1b
    has_before_connect: bool
    has_after_connect: bool


class HookManager:  # Phase 1b
    def __init__(
        self,
        before_connect: Optional[Any] = ...,
        after_connect: Optional[Any] = ...,
    ) -> None: ...
    def set_before_connect(self, callback: Optional[Any]) -> None: ...
    def set_after_connect(self, callback: Optional[Any]) -> None: ...
