"""Auto-generated type stubs for the native _aster extension module."""

from typing import Any, Coroutine, Optional
from collections.abc import Sequence

# ── Exceptions ────────────────────────────────────────────────────────────────

class IrohError(Exception): ...
class BlobNotFound(Exception): ...
class DocNotFound(Exception): ...
class ConnectionError(Exception): ...
class TicketError(Exception): ...

# ── Node ──────────────────────────────────────────────────────────────────────

class IrohNode:
    @staticmethod
    def memory() -> Coroutine[Any, Any, IrohNode]: ...
    @staticmethod
    def persistent(path: str) -> Coroutine[Any, Any, IrohNode]: ...
    @staticmethod
    def memory_with_alpns(alpns: list[bytes], config: Optional[EndpointConfig] = None) -> Coroutine[Any, Any, IrohNode]: ...
    @staticmethod
    def persistent_with_alpns(path: str, alpns: list[bytes], config: Optional[EndpointConfig] = None) -> Coroutine[Any, Any, IrohNode]: ...
    def accept_aster(self, alpn: Optional[bytes] = None) -> Coroutine[Any, Any, IrohConnection]: ...
    def take_hook_receiver(self) -> Optional[NodeHookReceiver]: ...
    def has_hooks(self) -> bool: ...
    def node_id(self) -> str: ...
    def node_addr(self) -> str: ...
    def node_addr_info(self) -> NodeAddr: ...
    def close(self) -> Coroutine[Any, Any, None]: ...
    def shutdown(self) -> Coroutine[Any, Any, None]: ...
    def add_node_addr(self, other: IrohNode) -> None: ...
    def export_secret_key(self) -> bytes: ...
    def transport_metrics_prometheus(self) -> str: ...

# ── QUIC Streams ──────────────────────────────────────────────────────────────

class IrohSendStream:
    def write_all(self, data: bytes) -> Coroutine[Any, Any, None]: ...
    def finish(self) -> Coroutine[Any, Any, None]: ...
    def stopped(self) -> Coroutine[Any, Any, None]: ...

class IrohRecvStream:
    def read(self, n: int) -> Coroutine[Any, Any, bytes]: ...
    def read_exact(self, n: int) -> Coroutine[Any, Any, bytes]: ...
    def read_to_end(self, max_size: int) -> Coroutine[Any, Any, bytes]: ...
    def stop(self, error_code: int) -> None: ...

# ── Connection ────────────────────────────────────────────────────────────────

class IrohConnection:
    def open_bi(self) -> Coroutine[Any, Any, tuple[IrohSendStream, IrohRecvStream]]: ...
    def accept_bi(self) -> Coroutine[Any, Any, tuple[IrohSendStream, IrohRecvStream]]: ...
    def open_uni(self) -> Coroutine[Any, Any, IrohSendStream]: ...
    def accept_uni(self) -> Coroutine[Any, Any, IrohRecvStream]: ...
    def send_datagram(self, data: bytes) -> Coroutine[Any, Any, None]: ...
    def read_datagram(self) -> Coroutine[Any, Any, bytes]: ...
    def max_datagram_size(self) -> Optional[int]: ...
    def remote_id(self) -> str: ...
    def connection_info(self) -> ConnectionInfo: ...
    def close(self, code: int, reason: bytes) -> None: ...

class ConnectionInfo:
    rtt_us: int
    cwnd: int
    remote_endpoint_id: str
    close_reason: str

# ── NodeAddr ──────────────────────────────────────────────────────────────────

class NodeAddr:
    endpoint_id: str
    relay_url: Optional[str]
    direct_addresses: Optional[list[str]]
    def __init__(
        self,
        endpoint_id: str = "",
        relay_url: Optional[str] = None,
        direct_addresses: Optional[list[str]] = None,
    ) -> None: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> NodeAddr: ...

# ── EndpointConfig ────────────────────────────────────────────────────────────

class EndpointConfig:
    alpns: Optional[list[str]]
    secret_key: Optional[bytes]
    relay_mode: Optional[str]
    relay_url: Optional[str]
    bind_addr: Optional[str]
    enable_hooks: Optional[bool]
    hook_timeout_ms: Optional[int]
    enable_monitoring: Optional[bool]
    enable_local_discovery: Optional[bool]
    portmapper_config: Optional[str]
    proxy_url: Optional[str]
    proxy_from_env: Optional[bool]
    clear_relay_transports: Optional[bool]
    clear_ip_transports: Optional[bool]
    def __init__(
        self,
        alpns: Optional[list[str]] = None,
        secret_key: Optional[bytes] = None,
        relay_mode: Optional[str] = None,
        relay_url: Optional[str] = None,
        bind_addr: Optional[str] = None,
        enable_hooks: Optional[bool] = None,
        hook_timeout_ms: Optional[int] = None,
        enable_monitoring: Optional[bool] = None,
        enable_local_discovery: Optional[bool] = None,
        portmapper_config: Optional[str] = None,
        proxy_url: Optional[str] = None,
        proxy_from_env: Optional[bool] = None,
        clear_relay_transports: Optional[bool] = None,
        clear_ip_transports: Optional[bool] = None,
    ) -> None: ...

# ── Blobs ─────────────────────────────────────────────────────────────────────

class BlobsClient:
    def add_bytes(self, data: bytes) -> Coroutine[Any, Any, str]: ...
    def read_to_bytes(self, hash_hex: str) -> Coroutine[Any, Any, bytes]: ...
    def create_ticket(self, hash_hex: str) -> str: ...
    def create_collection_ticket(self, hash_hex: str) -> str: ...
    def download_blob(self, ticket_str: str) -> Coroutine[Any, Any, bytes]: ...
    def download_hash(self, hash_hex: str, node_id_hex: str, format: str) -> Coroutine[Any, Any, bytes]: ...
    def download_collection_hash(self, hash_hex: str, node_id_hex: str) -> Coroutine[Any, Any, list[tuple[str, bytes]]]: ...
    def add_bytes_as_collection(self, entries: list[tuple[str, bytes]]) -> Coroutine[Any, Any, str]: ...
    def list_collection(self, hash_hex: str) -> Coroutine[Any, Any, list[tuple[str, str, int]]]: ...
    def has(self, hash_hex: str) -> Coroutine[Any, Any, bool]: ...
    def tag_set(self, name: str, hash_hex: str, format: str) -> Coroutine[Any, Any, None]: ...
    def tag_get(self, name: str) -> Coroutine[Any, Any, Optional[str]]: ...
    def tag_delete(self, name: str) -> Coroutine[Any, Any, None]: ...
    def tag_list(self) -> Coroutine[Any, Any, list[TagInfo]]: ...
    def tag_list_prefix(self, prefix: str) -> Coroutine[Any, Any, list[TagInfo]]: ...
    def blob_status(self, hash_hex: str) -> Coroutine[Any, Any, BlobStatusResult]: ...
    def blob_observe_complete(self, hash_hex: str) -> Coroutine[Any, Any, BlobObserveResult]: ...
    def blob_local_info(self, hash_hex: str) -> Coroutine[Any, Any, BlobLocalInfo]: ...

class BlobStatusResult:
    is_complete: bool
    size: int
class BlobObserveResult:
    is_complete: bool
    size: int
class BlobLocalInfo:
    is_complete: bool
    local_bytes: int
class TagInfo:
    name: str
    hash: str
    format: str

# ── Docs ──────────────────────────────────────────────────────────────────────

class DocsClient:
    def create(self) -> Coroutine[Any, Any, tuple[DocHandle, str]]: ...
    def create_author(self) -> Coroutine[Any, Any, str]: ...
    def join(self, ticket_str: str) -> Coroutine[Any, Any, DocHandle]: ...
    def join_and_subscribe(self, ticket_str: str) -> Coroutine[Any, Any, tuple[DocHandle, DocEventReceiver]]: ...
    def join_and_subscribe_namespace(self, namespace_id_hex: str, peer_node_id_hex: str) -> Coroutine[Any, Any, tuple[DocHandle, DocEventReceiver]]: ...

class DocHandle:
    def set_bytes(self, author_id: str, key: bytes, value: bytes) -> Coroutine[Any, Any, str]: ...
    def get_exact(self, author_id: str, key: bytes) -> Coroutine[Any, Any, Optional[DocEntry]]: ...
    def query_key_exact(self, key: bytes) -> Coroutine[Any, Any, list[DocEntry]]: ...
    def query_key_prefix(self, prefix: bytes) -> Coroutine[Any, Any, list[DocEntry]]: ...
    def read_entry_content(self, content_hash_hex: str) -> Coroutine[Any, Any, bytes]: ...
    def share(self, mode: str) -> Coroutine[Any, Any, str]: ...
    def share_with_addr(self, mode: str) -> Coroutine[Any, Any, str]: ...
    def doc_id(self) -> str: ...
    def subscribe(self) -> Coroutine[Any, Any, DocEventReceiver]: ...
    def start_sync(self, peers: list[Any]) -> Coroutine[Any, Any, None]: ...
    def leave(self) -> Coroutine[Any, Any, None]: ...
    def set_download_policy(self, policy_str: str) -> Coroutine[Any, Any, None]: ...
    def get_download_policy(self) -> Coroutine[Any, Any, str]: ...

class DocEntry:
    author_id: str
    key: bytes
    content_hash: str
    content_len: int
    timestamp: int

class DocEvent:
    kind: str

class DocEventReceiver:
    def recv(self) -> Coroutine[Any, Any, DocEvent]: ...

class DocDownloadPolicy: ...

# ── Gossip ────────────────────────────────────────────────────────────────────

class GossipClient:
    def subscribe(self, topic: bytes, bootstrap: list[str]) -> Coroutine[Any, Any, GossipTopicHandle]: ...

class GossipTopicHandle:
    def broadcast(self, data: bytes) -> Coroutine[Any, Any, None]: ...
    def recv(self) -> Coroutine[Any, Any, bytes]: ...

# ── Net ───────────────────────────────────────────────────────────────────────

class NetClient:
    def connect_node_addr(self, addr: NodeAddr, alpn: str) -> Coroutine[Any, Any, IrohConnection]: ...
    def remote_info(self, endpoint_id: str) -> Coroutine[Any, Any, Optional[RemoteInfo]]: ...

class RemoteInfo:
    endpoint_id: str
    relay_url: Optional[str]
    addrs: list[str]
    last_used: Optional[int]

class TransportMetrics: ...

# ── Hooks ─────────────────────────────────────────────────────────────────────

class HookConnectInfo:
    remote_addr: str

class HookHandshakeInfo:
    remote_addr: str
    endpoint_id: str
    alpn: str

class HookDecision:
    @staticmethod
    def create_allow() -> HookDecision: ...
    @staticmethod
    def create_deny(reason: str) -> HookDecision: ...

class HookReceiver: ...
class HookRegistration: ...
class HookManager: ...

class NodeHookReceiver:
    def recv(self) -> Coroutine[Any, Any, tuple[Any, NodeHookDecisionSender]]: ...

class NodeHookDecisionSender:
    def respond(self, decision: HookDecision) -> None: ...

# ── Ticket ────────────────────────────────────────────────────────────────────

class AsterTicket:
    endpoint_id: str
    relay_addr: Optional[str]
    direct_addrs: list[str]
    credential_type: Optional[str]
    credential_data: Optional[bytes]
    def __init__(
        self,
        endpoint_id: str = "",
        relay_addr: Optional[str] = None,
        direct_addrs: Optional[list[str]] = None,
        credential_type: Optional[str] = None,
        credential_data: Optional[bytes] = None,
    ) -> None: ...
    def encode(self) -> bytes: ...
    @staticmethod
    def decode(data: bytes) -> AsterTicket: ...
    def to_string(self) -> str: ...
    @staticmethod
    def from_string(s: str) -> AsterTicket: ...

# ── Module-level functions ────────────────────────────────────────────────────

def blobs_client(node: IrohNode) -> BlobsClient: ...
def docs_client(node: IrohNode) -> DocsClient: ...
def gossip_client(node: IrohNode) -> GossipClient: ...
def net_client(node: IrohNode) -> NetClient: ...
def create_endpoint() -> Coroutine[Any, Any, NetClient]: ...
def create_endpoint_with_config(config: EndpointConfig) -> Coroutine[Any, Any, NetClient]: ...

# ── Contract submodule ────────────────────────────────────────────────────────

class contract:
    @staticmethod
    def compute_contract_id_from_json(json_str: str) -> str: ...
    @staticmethod
    def canonical_bytes_from_json(json_str: str) -> bytes: ...
    @staticmethod
    def compute_type_hash(canonical_bytes: bytes) -> str: ...
    @staticmethod
    def encode_frame(payload: bytes, flags: int) -> bytes: ...
    @staticmethod
    def decode_frame(data: bytes) -> tuple[bytes, int]: ...
    @staticmethod
    def canonical_signing_bytes_from_json(json_str: str) -> bytes: ...
    @staticmethod
    def canonical_json(json_str: str) -> str: ...
