"""Auto-generated type stubs for the native _aster extension module."""

from typing import Any, Coroutine, Optional

class AsterCall: ...
class AsterTicket: ...
class BlobLocalInfo: ...
class BlobNotFound: ...
class BlobObserveResult: ...
class BlobStatusResult: ...
class BlobsClient: ...
class ConnectionError: ...
class ConnectionInfo: ...
class DocDownloadPolicy: ...
class DocEntry: ...
class DocEvent: ...
class DocEventReceiver: ...
class DocHandle: ...
class DocNotFound: ...
class DocsClient: ...
class EndpointConfig: ...
class GossipClient: ...
class GossipTopicHandle: ...
class HookConnectInfo: ...
class HookDecision: ...
class HookHandshakeInfo: ...
class HookManager: ...
class HookReceiver: ...
class HookRegistration: ...
class IrohConnection: ...
class IrohError: ...
class IrohNode: ...
class IrohRecvStream: ...
class IrohSendStream: ...
class NetClient: ...
class NodeAddr: ...
class NodeHookDecisionSender: ...
class NodeHookReceiver: ...
RECV_END_OF_STREAM: Any
RECV_OK: Any
RECV_TIMEOUT: Any
class ReactorCancelFlag: ...
class ReactorEvent: ...
class ReactorFeeder: ...
class ReactorHandle: ...
class ReactorRequestReceiver: ...
class ReactorResponseSender: ...
class RemoteInfo: ...
class StreamAcquireError: ...
class TagInfo: ...
class TicketError: ...
class TransportMetrics: ...
def blobs_client(*args: Any, **kwargs: Any) -> Any: ...
contract: Any
def create_endpoint(*args: Any, **kwargs: Any) -> Any: ...
def create_endpoint_with_config(*args: Any, **kwargs: Any) -> Any: ...
def create_reactor(*args: Any, **kwargs: Any) -> Any: ...
def docs_client(*args: Any, **kwargs: Any) -> Any: ...
def gossip_client(*args: Any, **kwargs: Any) -> Any: ...
def net_client(*args: Any, **kwargs: Any) -> Any: ...
def session_unary_call(*args: Any, **kwargs: Any) -> Any: ...
def start_reactor(*args: Any, **kwargs: Any) -> Any: ...
