/* Generated by cbindgen */

/* Generated with cbindgen:0.29.2 */

/* DO NOT EDIT */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define IROH_ABI_VERSION_MAJOR 1

#define IROH_ABI_VERSION_MINOR 0

#define IROH_ABI_VERSION_PATCH 0

/**
 * Result codes returned by `aster_call_recv_frame`. Mirrors the
 * `aster_reactor_recv_frame` triplet for consistency across surfaces.
 */
#define ASTER_CALL_RECV_OK 0

#define ASTER_CALL_RECV_END_OF_STREAM 1

#define ASTER_CALL_RECV_TIMEOUT 2

/**
 * Acquire-error subcodes returned by `aster_call_acquire` as negative
 * values. Bindings can map these to typed exceptions per spec §5.
 */
#define ASTER_CALL_ERR_POOL_FULL -10

#define ASTER_CALL_ERR_QUIC_LIMIT_REACHED -11

#define ASTER_CALL_ERR_PEER_STREAM_LIMIT_TOO_LOW -12

#define ASTER_CALL_ERR_STREAM_OPEN_FAILED -13

#define ASTER_CALL_ERR_POOL_CLOSED -14

/**
 * Event-kind discriminator for `aster_reactor_call_t` (spec §7.5).
 * Bindings MUST check `event_kind` before reading any other field — a
 * `ConnectionClosed` event populates only `event_kind`, `connection_id`,
 * `peer_*` (peer_id of the closed connection); all other fields are zero
 * or NULL.
 */
#define ASTER_EVENT_KIND_CALL 0

#define ASTER_EVENT_KIND_CONNECTION_CLOSED 1

/**
 * Result codes returned by `aster_reactor_recv_frame` in addition to the
 * usual `iroh_status_t` codes for error cases.
 */
#define ASTER_RECV_FRAME_OK 0

/**
 * Per-call request channel was closed cleanly (peer signalled END_STREAM
 * or its recv stream EOF'd). No frame was written; the binding should
 * stop calling recv_frame for this call_id.
 */
#define ASTER_RECV_FRAME_END_OF_STREAM 1

/**
 * Timeout expired with no frame available. The binding may retry.
 */
#define ASTER_RECV_FRAME_TIMEOUT 2

/**
 * Status codes
 */
typedef enum iroh_status_t {
  IROH_STATUS_OK = 0,
  IROH_STATUS_INVALID_ARGUMENT = 1,
  IROH_STATUS_NOT_FOUND = 2,
  IROH_STATUS_ALREADY_CLOSED = 3,
  IROH_STATUS_QUEUE_FULL = 4,
  IROH_STATUS_BUFFER_TOO_SMALL = 5,
  IROH_STATUS_UNSUPPORTED = 6,
  IROH_STATUS_INTERNAL = 7,
  IROH_STATUS_TIMEOUT = 8,
  IROH_STATUS_CANCELLED = 9,
  IROH_STATUS_CONNECTION_REFUSED = 10,
  IROH_STATUS_STREAM_RESET = 11,
} iroh_status_t;

/**
 * Hook decision
 */
typedef enum iroh_hook_decision_t {
  IROH_HOOK_DECISION_ALLOW = 0,
  IROH_HOOK_DECISION_DENY = 1,
} iroh_hook_decision_t;

typedef struct iroh_runtime_config_t {
  uint32_t struct_size;
  uint32_t worker_threads;
  uint32_t event_queue_capacity;
  uint32_t reserved;
} iroh_runtime_config_t;

/**
 * Opaque handle types
 */
typedef uint64_t iroh_runtime_t;

/**
 * C-compatible event structure for FFI output
 */
typedef struct iroh_event_t {
  uint32_t struct_size;
  uint32_t kind;
  uint32_t status;
  uint64_t operation;
  uint64_t handle;
  uint64_t related;
  uint64_t user_data;
  const uint8_t *data_ptr;
  uintptr_t data_len;
  uint64_t buffer;
  int32_t error_code;
  uint32_t flags;
} iroh_event_t;

typedef uint64_t iroh_operation_t;

typedef struct iroh_bytes_t {
  const uint8_t *ptr;
  uintptr_t len;
} iroh_bytes_t;

typedef uint64_t iroh_node_t;

typedef struct iroh_bytes_list_t {
  const struct iroh_bytes_t *items;
  uintptr_t len;
} iroh_bytes_list_t;

typedef struct iroh_node_addr_t {
  struct iroh_bytes_t endpoint_id;
  struct iroh_bytes_t relay_url;
  struct iroh_bytes_list_t direct_addresses;
} iroh_node_addr_t;

typedef struct iroh_endpoint_config_t {
  uint32_t struct_size;
  uint32_t relay_mode;
  struct iroh_bytes_t secret_key;
  struct iroh_bytes_list_t alpns;
  struct iroh_bytes_list_t relay_urls;
  uint32_t enable_discovery;
  uint32_t enable_hooks;
  uint64_t hook_timeout_ms;
  struct iroh_bytes_t bind_addr;
  uint32_t clear_ip_transports;
  uint32_t clear_relay_transports;
  uint32_t portmapper_config;
  struct iroh_bytes_t proxy_url;
  uint32_t proxy_from_env;
  struct iroh_bytes_t data_dir_utf8;
} iroh_endpoint_config_t;

typedef uint64_t iroh_endpoint_t;

typedef uint64_t iroh_recv_stream_t;

typedef struct iroh_connect_config_t {
  uint32_t struct_size;
  uint32_t flags;
  struct iroh_bytes_t node_id;
  struct iroh_bytes_t alpn;
  const struct iroh_node_addr_t *addr;
} iroh_connect_config_t;

typedef uint64_t iroh_connection_t;

typedef uint64_t iroh_send_stream_t;

typedef struct iroh_remote_info_t {
  uint32_t struct_size;
  struct iroh_bytes_t node_id;
  uint32_t is_connected;
  uint32_t connection_type;
  struct iroh_bytes_t relay_url;
  uint64_t last_handshake_ns;
  uint64_t bytes_sent;
  uint64_t bytes_received;
} iroh_remote_info_t;

typedef struct iroh_connection_info_t {
  uint32_t struct_size;
  uint32_t connection_type;
  uint64_t bytes_sent;
  uint64_t bytes_received;
  uint64_t rtt_ns;
  struct iroh_bytes_t alpn;
  uint32_t is_connected;
} iroh_connection_info_t;

typedef uint64_t iroh_hook_invocation_t;

/**
 * Transport-layer metrics snapshot from the iroh endpoint.
 */
typedef struct iroh_transport_metrics_t {
  uint32_t struct_size;
  uint64_t send_ipv4;
  uint64_t send_ipv6;
  uint64_t send_relay;
  uint64_t recv_data_ipv4;
  uint64_t recv_data_ipv6;
  uint64_t recv_data_relay;
  uint64_t recv_datagrams;
  uint64_t num_conns_direct;
  uint64_t num_conns_opened;
  uint64_t num_conns_closed;
  uint64_t paths_direct;
  uint64_t paths_relay;
  uint64_t holepunch_attempts;
  uint64_t relay_home_change;
  uint64_t net_reports;
  uint64_t net_reports_full;
} iroh_transport_metrics_t;

typedef uint64_t aster_call_t;

typedef uint64_t iroh_buffer_t;

typedef uint64_t aster_reactor_t;

/**
 * C-visible event descriptor returned by aster_reactor_poll.
 *
 * Despite the historical `aster_reactor_call_t` name, this struct now
 * carries either an inbound call (`event_kind == ASTER_EVENT_KIND_CALL`)
 * or a connection-closed event
 * (`event_kind == ASTER_EVENT_KIND_CONNECTION_CLOSED`). Bindings that
 * support session lifecycle reaping (spec §7.5) MUST handle both kinds.
 */
typedef struct aster_reactor_call_t {
  /**
   * Event-kind discriminator. See `ASTER_EVENT_KIND_*` constants.
   */
  uint8_t event_kind;
  /**
   * Reactor-assigned call ID (for submit correlation). Zero on
   * ConnectionClosed events.
   */
  uint64_t call_id;
  /**
   * Reactor-assigned unique ID for the QUIC connection this event
   * belongs to (spec §7.5). Same id is reused across every call from
   * this connection and emitted with the terminal ConnectionClosed
   * event so the binding can drop per-connection state. A peer that
   * disconnects and reconnects gets a fresh `connection_id`.
   */
  uint64_t connection_id;
  /**
   * Reactor-assigned unique ID for the QUIC bi-stream this call arrived
   * on. Multiplexed streams (spec §6) carry many calls per bi-stream,
   * so DO NOT key per-session state on `stream_id` — use
   * `(connection_id, StreamHeader.sessionId)` from the binding-decoded
   * header instead. Zero on ConnectionClosed events.
   */
  uint64_t stream_id;
  /**
   * Pointer to header payload bytes (owned by buffer registry).
   * NULL on ConnectionClosed events.
   */
  const uint8_t *header_ptr;
  /**
   * Length of header payload. Zero on ConnectionClosed events.
   */
  uint32_t header_len;
  /**
   * Header frame flags. Zero on ConnectionClosed events.
   */
  uint8_t header_flags;
  /**
   * Pointer to request payload bytes (owned by buffer registry).
   * NULL on ConnectionClosed events.
   */
  const uint8_t *request_ptr;
  /**
   * Length of request payload. Zero on ConnectionClosed events.
   */
  uint32_t request_len;
  /**
   * Request frame flags. Zero on ConnectionClosed events.
   */
  uint8_t request_flags;
  /**
   * Pointer to peer ID string (UTF-8, not null-terminated, owned by
   * buffer registry). Populated on both Call and ConnectionClosed.
   */
  const uint8_t *peer_ptr;
  /**
   * Length of peer ID string. Populated on both Call and
   * ConnectionClosed.
   */
  uint32_t peer_len;
  /**
   * Buffer ID for the header payload (release after processing). Zero
   * on ConnectionClosed events.
   */
  uint64_t header_buffer;
  /**
   * Buffer ID for the request payload. Zero on ConnectionClosed events.
   */
  uint64_t request_buffer;
  /**
   * Buffer ID for the peer ID string. Populated on both Call and
   * ConnectionClosed.
   */
  uint64_t peer_buffer;
} aster_reactor_call_t;

uint32_t iroh_abi_version_major(void);

uint32_t iroh_abi_version_minor(void);

uint32_t iroh_abi_version_patch(void);

int32_t iroh_runtime_new(const struct iroh_runtime_config_t *config, iroh_runtime_t *out_runtime);

int32_t iroh_runtime_close(iroh_runtime_t runtime);

int32_t iroh_secret_key_generate(uint8_t *out_key_ptr,
                                 uintptr_t out_key_capacity,
                                 uintptr_t *out_len);

uintptr_t iroh_poll_events(iroh_runtime_t runtime,
                           struct iroh_event_t *out_events,
                           uintptr_t max_events,
                           uint32_t timeout_ms);

int32_t iroh_buffer_release(iroh_runtime_t runtime, uint64_t buffer);

/**
 * Release a string allocated by `alloc_string`.
 * Java must call this to free strings returned via `iroh_bytes_t` fields
 * in structs that were allocated with Rust-owned memory (not caller-buffers).
 *
 * # Safety
 * - `ptr` must be a pointer returned by a Rust `alloc_string` call
 * - `len` must be the length passed back alongside `ptr`
 * - Must be called exactly once for each allocation
 * - `ptr` must not be null
 */
int32_t iroh_string_release(const uint8_t *ptr, uintptr_t len);

int32_t iroh_operation_cancel(iroh_runtime_t runtime, iroh_operation_t operation);

uintptr_t iroh_last_error_message(uint8_t *buffer, uintptr_t capacity);

const char *iroh_status_name(enum iroh_status_t status);

int32_t iroh_node_memory(iroh_runtime_t runtime,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

int32_t iroh_node_persistent(iroh_runtime_t runtime,
                             struct iroh_bytes_t path,
                             uint64_t user_data,
                             iroh_operation_t *out_operation);

int32_t iroh_node_close(iroh_runtime_t runtime,
                        iroh_node_t node,
                        uint64_t user_data,
                        iroh_operation_t *out_operation);

int32_t iroh_node_id(iroh_runtime_t runtime,
                     iroh_node_t node,
                     uint8_t *out_buf,
                     uintptr_t capacity,
                     uintptr_t *out_len);

int32_t iroh_node_addr_info(iroh_runtime_t runtime,
                            iroh_node_t node,
                            uint8_t *out_buf,
                            uintptr_t buf_capacity,
                            struct iroh_node_addr_t *out_addr);

int32_t iroh_node_export_secret_key(iroh_runtime_t runtime,
                                    iroh_node_t node,
                                    uint8_t *out_buf,
                                    uintptr_t capacity,
                                    uintptr_t *out_len);

int32_t iroh_endpoint_create(iroh_runtime_t runtime,
                             const struct iroh_endpoint_config_t *config,
                             uint64_t user_data,
                             iroh_operation_t *out_operation);

int32_t iroh_endpoint_close(iroh_runtime_t runtime,
                            iroh_endpoint_t endpoint,
                            uint64_t user_data,
                            iroh_operation_t *out_operation);

int32_t iroh_endpoint_id(iroh_runtime_t runtime,
                         iroh_endpoint_t endpoint,
                         uint8_t *out_buf,
                         uintptr_t capacity,
                         uintptr_t *out_len);

int32_t iroh_endpoint_export_secret_key(iroh_runtime_t runtime,
                                        iroh_endpoint_t endpoint,
                                        uint8_t *out_buf,
                                        uintptr_t capacity,
                                        uintptr_t *out_len);

int32_t iroh_endpoint_addr_info(iroh_runtime_t runtime,
                                iroh_endpoint_t endpoint,
                                uint8_t *out_buf,
                                uintptr_t buf_capacity,
                                struct iroh_node_addr_t *out_addr);

int32_t iroh_stream_stop(iroh_runtime_t runtime,
                         iroh_recv_stream_t recv_stream,
                         uint32_t error_code);

int32_t iroh_connect(iroh_runtime_t runtime,
                     uint64_t endpoint_or_node,
                     const struct iroh_connect_config_t *config,
                     uint64_t user_data,
                     iroh_operation_t *out_operation);

int32_t iroh_accept(iroh_runtime_t runtime,
                    uint64_t endpoint_or_node,
                    uint64_t user_data,
                    iroh_operation_t *out_operation);

/**
 * Create an in-memory node with blobs/docs/gossip + custom aster ALPNs.
 * Emits IROH_EVENT_NODE_CREATED on success.
 */
int32_t iroh_node_memory_with_alpns(iroh_runtime_t runtime,
                                    const uint8_t *const *alpns,
                                    const uintptr_t *alpn_lens,
                                    uintptr_t alpn_count,
                                    uint64_t user_data,
                                    iroh_operation_t *out_operation);

/**
 * Pull the next incoming aster-ALPN connection from the node's queue.
 * Long-poll: spawns a tokio task, emits IROH_EVENT_ASTER_ACCEPTED when a
 * connection arrives. event.handle = connection_handle, event.data_ptr/len
 * = ALPN bytes, event.buffer = lease to release via iroh_buffer_release.
 */
int32_t iroh_node_accept_aster(iroh_runtime_t runtime,
                               uint64_t node,
                               uint64_t user_data,
                               iroh_operation_t *out_operation);

int32_t iroh_connection_remote_id(iroh_runtime_t runtime,
                                  iroh_connection_t connection,
                                  uint8_t *out_buf,
                                  uintptr_t capacity,
                                  uintptr_t *out_len);

int32_t iroh_connection_close(iroh_runtime_t runtime,
                              iroh_connection_t connection,
                              uint32_t error_code,
                              struct iroh_bytes_t reason);

int32_t iroh_connection_closed(iroh_runtime_t runtime,
                               iroh_connection_t connection,
                               uint64_t user_data,
                               iroh_operation_t *out_operation);

int32_t iroh_connection_send_datagram(iroh_runtime_t runtime,
                                      iroh_connection_t connection,
                                      struct iroh_bytes_t data);

int32_t iroh_connection_read_datagram(iroh_runtime_t runtime,
                                      iroh_connection_t connection,
                                      uint64_t user_data,
                                      iroh_operation_t *out_operation);

int32_t iroh_open_bi(iroh_runtime_t runtime,
                     iroh_connection_t connection,
                     uint64_t user_data,
                     iroh_operation_t *out_operation);

int32_t iroh_accept_bi(iroh_runtime_t runtime,
                       iroh_connection_t connection,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

int32_t iroh_open_uni(iroh_runtime_t runtime,
                      iroh_connection_t connection,
                      uint64_t user_data,
                      iroh_operation_t *out_operation);

int32_t iroh_accept_uni(iroh_runtime_t runtime,
                        iroh_connection_t connection,
                        uint64_t user_data,
                        iroh_operation_t *out_operation);

int32_t iroh_stream_write(iroh_runtime_t runtime,
                          iroh_send_stream_t send_stream,
                          struct iroh_bytes_t data,
                          uint64_t user_data,
                          iroh_operation_t *out_operation);

int32_t iroh_stream_finish(iroh_runtime_t runtime,
                           iroh_send_stream_t send_stream,
                           uint64_t user_data,
                           iroh_operation_t *out_operation);

int32_t iroh_stream_read(iroh_runtime_t runtime,
                         iroh_recv_stream_t recv_stream,
                         uintptr_t max_len,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

int32_t iroh_stream_read_to_end(iroh_runtime_t runtime,
                                iroh_recv_stream_t recv_stream,
                                uintptr_t max_size,
                                uint64_t user_data,
                                iroh_operation_t *out_operation);

int32_t iroh_stream_read_exact(iroh_runtime_t runtime,
                               iroh_recv_stream_t recv_stream,
                               uintptr_t exact_len,
                               uint64_t user_data,
                               iroh_operation_t *out_operation);

int32_t iroh_stream_stopped(iroh_runtime_t runtime,
                            iroh_send_stream_t send_stream,
                            uint64_t user_data,
                            iroh_operation_t *out_operation);

int32_t iroh_add_node_addr(iroh_runtime_t runtime,
                           iroh_endpoint_t endpoint,
                           struct iroh_node_addr_t addr);

int32_t iroh_node_free(iroh_runtime_t runtime, iroh_node_t node);

int32_t iroh_endpoint_free(iroh_runtime_t runtime, iroh_endpoint_t endpoint);

int32_t iroh_connection_free(iroh_runtime_t runtime, iroh_connection_t connection);

int32_t iroh_send_stream_free(iroh_runtime_t runtime, iroh_send_stream_t stream);

int32_t iroh_recv_stream_free(iroh_runtime_t runtime, iroh_recv_stream_t stream);

int32_t iroh_doc_free(iroh_runtime_t runtime, uint64_t doc);

int32_t iroh_gossip_topic_free(iroh_runtime_t runtime, uint64_t topic);

int32_t iroh_blobs_add_bytes(iroh_runtime_t runtime,
                             iroh_node_t node,
                             struct iroh_bytes_t data,
                             uint64_t user_data,
                             iroh_operation_t *out_operation);

int32_t iroh_blobs_read(iroh_runtime_t runtime,
                        iroh_node_t node,
                        struct iroh_bytes_t hash_hex,
                        uint64_t user_data,
                        iroh_operation_t *out_operation);

/**
 * Store bytes as a single-file Collection (HashSeq), compatible with sendme.
 * Emits IROH_EVENT_BLOB_ADDED with the collection hash in the payload.
 */
int32_t iroh_blobs_add_bytes_as_collection(iroh_runtime_t runtime,
                                           iroh_node_t node,
                                           struct iroh_bytes_t name,
                                           struct iroh_bytes_t data,
                                           uint64_t user_data,
                                           iroh_operation_t *out_operation);

/**
 * Store a multi-file collection (HashSeq).
 *
 * `entries_json` is a UTF-8 JSON string: `[["name1","base64data1"],["name2","base64data2"]]`
 * Each entry's data is base64-encoded. The result (collection hash hex) is emitted as
 * `IROH_EVENT_BLOB_COLLECTION_ADDED` with the hash string in the event data buffer.
 */
int32_t iroh_blobs_add_collection(iroh_runtime_t runtime,
                                  iroh_node_t node,
                                  struct iroh_bytes_t entries_json,
                                  uint64_t user_data,
                                  iroh_operation_t *out_operation);

/**
 * List entries from a stored collection.
 *
 * `hash_hex` is the collection hash. The result is emitted as
 * `IROH_EVENT_BLOB_READ` with a JSON string:
 * `[["name1","hash_hex1",size1],["name2","hash_hex2",size2]]`
 */
int32_t iroh_blobs_list_collection(iroh_runtime_t runtime,
                                   iroh_node_t node,
                                   struct iroh_bytes_t hash_hex,
                                   uint64_t user_data,
                                   iroh_operation_t *out_operation);

/**
 * Create a ticket for a Collection (HashSeq format), compatible with sendme.
 * Writes the ticket string into the caller-provided buffer.
 */
int32_t iroh_blobs_create_collection_ticket(iroh_runtime_t runtime,
                                            iroh_node_t node,
                                            struct iroh_bytes_t hash_hex,
                                            uint8_t *out_buf,
                                            uintptr_t capacity,
                                            uintptr_t *out_len);

int32_t iroh_blobs_create_ticket(iroh_runtime_t runtime,
                                 iroh_node_t node,
                                 struct iroh_bytes_t hash_hex,
                                 uint8_t *out_buf,
                                 uintptr_t capacity,
                                 uintptr_t *out_len);

int32_t iroh_blobs_download(iroh_runtime_t runtime,
                            iroh_node_t node,
                            struct iroh_bytes_t ticket,
                            uint64_t user_data,
                            iroh_operation_t *out_operation);

/**
 * Check the status of a blob in the local store. Synchronous.
 *
 * Writes to `out_status`: 0 = not_found, 1 = partial, 2 = complete.
 * Writes to `out_size`: byte size (0 if not_found).
 */
int32_t iroh_blobs_status(iroh_runtime_t runtime,
                          iroh_node_t node,
                          const uint8_t *hash_hex_ptr,
                          uintptr_t hash_hex_len,
                          uint32_t *out_status,
                          uint64_t *out_size);

/**
 * Check if a blob is fully stored locally. Synchronous.
 *
 * Writes to `out_has`: 1 = complete/present, 0 = not complete.
 */
int32_t iroh_blobs_has(iroh_runtime_t runtime,
                       iroh_node_t node,
                       const uint8_t *hash_hex_ptr,
                       uintptr_t hash_hex_len,
                       uint32_t *out_has);

/**
 * Snapshot of the current bitfield for a blob.
 * Fills `out_is_complete` (1=complete, 0=partial/not-found) and `out_size` (total bytes, 0 if unknown).
 * Returns IROH_STATUS_NOT_FOUND if the node handle is unknown.
 * Returns IROH_STATUS_INVALID_ARGUMENT if any pointer is null.
 */
int32_t iroh_blobs_observe_snapshot(iroh_runtime_t runtime,
                                    iroh_node_t node,
                                    const uint8_t *hash_hex_ptr,
                                    uintptr_t hash_hex_len,
                                    uint32_t *out_is_complete,
                                    uint64_t *out_size);

/**
 * Wait until a blob is fully downloaded locally.
 * Emits IROH_EVENT_BLOB_OBSERVE_COMPLETE (via IROH_EVENT_UNIT_RESULT) when complete,
 * or an error event if the observation stream ends without completion.
 */
int32_t iroh_blobs_observe_complete(iroh_runtime_t runtime,
                                    iroh_node_t node,
                                    const uint8_t *hash_hex_ptr,
                                    uintptr_t hash_hex_len,
                                    uint64_t user_data,
                                    iroh_operation_t *out_operation);

/**
 * Check local availability of a blob using the Remote API.
 * Fills `out_is_complete` (1=complete, 0=partial) and `out_local_bytes` (bytes we have locally).
 * Returns IROH_STATUS_NOT_FOUND if the node handle is unknown.
 * Returns IROH_STATUS_INVALID_ARGUMENT if any pointer is null.
 */
int32_t iroh_blobs_local_info(iroh_runtime_t runtime,
                              iroh_node_t node,
                              const uint8_t *hash_hex_ptr,
                              uintptr_t hash_hex_len,
                              uint32_t *out_is_complete,
                              uint64_t *out_local_bytes);

/**
 * Set a named tag. format: 0 = raw, 1 = hash_seq. Emits IROH_EVENT_TAG_SET.
 */
int32_t iroh_tags_set(iroh_runtime_t runtime,
                      iroh_node_t node,
                      const uint8_t *name_ptr,
                      uintptr_t name_len,
                      const uint8_t *hash_hex_ptr,
                      uintptr_t hash_hex_len,
                      uint32_t format,
                      uint64_t user_data,
                      iroh_operation_t *out_operation);

/**
 * Get a tag by name. Emits IROH_EVENT_TAG_GET with payload on found, NOT_FOUND status if absent.
 */
int32_t iroh_tags_get(iroh_runtime_t runtime,
                      iroh_node_t node,
                      const uint8_t *name_ptr,
                      uintptr_t name_len,
                      uint64_t user_data,
                      iroh_operation_t *out_operation);

/**
 * Delete a tag by name. Emits IROH_EVENT_TAG_DELETED with count in event.flags.
 */
int32_t iroh_tags_delete(iroh_runtime_t runtime,
                         iroh_node_t node,
                         const uint8_t *name_ptr,
                         uintptr_t name_len,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

/**
 * List tags matching a prefix (empty prefix = all tags).
 * Emits IROH_EVENT_TAG_LIST with packed tag records in payload; event.flags = count.
 */
int32_t iroh_tags_list_prefix(iroh_runtime_t runtime,
                              iroh_node_t node,
                              const uint8_t *prefix_ptr,
                              uintptr_t prefix_len,
                              uint64_t user_data,
                              iroh_operation_t *out_operation);

int32_t iroh_docs_create(iroh_runtime_t runtime,
                         iroh_node_t node,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

int32_t iroh_docs_create_author(iroh_runtime_t runtime,
                                iroh_node_t node,
                                uint64_t user_data,
                                iroh_operation_t *out_operation);

int32_t iroh_docs_join(iroh_runtime_t runtime,
                       iroh_node_t node,
                       struct iroh_bytes_t ticket,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

int32_t iroh_doc_set_bytes(iroh_runtime_t runtime,
                           uint64_t doc,
                           struct iroh_bytes_t author_hex,
                           struct iroh_bytes_t key,
                           struct iroh_bytes_t value,
                           uint64_t user_data,
                           iroh_operation_t *out_operation);

int32_t iroh_doc_get_exact(iroh_runtime_t runtime,
                           uint64_t doc,
                           struct iroh_bytes_t author_hex,
                           struct iroh_bytes_t key,
                           uint64_t user_data,
                           iroh_operation_t *out_operation);

int32_t iroh_doc_share(iroh_runtime_t runtime,
                       uint64_t doc,
                       uint32_t mode,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

int32_t iroh_doc_query(iroh_runtime_t runtime,
                       uint64_t doc,
                       uint32_t mode,
                       struct iroh_bytes_t key,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

/**
 * Read the content bytes for a doc entry given its content hash.
 */
int32_t iroh_doc_read_entry_content(iroh_runtime_t runtime,
                                    uint64_t doc,
                                    struct iroh_bytes_t content_hash_hex,
                                    uint64_t user_data,
                                    iroh_operation_t *out_operation);

/**
 * Start syncing a document with the specified peers (endpoint-ID hex strings).
 * Emits IROH_EVENT_UNIT_RESULT on completion.
 */
int32_t iroh_doc_start_sync(iroh_runtime_t runtime,
                            uint64_t doc,
                            struct iroh_bytes_list_t peers,
                            uint64_t user_data,
                            iroh_operation_t *out_operation);

/**
 * Leave (stop syncing) a document.
 * Emits IROH_EVENT_UNIT_RESULT on completion.
 */
int32_t iroh_doc_leave(iroh_runtime_t runtime,
                       uint64_t doc,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

/**
 * Subscribe to live document events.
 * Emits IROH_EVENT_DOC_SUBSCRIBED (status=OK, handle=receiver_handle) on success.
 */
int32_t iroh_doc_subscribe(iroh_runtime_t runtime,
                           uint64_t doc,
                           uint64_t user_data,
                           iroh_operation_t *out_operation);

/**
 * Receive the next live document event (long-poll, like gossip_recv).
 * Emits IROH_EVENT_DOC_EVENT with event.subtype indicating the event kind and
 * packed data in the payload.  When the subscription ends, emits with status=NOT_FOUND.
 */
int32_t iroh_doc_event_recv(iroh_runtime_t runtime,
                            uint64_t receiver,
                            uint64_t user_data,
                            iroh_operation_t *out_operation);

/**
 * Set the download policy for a document.
 * prefixes: list of byte-string prefixes (used for NOTHING_EXCEPT / EVERYTHING_EXCEPT modes).
 * Emits IROH_EVENT_UNIT_RESULT on success.
 */
int32_t iroh_doc_set_download_policy(iroh_runtime_t runtime,
                                     uint64_t doc,
                                     uint32_t mode,
                                     struct iroh_bytes_list_t prefixes,
                                     uint64_t user_data,
                                     iroh_operation_t *out_operation);

/**
 * Share a document with full relay+address info (AddrInfoOptions::RelayAndAddresses).
 * mode: 0 = read, 1 = write.
 * Emits IROH_EVENT_DOC_SHARED with the ticket string in the payload.
 */
int32_t iroh_doc_share_with_addr(iroh_runtime_t runtime,
                                 uint64_t doc,
                                 uint32_t mode,
                                 uint64_t user_data,
                                 iroh_operation_t *out_operation);

/**
 * Join a document and subscribe to live events atomically.
 * Emits IROH_EVENT_DOC_JOINED_AND_SUBSCRIBED:
 *   event.handle = doc handle
 *   event.flags  = event-receiver handle
 */
int32_t iroh_docs_join_and_subscribe(iroh_runtime_t runtime,
                                     iroh_node_t node,
                                     struct iroh_bytes_t ticket,
                                     uint64_t user_data,
                                     iroh_operation_t *out_operation);

int32_t iroh_gossip_subscribe(iroh_runtime_t runtime,
                              iroh_node_t node,
                              struct iroh_bytes_t topic,
                              struct iroh_bytes_list_t peers,
                              uint64_t user_data,
                              iroh_operation_t *out_operation);

int32_t iroh_gossip_broadcast(iroh_runtime_t runtime,
                              uint64_t topic,
                              struct iroh_bytes_t data,
                              uint64_t user_data,
                              iroh_operation_t *out_operation);

int32_t iroh_gossip_recv(iroh_runtime_t runtime,
                         uint64_t topic,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

int32_t iroh_connection_max_datagram_size(iroh_runtime_t runtime,
                                          iroh_connection_t connection,
                                          uint64_t *out_size,
                                          uint32_t *out_is_some);

int32_t iroh_connection_datagram_send_buffer_space(iroh_runtime_t runtime,
                                                   iroh_connection_t connection,
                                                   uint64_t *out_bytes);

int32_t iroh_endpoint_remote_info(iroh_runtime_t runtime,
                                  uint64_t endpoint_or_node,
                                  struct iroh_bytes_t node_id,
                                  struct iroh_remote_info_t *out_info);

int32_t iroh_endpoint_remote_info_list(iroh_runtime_t runtime,
                                       uint64_t endpoint_or_node,
                                       struct iroh_remote_info_t *out_infos,
                                       uintptr_t max_infos,
                                       uintptr_t *out_count);

int32_t iroh_connection_info(iroh_runtime_t runtime,
                             iroh_connection_t connection,
                             struct iroh_connection_info_t *out_info);

/**
 * Respond to a pending before_connect hook invocation.
 *
 * `decision` is IROH_HOOK_DECISION_ALLOW (0) or IROH_HOOK_DECISION_DENY (1).
 * Calling this consumes the invocation; a second call returns NOT_FOUND.
 */
int32_t iroh_hook_before_connect_respond(iroh_runtime_t runtime,
                                         iroh_hook_invocation_t invocation,
                                         enum iroh_hook_decision_t decision);

/**
 * Respond to a pending after_connect hook invocation (always accepts).
 *
 * Calling this consumes the invocation; a second call returns NOT_FOUND.
 */
int32_t iroh_hook_after_connect_respond(iroh_runtime_t runtime, iroh_hook_invocation_t invocation);

/**
 * Snapshot current transport metrics from the iroh endpoint.
 *
 * `endpoint_or_node` may be either an endpoint handle or a node handle.
 * Writes the metrics into `out_metrics`.
 */
int32_t iroh_endpoint_transport_metrics(iroh_runtime_t runtime,
                                        uint64_t endpoint_or_node,
                                        struct iroh_transport_metrics_t *out_metrics);

/**
 * Compute contract_id from a ServiceContract JSON string.
 * Writes 64-byte hex string (no null terminator) to out_buf.
 * On BUFFER_TOO_SMALL, sets `*out_len` to required size.
 */
int32_t aster_contract_id(const uint8_t *json_ptr,
                          uintptr_t json_len,
                          uint8_t *out_buf,
                          uintptr_t *out_len);

/**
 * Compute canonical bytes for a named type from JSON.
 * `type_name`: `"ServiceContract"`, `"TypeDef"`, or `"MethodDef"`.
 */
int32_t aster_canonical_bytes(const uint8_t *type_name_ptr,
                              uintptr_t type_name_len,
                              const uint8_t *json_ptr,
                              uintptr_t json_len,
                              uint8_t *out_buf,
                              uintptr_t *out_len);

/**
 * BLAKE3 hash of arbitrary bytes → 64-char lowercase hex.
 *
 * General-purpose primitive for bindings that need to hash canonical output from
 * [`aster_canonical_bytes`] (e.g. per-TypeDef hashing when assembling a
 * [`ServiceContract`](aster_transport_core::contract::ServiceContract) for
 * [`aster_contract_id`]). Mirrors what PyO3 already exposes to Python as
 * `_native.contract.compute_type_hash`.
 *
 * Writes 64 bytes of hex to `out_buf`. On `BUFFER_TOO_SMALL`, sets `*out_len` to
 * the required size (64). `bytes_len == 0` is valid and hashes the empty input.
 */
int32_t aster_blake3_hex(const uint8_t *bytes_ptr,
                         uintptr_t bytes_len,
                         uint8_t *out_buf,
                         uintptr_t *out_len);

/**
 * Compute canonical signing bytes from credential JSON.
 *
 * The JSON must contain a `"kind"` field (`"producer"` or `"consumer"`)
 * to dispatch to the correct signing bytes format.
 */
int32_t aster_signing_bytes(const uint8_t *json_ptr,
                            uintptr_t json_len,
                            uint8_t *out_buf,
                            uintptr_t *out_len);

/**
 * Canonical JSON normalization: parse, sort all keys recursively, re-serialize compact.
 *
 * This is a general-purpose canonical form — not specific to credentials or contracts.
 * Useful for computing deterministic hashes of arbitrary JSON payloads.
 */
int32_t aster_canonical_json(const uint8_t *json_ptr,
                             uintptr_t json_len,
                             uint8_t *out_buf,
                             uintptr_t *out_len);

/**
 * Encode an AsterTicket to a base58 string (``aster1<base58>``).
 *
 * # Parameters
 * - `endpoint_id_hex`: 64-char hex endpoint ID
 * - `relay_addr_ptr/len`: relay "ip:port" string (NULL/0 for none)
 * - `direct_addrs_json_ptr/len`: JSON array of "ip:port" strings (NULL/0 for none)
 * - `credential_type_ptr/len`: credential type string: "open", "consumer_rcan",
 *   "enrollment", "registry_read" (NULL/0 for none)
 * - `credential_data_ptr/len`: credential payload bytes (NULL/0 for none)
 * - `out_buf/out_len`: output buffer for the aster1... string
 */
int32_t aster_ticket_encode(const uint8_t *endpoint_id_hex_ptr,
                            uintptr_t endpoint_id_hex_len,
                            const uint8_t *relay_addr_ptr,
                            uintptr_t relay_addr_len,
                            const uint8_t *direct_addrs_json_ptr,
                            uintptr_t direct_addrs_json_len,
                            const uint8_t *credential_type_ptr,
                            uintptr_t credential_type_len,
                            const uint8_t *credential_data_ptr,
                            uintptr_t credential_data_len,
                            uint8_t *out_buf,
                            uintptr_t *out_len);

/**
 * Decode an AsterTicket from a base58 string (``aster1<base58>``).
 *
 * Writes a JSON object to `out_buf`:
 * ```json
 * {
 *   "endpoint_id": "hex...",
 *   "relay_addr": "ip:port" | null,
 *   "direct_addrs": ["ip:port", ...],
 *   "credential_type": "open" | "consumer_rcan" | "enrollment" | "registry_read" | null,
 *   "credential_data_hex": "hex..." | null
 * }
 * ```
 */
int32_t aster_ticket_decode(const uint8_t *ticket_ptr,
                            uintptr_t ticket_len,
                            uint8_t *out_buf,
                            uintptr_t *out_len);

/**
 * Return the current wall-clock epoch-millis as seen by the Rust runtime.
 * Single shared clock across all bindings prevents time-skew in lease freshness checks.
 */
int64_t aster_registry_now_epoch_ms(void);

/**
 * Report whether a lease is still fresh given the lease duration window.
 * `lease_json` is a single EndpointLease JSON object.
 * Returns 1 = fresh, 0 = expired, negative = error (see set_last_error).
 */
int32_t aster_registry_is_fresh(const uint8_t *lease_json_ptr,
                                uintptr_t lease_json_len,
                                int32_t lease_duration_s);

/**
 * Report whether a health status string is routable (READY or DEGRADED).
 * `status_json` is a UTF-8 string (not JSON-quoted).
 */
int32_t aster_registry_is_routable(const uint8_t *status_ptr, uintptr_t status_len);

/**
 * Apply mandatory filters + ranking to a list of EndpointLease JSON objects.
 *
 * Input:
 * - `leases_json`: a JSON array of EndpointLease objects.
 * - `opts_json`: a ResolveOptions JSON object with fields:
 *   service (string), version (int|null), channel (string|null),
 *   contract_id (string|null), strategy (string), caller_alpn (string),
 *   caller_serialization_modes (array), caller_policy_realm (string|null),
 *   lease_duration_s (int).
 *
 * Output (written to `out_buf`): a JSON array of EndpointLease objects in
 * ranked order. The top element is the resolved winner. If the output buffer
 * is too small, returns `BUFFER_TOO_SMALL` and sets `*out_len` to the
 * required size.
 *
 * Note: the round-robin rotation state is reset on every call (stateless).
 * Stateful multi-call round-robin will be added when the async resolve FFI
 * lands; for now, bindings should maintain their own rotation counter or
 * accept per-call randomization.
 */
int32_t aster_registry_filter_and_rank(const uint8_t *leases_json_ptr,
                                       uintptr_t leases_json_len,
                                       const uint8_t *opts_json_ptr,
                                       uintptr_t opts_json_len,
                                       uint8_t *out_buf,
                                       uintptr_t *out_len);

/**
 * Return one of the registry key-schema strings by kind, for all bindings to share.
 *
 * `kind` values:
 *   0 = contract_key(arg1)
 *   1 = version_key(arg1, arg2 as int)
 *   2 = channel_key(arg1, arg2)
 *   3 = lease_key(arg1, arg2, arg3)
 *   4 = lease_prefix(arg1, arg2)
 *   5 = acl_key(arg1)
 *
 * `arg1/arg2/arg3` are UTF-8 strings. For version_key, arg2 must parse as i32.
 */
int32_t aster_registry_key(int32_t kind,
                           const uint8_t *arg1_ptr,
                           uintptr_t arg1_len,
                           const uint8_t *arg2_ptr,
                           uintptr_t arg2_len,
                           const uint8_t *arg3_ptr,
                           uintptr_t arg3_len,
                           uint8_t *out_buf,
                           uintptr_t *out_len);

/**
 * Async resolve: pointer lookup → list_leases → seq filter → mandatory filters → rank.
 *
 * Inputs:
 * - `doc`: a doc handle previously returned by `iroh_doc_create` / `iroh_doc_join`.
 * - `opts_json`: ResolveOptions JSON (same shape as `aster_registry_filter_and_rank`).
 *
 * On success emits `IROH_EVENT_REGISTRY_RESOLVED`. The event payload is the JSON
 * of the winning EndpointLease, or empty with `IROH_STATUS_NOT_FOUND` if no
 * candidate survived the filters.
 */
int32_t aster_registry_resolve(iroh_runtime_t runtime,
                               uint64_t doc,
                               struct iroh_bytes_t opts_json,
                               uint64_t user_data,
                               iroh_operation_t *out_operation);

/**
 * Publish a lease and/or an artifact in a single op.
 *
 * Either or both of `lease_json` / `artifact_json` may be provided (pass an
 * empty `iroh_bytes_t` to skip). For artifact publication, `service` and
 * `version` must be set; `channel` is optional. `gossip_topic` is a topic
 * handle to broadcast the corresponding GossipEvent on, or 0 to skip.
 *
 * Emits `IROH_EVENT_REGISTRY_PUBLISHED` on success.
 */
int32_t aster_registry_publish(iroh_runtime_t runtime,
                               uint64_t doc,
                               struct iroh_bytes_t author_id,
                               struct iroh_bytes_t lease_json,
                               struct iroh_bytes_t artifact_json,
                               struct iroh_bytes_t service,
                               int32_t version,
                               struct iroh_bytes_t channel,
                               uint64_t gossip_topic,
                               uint64_t user_data,
                               iroh_operation_t *out_operation);

/**
 * Renew an existing lease in place. Reads the current row, bumps lease_seq +
 * timestamps, updates health/load, rewrites it.
 *
 * `load` uses NaN as a sentinel for "no load reported".
 * Emits `IROH_EVENT_REGISTRY_RENEWED` on success.
 */
int32_t aster_registry_renew_lease(iroh_runtime_t runtime,
                                   uint64_t doc,
                                   struct iroh_bytes_t author_id,
                                   struct iroh_bytes_t service,
                                   struct iroh_bytes_t contract_id,
                                   struct iroh_bytes_t endpoint_id,
                                   struct iroh_bytes_t health,
                                   float load,
                                   int32_t lease_duration_s,
                                   uint64_t gossip_topic,
                                   uint64_t user_data,
                                   iroh_operation_t *out_operation);

/**
 * Add an author to the per-doc registry ACL writer set, persisting it to the
 * doc under `_aster/acl/writers`. Switches the ACL out of open mode if it was
 * in open mode. Emits `IROH_EVENT_REGISTRY_ACL_UPDATED` on success.
 */
int32_t aster_registry_acl_add_writer(iroh_runtime_t runtime,
                                      uint64_t doc,
                                      struct iroh_bytes_t author_id,
                                      struct iroh_bytes_t writer_id,
                                      uint64_t user_data,
                                      iroh_operation_t *out_operation);

/**
 * Remove an author from the per-doc registry ACL writer set and persist the
 * updated list. Emits `IROH_EVENT_REGISTRY_ACL_UPDATED` on success.
 */
int32_t aster_registry_acl_remove_writer(iroh_runtime_t runtime,
                                         uint64_t doc,
                                         struct iroh_bytes_t author_id,
                                         struct iroh_bytes_t writer_id,
                                         uint64_t user_data,
                                         iroh_operation_t *out_operation);

/**
 * List the current writer set for the per-doc registry ACL.
 *
 * Emits `IROH_EVENT_REGISTRY_ACL_LISTED`. The event payload is a JSON array
 * of AuthorId strings. If the ACL is in open mode (no writers added yet),
 * the array is empty.
 */
int32_t aster_registry_acl_list_writers(iroh_runtime_t runtime,
                                        uint64_t doc,
                                        uint64_t user_data,
                                        iroh_operation_t *out_operation);

/**
 * Acquire a call handle from the connection's per-connection
 * multiplexed-stream pool. `session_id == 0` selects the SHARED
 * pool; non-zero selects the session pool keyed by that id.
 *
 * Blocks (on the FFI thread, via `block_on`) up to the pool's
 * configured `stream_acquire_timeout`. On success, writes a non-zero
 * call handle to `*out_call`. On failure, returns one of the
 * `ASTER_CALL_ERR_*` codes (negative) or an `iroh_status_t` code.
 */
int32_t aster_call_acquire(iroh_runtime_t runtime,
                           iroh_connection_t connection,
                           uint32_t session_id,
                           aster_call_t *out_call);

/**
 * Acquire a **streaming** call handle. Unlike `aster_call_acquire`,
 * this bypasses the per-connection pool entirely and opens a
 * dedicated multiplexed substream via `CoreConnection::open_bi` —
 * per `ffi_spec/Aster-multiplexed-streams.md` §3 line 65, "streaming
 * substreams don't count against any pool." Use this for
 * server-stream / client-stream / bidi calls.
 *
 * The substream is bounded only by the QUIC `max_concurrent_streams`
 * ceiling. It is closed on `aster_call_release` or `aster_call_discard`.
 *
 * `session_id` is not used by this entry point — the binding carries
 * the session id in the `StreamHeader` it sends itself. Kept out of
 * the signature to make the "no pool involvement" intent unambiguous.
 */
int32_t aster_call_acquire_streaming(iroh_runtime_t runtime,
                                     iroh_connection_t connection,
                                     aster_call_t *out_call);

/**
 * Push a frame on a call's request side.
 *
 * `frame_ptr` / `frame_len` point to already-framed bytes (including
 * the 4-byte little-endian length prefix and 1-byte flags). The
 * binding is responsible for framing — this matches
 * `aster_reactor_submit_frame`'s contract.
 *
 * Blocks on the FFI thread until the underlying QUIC `write_all`
 * completes.
 */
int32_t aster_call_send_frame(iroh_runtime_t runtime,
                              aster_call_t call,
                              const uint8_t *frame_ptr,
                              uint32_t frame_len);

/**
 * Pull the next response frame on a call. Blocks up to `timeout_ms`
 * waiting for the next frame on the recv side.
 *
 * On `ASTER_CALL_RECV_OK` (return value 0), writes:
 * - `*out_payload_ptr` — pointer to payload bytes (owned by
 *   `CALL_BUFFERS`; release via `aster_call_buffer_release`).
 * - `*out_payload_len` — payload length in bytes.
 * - `*out_flags` — frame flags byte. Bindings inspect `FLAG_TRAILER`
 *   to detect end-of-call.
 * - `*out_buffer_id` — buffer registry id for releasing the payload.
 *
 * On `ASTER_CALL_RECV_TIMEOUT` (return value 2), no out parameters
 * are touched and the call remains valid for further recv attempts.
 *
 * On `ASTER_CALL_RECV_END_OF_STREAM` (return value 1), the underlying
 * QUIC recv side has closed; further recvs will keep returning EOF.
 * The binding should release/discard the call.
 *
 * Negative return values are `iroh_status_t` error codes.
 */
int32_t aster_call_recv_frame(iroh_runtime_t runtime,
                              aster_call_t call,
                              uint32_t timeout_ms,
                              const uint8_t **out_payload_ptr,
                              uint32_t *out_payload_len,
                              uint8_t *out_flags,
                              iroh_buffer_t *out_buffer_id);

/**
 * Release a call on the success path. The underlying multiplexed
 * stream returns to the connection's pool (LIFO) for reuse by the
 * next acquire.
 *
 * MUST be called only when no concurrent `send_frame` / `recv_frame`
 * is in flight on this call. Calling release with leftover unread
 * bytes on the recv side would corrupt the next call that reuses
 * the stream — the binding MUST drain to the trailer first.
 */
int32_t aster_call_release(iroh_runtime_t runtime, aster_call_t call);

/**
 * Discard a call on the error path. The underlying multiplexed
 * stream is dropped (not returned to the pool); the pool slot is
 * freed and any blocked waiter is woken to either reuse a freed
 * slot or surface the same transport error.
 *
 * Use this when:
 * - A `send_frame` or `recv_frame` returned an error.
 * - The call was cancelled mid-flight (FLAG_CANCEL).
 * - The recv side returned `ASTER_CALL_RECV_END_OF_STREAM` before
 *   the trailer was seen.
 */
int32_t aster_call_discard(iroh_runtime_t runtime, aster_call_t call);

/**
 * Release a buffer obtained from `aster_call_recv_frame`. Each
 * buffer id returned by recv MUST be released exactly once.
 */
int32_t aster_call_buffer_release(iroh_runtime_t runtime, iroh_buffer_t buffer);

/**
 * Unary fast-path (spec §8). Collapses
 * `acquire` + `send_frame(header)` + `send_frame(request)` +
 * `recv_frame(response)` + `recv_frame(trailer)` + `release` into a
 * single FFI entry point and a single `block_on`. Bindings whose
 * hot-path is dominated by FFI roundtrips (e.g. Java FFM, where every
 * `block_on` parks a platform thread) see ~5-6× fewer FFI hops per
 * unary call.
 *
 * `request_pair_ptr` / `request_pair_len` is a single buffer holding
 * the already-framed StreamHeader frame *concatenated with* the
 * already-framed request frame:
 *
 * ```text
 *   [4B LE len][1B FLAG_HEADER][header_payload]
 *   [4B LE len][1B request_flags][request_payload]
 * ```
 *
 * The Rust side writes the whole buffer in one `write_all` so Quinn's
 * flow control sees one logical write.
 *
 * On success, populates four sets of out parameters:
 * - `out_response_*` — the FIRST non-row-schema response frame on the
 *   stream, or zero-length if the dispatcher only sent a trailer.
 * - `out_trailer_*` — the trailer frame's payload (an encoded
 *   `RpcStatus`). Always populated on success; zero-length if the
 *   dispatcher sent an empty OK trailer.
 *
 * Each populated payload comes with its own buffer id; bindings MUST
 * call `aster_call_buffer_release` for every non-zero buffer id
 * returned. Skipped row-schema frames are released internally.
 *
 * On error returns the appropriate `ASTER_CALL_ERR_*` (acquire failure)
 * or `IROH_STATUS_INTERNAL` (transport / framing failure); no out
 * parameters are populated. The pool slot is freed on every error path.
 */
int32_t aster_call_unary(iroh_runtime_t runtime,
                         iroh_connection_t connection,
                         uint32_t session_id,
                         const uint8_t *request_pair_ptr,
                         uint32_t request_pair_len,
                         const uint8_t **out_response_ptr,
                         uint32_t *out_response_len,
                         uint8_t *out_response_flags,
                         iroh_buffer_t *out_response_buffer,
                         const uint8_t **out_trailer_ptr,
                         uint32_t *out_trailer_len,
                         iroh_buffer_t *out_trailer_buffer);

void aster_probe_reset(void);

int32_t aster_probe_dump_unary_csv(const uint8_t *path_ptr, uint32_t path_len);

/**
 * Create a reactor attached to a node. The reactor starts accepting
 * connections and delivering calls via the SPSC ring.
 *
 * `ring_capacity` is rounded up to the next power of two.
 * `out_reactor` receives the reactor handle on success.
 */
int32_t aster_reactor_create(iroh_runtime_t runtime,
                             iroh_node_t node,
                             uint32_t ring_capacity,
                             aster_reactor_t *out_reactor);

/**
 * Destroy a reactor. Stops the pump task and releases resources.
 */
int32_t aster_reactor_destroy(iroh_runtime_t runtime, aster_reactor_t reactor);

/**
 * Poll for incoming calls. Drains up to `max_calls` from the ring buffer
 * into the caller-provided `out_calls` array. Returns the number of calls
 * written.
 *
 * If `timeout_ms` is 0, returns immediately (non-blocking).
 * If `timeout_ms` > 0, blocks up to that duration waiting for at least one call.
 *
 * The caller must release each call's buffers via `iroh_buffer_release` after
 * processing (using the reactor's buffer registry, not the runtime's).
 */
uint32_t aster_reactor_poll(iroh_runtime_t runtime,
                            aster_reactor_t reactor,
                            struct aster_reactor_call_t *out_calls,
                            uint32_t max_calls,
                            uint32_t timeout_ms);

/**
 * Submit a unary response (single response frame + trailer) in one FFI call.
 *
 * Convenience wrapper over `aster_reactor_submit_frame` + `aster_reactor_submit_trailer`
 * for the unary path. For server-streaming or bidi, call `submit_frame` N times
 * then `submit_trailer` once.
 *
 * After this call, the call_id is no longer valid.
 */
int32_t aster_reactor_submit(iroh_runtime_t runtime,
                             aster_reactor_t reactor,
                             uint64_t call_id,
                             const uint8_t *response_ptr,
                             uint32_t response_len,
                             const uint8_t *trailer_ptr,
                             uint32_t trailer_len);

/**
 * Submit one streaming response frame for a call. May be called multiple
 * times per call; each call enqueues one Frame on the reactor's mpsc channel.
 * The call_id remains valid until `aster_reactor_submit_trailer` is called.
 *
 * `frame_ptr`/`frame_len` point to already-framed bytes (including the 4-byte
 * length prefix and 1-byte flags). The binding is responsible for framing.
 */
int32_t aster_reactor_submit_frame(iroh_runtime_t runtime,
                                   aster_reactor_t reactor,
                                   uint64_t call_id,
                                   const uint8_t *frame_ptr,
                                   uint32_t frame_len);

/**
 * Submit the trailer for a call and close the stream. After this call, the
 * `call_id` is no longer valid. The trailer payload may be empty — the
 * reactor still finishes the send side cleanly.
 */
int32_t aster_reactor_submit_trailer(iroh_runtime_t runtime,
                                     aster_reactor_t reactor,
                                     uint64_t call_id,
                                     const uint8_t *trailer_ptr,
                                     uint32_t trailer_len);

/**
 * Pull the next ADDITIONAL request frame for a client-streaming or
 * bidi-streaming call. Blocks up to `timeout_ms` waiting for a frame.
 *
 * On `ASTER_RECV_FRAME_OK` (return value 0), the function writes:
 * - `*out_payload_ptr`: pointer to payload bytes (owned by the reactor's
 *   buffer registry — must be released via `aster_reactor_buffer_release`)
 * - `*out_payload_len`: payload length in bytes
 * - `*out_flags`: frame flags byte (peer may set `FLAG_END_STREAM` here on
 *   the last frame; the binding may use that as a hint but is not required
 *   to — the reactor will also surface end-of-stream as
 *   `ASTER_RECV_FRAME_END_OF_STREAM` on the next call)
 * - `*out_buffer_id`: registry id for releasing the payload buffer
 *
 * On `ASTER_RECV_FRAME_END_OF_STREAM` (return value 1) or
 * `ASTER_RECV_FRAME_TIMEOUT` (return value 2), no out parameters are
 * touched and the call_id remains valid for further recv attempts (in the
 * timeout case) or is now drained (end-of-stream case — further calls
 * will continue to return end-of-stream).
 *
 * Negative return values are `iroh_status_t` error codes (e.g.
 * `IROH_STATUS_NOT_FOUND` if the call_id is unknown).
 *
 * The first request frame is delivered inline via `aster_reactor_poll`'s
 * `request_ptr` / `request_len` / `request_flags` fields. This function
 * is for SUBSEQUENT frames only.
 */
int32_t aster_reactor_recv_frame(iroh_runtime_t runtime,
                                 aster_reactor_t reactor,
                                 uint64_t call_id,
                                 uint32_t timeout_ms,
                                 const uint8_t **out_payload_ptr,
                                 uint32_t *out_payload_len,
                                 uint8_t *out_flags,
                                 uint64_t *out_buffer_id);

/**
 * Check whether the given call has been cancelled by the peer (or by a
 * stream-level error). Streaming dispatchers should poll this from any
 * long-running emit loop and stop early when it returns 1.
 *
 * Returns:
 *   0 — call is alive (no cancellation observed yet)
 *   1 — call has been cancelled (peer sent FLAG_CANCEL or stream errored)
 *  <0 — `iroh_status_t` error code (e.g. NOT_FOUND if the call_id is unknown,
 *       which the binding may treat as "no longer cancellable" — typically
 *       maps to "already completed")
 */
int32_t aster_reactor_check_cancelled(iroh_runtime_t runtime,
                                      aster_reactor_t reactor,
                                      uint64_t call_id);

/**
 * Release a buffer obtained from a reactor call descriptor.
 * Each buffer ID from aster_reactor_call_t must be released exactly once.
 */
int32_t aster_reactor_buffer_release(iroh_runtime_t runtime,
                                     aster_reactor_t reactor,
                                     uint64_t buffer);
