/* Generated by cbindgen */

/* Generated with cbindgen:0.29.2 */

/* DO NOT EDIT */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define IROH_ABI_VERSION_MAJOR 1

#define IROH_ABI_VERSION_MINOR 0

#define IROH_ABI_VERSION_PATCH 0

/**
 * Status codes
 */
typedef enum iroh_status_t {
  IROH_STATUS_OK = 0,
  IROH_STATUS_INVALID_ARGUMENT = 1,
  IROH_STATUS_NOT_FOUND = 2,
  IROH_STATUS_ALREADY_CLOSED = 3,
  IROH_STATUS_QUEUE_FULL = 4,
  IROH_STATUS_BUFFER_TOO_SMALL = 5,
  IROH_STATUS_UNSUPPORTED = 6,
  IROH_STATUS_INTERNAL = 7,
  IROH_STATUS_TIMEOUT = 8,
  IROH_STATUS_CANCELLED = 9,
  IROH_STATUS_CONNECTION_REFUSED = 10,
  IROH_STATUS_STREAM_RESET = 11,
} iroh_status_t;

/**
 * Hook decision
 */
typedef enum iroh_hook_decision_t {
  IROH_HOOK_DECISION_ALLOW = 0,
  IROH_HOOK_DECISION_DENY = 1,
} iroh_hook_decision_t;

typedef struct iroh_runtime_config_t {
  uint32_t struct_size;
  uint32_t worker_threads;
  uint32_t event_queue_capacity;
  uint32_t reserved;
} iroh_runtime_config_t;

/**
 * Opaque handle types
 */
typedef uint64_t iroh_runtime_t;

/**
 * C-compatible event structure for FFI output
 */
typedef struct iroh_event_t {
  uint32_t struct_size;
  uint32_t kind;
  uint32_t status;
  uint64_t operation;
  uint64_t handle;
  uint64_t related;
  uint64_t user_data;
  const uint8_t *data_ptr;
  uintptr_t data_len;
  uint64_t buffer;
  int32_t error_code;
  uint32_t flags;
} iroh_event_t;

typedef uint64_t iroh_operation_t;

typedef struct iroh_bytes_t {
  const uint8_t *ptr;
  uintptr_t len;
} iroh_bytes_t;

typedef uint64_t iroh_node_t;

typedef struct iroh_bytes_list_t {
  const struct iroh_bytes_t *items;
  uintptr_t len;
} iroh_bytes_list_t;

typedef struct iroh_node_addr_t {
  struct iroh_bytes_t endpoint_id;
  struct iroh_bytes_t relay_url;
  struct iroh_bytes_list_t direct_addresses;
} iroh_node_addr_t;

typedef struct iroh_endpoint_config_t {
  uint32_t struct_size;
  uint32_t relay_mode;
  struct iroh_bytes_t secret_key;
  struct iroh_bytes_list_t alpns;
  struct iroh_bytes_list_t relay_urls;
  uint32_t enable_discovery;
  uint32_t enable_hooks;
  uint64_t hook_timeout_ms;
  struct iroh_bytes_t bind_addr;
  uint32_t clear_ip_transports;
  uint32_t clear_relay_transports;
  uint32_t portmapper_config;
  struct iroh_bytes_t proxy_url;
  uint32_t proxy_from_env;
  struct iroh_bytes_t data_dir_utf8;
} iroh_endpoint_config_t;

typedef uint64_t iroh_endpoint_t;

typedef uint64_t iroh_recv_stream_t;

typedef struct iroh_connect_config_t {
  uint32_t struct_size;
  uint32_t flags;
  struct iroh_bytes_t node_id;
  struct iroh_bytes_t alpn;
  const struct iroh_node_addr_t *addr;
} iroh_connect_config_t;

typedef uint64_t iroh_connection_t;

typedef uint64_t iroh_send_stream_t;

typedef struct iroh_remote_info_t {
  uint32_t struct_size;
  struct iroh_bytes_t node_id;
  uint32_t is_connected;
  uint32_t connection_type;
  struct iroh_bytes_t relay_url;
  uint64_t last_handshake_ns;
  uint64_t bytes_sent;
  uint64_t bytes_received;
} iroh_remote_info_t;

typedef struct iroh_connection_info_t {
  uint32_t struct_size;
  uint32_t connection_type;
  uint64_t bytes_sent;
  uint64_t bytes_received;
  uint64_t rtt_ns;
  struct iroh_bytes_t alpn;
  uint32_t is_connected;
} iroh_connection_info_t;

typedef uint64_t iroh_hook_invocation_t;

/**
 * Transport-layer metrics snapshot from the iroh endpoint.
 */
typedef struct iroh_transport_metrics_t {
  uint32_t struct_size;
  uint64_t send_ipv4;
  uint64_t send_ipv6;
  uint64_t send_relay;
  uint64_t recv_data_ipv4;
  uint64_t recv_data_ipv6;
  uint64_t recv_data_relay;
  uint64_t recv_datagrams;
  uint64_t num_conns_direct;
  uint64_t num_conns_opened;
  uint64_t num_conns_closed;
  uint64_t paths_direct;
  uint64_t paths_relay;
  uint64_t holepunch_attempts;
  uint64_t relay_home_change;
  uint64_t net_reports;
  uint64_t net_reports_full;
} iroh_transport_metrics_t;

uint32_t iroh_abi_version_major(void);

uint32_t iroh_abi_version_minor(void);

uint32_t iroh_abi_version_patch(void);

int32_t iroh_runtime_new(const struct iroh_runtime_config_t *config, iroh_runtime_t *out_runtime);

int32_t iroh_runtime_close(iroh_runtime_t runtime);

int32_t iroh_secret_key_generate(uint8_t *out_key_ptr,
                                 uintptr_t out_key_capacity,
                                 uintptr_t *out_len);

uintptr_t iroh_poll_events(iroh_runtime_t runtime,
                           struct iroh_event_t *out_events,
                           uintptr_t max_events,
                           uint32_t timeout_ms);

int32_t iroh_buffer_release(iroh_runtime_t runtime, uint64_t buffer);

/**
 * Release a string allocated by `alloc_string`.
 * Java must call this to free strings returned via `iroh_bytes_t` fields
 * in structs that were allocated with Rust-owned memory (not caller-buffers).
 *
 * # Safety
 * - `ptr` must be a pointer returned by a Rust `alloc_string` call
 * - `len` must be the length passed back alongside `ptr`
 * - Must be called exactly once for each allocation
 * - `ptr` must not be null
 */
int32_t iroh_string_release(const uint8_t *ptr, uintptr_t len);

int32_t iroh_operation_cancel(iroh_runtime_t runtime, iroh_operation_t operation);

uintptr_t iroh_last_error_message(uint8_t *buffer, uintptr_t capacity);

const char *iroh_status_name(enum iroh_status_t status);

int32_t iroh_node_memory(iroh_runtime_t runtime,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

int32_t iroh_node_persistent(iroh_runtime_t runtime,
                             struct iroh_bytes_t path,
                             uint64_t user_data,
                             iroh_operation_t *out_operation);

int32_t iroh_node_close(iroh_runtime_t runtime,
                        iroh_node_t node,
                        uint64_t user_data,
                        iroh_operation_t *out_operation);

int32_t iroh_node_id(iroh_runtime_t runtime,
                     iroh_node_t node,
                     uint8_t *out_buf,
                     uintptr_t capacity,
                     uintptr_t *out_len);

int32_t iroh_node_addr_info(iroh_runtime_t runtime,
                            iroh_node_t node,
                            uint8_t *out_buf,
                            uintptr_t buf_capacity,
                            struct iroh_node_addr_t *out_addr);

int32_t iroh_node_export_secret_key(iroh_runtime_t runtime,
                                    iroh_node_t node,
                                    uint8_t *out_buf,
                                    uintptr_t capacity,
                                    uintptr_t *out_len);

int32_t iroh_endpoint_create(iroh_runtime_t runtime,
                             const struct iroh_endpoint_config_t *config,
                             uint64_t user_data,
                             iroh_operation_t *out_operation);

int32_t iroh_endpoint_close(iroh_runtime_t runtime,
                            iroh_endpoint_t endpoint,
                            uint64_t user_data,
                            iroh_operation_t *out_operation);

int32_t iroh_endpoint_id(iroh_runtime_t runtime,
                         iroh_endpoint_t endpoint,
                         uint8_t *out_buf,
                         uintptr_t capacity,
                         uintptr_t *out_len);

int32_t iroh_endpoint_export_secret_key(iroh_runtime_t runtime,
                                        iroh_endpoint_t endpoint,
                                        uint8_t *out_buf,
                                        uintptr_t capacity,
                                        uintptr_t *out_len);

int32_t iroh_endpoint_addr_info(iroh_runtime_t runtime,
                                iroh_endpoint_t endpoint,
                                uint8_t *out_buf,
                                uintptr_t buf_capacity,
                                struct iroh_node_addr_t *out_addr);

int32_t iroh_stream_stop(iroh_runtime_t runtime,
                         iroh_recv_stream_t recv_stream,
                         uint32_t error_code);

int32_t iroh_connect(iroh_runtime_t runtime,
                     uint64_t endpoint_or_node,
                     const struct iroh_connect_config_t *config,
                     uint64_t user_data,
                     iroh_operation_t *out_operation);

int32_t iroh_accept(iroh_runtime_t runtime,
                    uint64_t endpoint_or_node,
                    uint64_t user_data,
                    iroh_operation_t *out_operation);

/**
 * Create an in-memory node with blobs/docs/gossip + custom aster ALPNs.
 * Emits IROH_EVENT_NODE_CREATED on success.
 */
int32_t iroh_node_memory_with_alpns(iroh_runtime_t runtime,
                                    const uint8_t *const *alpns,
                                    const uintptr_t *alpn_lens,
                                    uintptr_t alpn_count,
                                    uint64_t user_data,
                                    iroh_operation_t *out_operation);

/**
 * Pull the next incoming aster-ALPN connection from the node's queue.
 * Long-poll: spawns a tokio task, emits IROH_EVENT_ASTER_ACCEPTED when a
 * connection arrives. event.handle = connection_handle, event.data_ptr/len
 * = ALPN bytes, event.buffer = lease to release via iroh_buffer_release.
 */
int32_t iroh_node_accept_aster(iroh_runtime_t runtime,
                               uint64_t node,
                               uint64_t user_data,
                               iroh_operation_t *out_operation);

int32_t iroh_connection_remote_id(iroh_runtime_t runtime,
                                  iroh_connection_t connection,
                                  uint8_t *out_buf,
                                  uintptr_t capacity,
                                  uintptr_t *out_len);

int32_t iroh_connection_close(iroh_runtime_t runtime,
                              iroh_connection_t connection,
                              uint32_t error_code,
                              struct iroh_bytes_t reason);

int32_t iroh_connection_closed(iroh_runtime_t runtime,
                               iroh_connection_t connection,
                               uint64_t user_data,
                               iroh_operation_t *out_operation);

int32_t iroh_connection_send_datagram(iroh_runtime_t runtime,
                                      iroh_connection_t connection,
                                      struct iroh_bytes_t data);

int32_t iroh_connection_read_datagram(iroh_runtime_t runtime,
                                      iroh_connection_t connection,
                                      uint64_t user_data,
                                      iroh_operation_t *out_operation);

int32_t iroh_open_bi(iroh_runtime_t runtime,
                     iroh_connection_t connection,
                     uint64_t user_data,
                     iroh_operation_t *out_operation);

int32_t iroh_accept_bi(iroh_runtime_t runtime,
                       iroh_connection_t connection,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

int32_t iroh_open_uni(iroh_runtime_t runtime,
                      iroh_connection_t connection,
                      uint64_t user_data,
                      iroh_operation_t *out_operation);

int32_t iroh_accept_uni(iroh_runtime_t runtime,
                        iroh_connection_t connection,
                        uint64_t user_data,
                        iroh_operation_t *out_operation);

int32_t iroh_stream_write(iroh_runtime_t runtime,
                          iroh_send_stream_t send_stream,
                          struct iroh_bytes_t data,
                          uint64_t user_data,
                          iroh_operation_t *out_operation);

int32_t iroh_stream_finish(iroh_runtime_t runtime,
                           iroh_send_stream_t send_stream,
                           uint64_t user_data,
                           iroh_operation_t *out_operation);

int32_t iroh_stream_read(iroh_runtime_t runtime,
                         iroh_recv_stream_t recv_stream,
                         uintptr_t max_len,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

int32_t iroh_stream_read_to_end(iroh_runtime_t runtime,
                                iroh_recv_stream_t recv_stream,
                                uintptr_t max_size,
                                uint64_t user_data,
                                iroh_operation_t *out_operation);

int32_t iroh_stream_read_exact(iroh_runtime_t runtime,
                               iroh_recv_stream_t recv_stream,
                               uintptr_t exact_len,
                               uint64_t user_data,
                               iroh_operation_t *out_operation);

int32_t iroh_stream_stopped(iroh_runtime_t runtime,
                            iroh_send_stream_t send_stream,
                            uint64_t user_data,
                            iroh_operation_t *out_operation);

int32_t iroh_add_node_addr(iroh_runtime_t runtime,
                           iroh_endpoint_t endpoint,
                           struct iroh_node_addr_t addr);

int32_t iroh_node_free(iroh_runtime_t runtime, iroh_node_t node);

int32_t iroh_endpoint_free(iroh_runtime_t runtime, iroh_endpoint_t endpoint);

int32_t iroh_connection_free(iroh_runtime_t runtime, iroh_connection_t connection);

int32_t iroh_send_stream_free(iroh_runtime_t runtime, iroh_send_stream_t stream);

int32_t iroh_recv_stream_free(iroh_runtime_t runtime, iroh_recv_stream_t stream);

int32_t iroh_doc_free(iroh_runtime_t runtime, uint64_t doc);

int32_t iroh_gossip_topic_free(iroh_runtime_t runtime, uint64_t topic);

int32_t iroh_blobs_add_bytes(iroh_runtime_t runtime,
                             iroh_node_t node,
                             struct iroh_bytes_t data,
                             uint64_t user_data,
                             iroh_operation_t *out_operation);

int32_t iroh_blobs_read(iroh_runtime_t runtime,
                        iroh_node_t node,
                        struct iroh_bytes_t hash_hex,
                        uint64_t user_data,
                        iroh_operation_t *out_operation);

/**
 * Store bytes as a single-file Collection (HashSeq), compatible with sendme.
 * Emits IROH_EVENT_BLOB_ADDED with the collection hash in the payload.
 */
int32_t iroh_blobs_add_bytes_as_collection(iroh_runtime_t runtime,
                                           iroh_node_t node,
                                           struct iroh_bytes_t name,
                                           struct iroh_bytes_t data,
                                           uint64_t user_data,
                                           iroh_operation_t *out_operation);

/**
 * Store a multi-file collection (HashSeq).
 *
 * `entries_json` is a UTF-8 JSON string: `[["name1","base64data1"],["name2","base64data2"]]`
 * Each entry's data is base64-encoded. The result (collection hash hex) is emitted as
 * `IROH_EVENT_BLOB_COLLECTION_ADDED` with the hash string in the event data buffer.
 */
int32_t iroh_blobs_add_collection(iroh_runtime_t runtime,
                                  iroh_node_t node,
                                  struct iroh_bytes_t entries_json,
                                  uint64_t user_data,
                                  iroh_operation_t *out_operation);

/**
 * List entries from a stored collection.
 *
 * `hash_hex` is the collection hash. The result is emitted as
 * `IROH_EVENT_BLOB_READ` with a JSON string:
 * `[["name1","hash_hex1",size1],["name2","hash_hex2",size2]]`
 */
int32_t iroh_blobs_list_collection(iroh_runtime_t runtime,
                                   iroh_node_t node,
                                   struct iroh_bytes_t hash_hex,
                                   uint64_t user_data,
                                   iroh_operation_t *out_operation);

/**
 * Create a ticket for a Collection (HashSeq format), compatible with sendme.
 * Writes the ticket string into the caller-provided buffer.
 */
int32_t iroh_blobs_create_collection_ticket(iroh_runtime_t runtime,
                                            iroh_node_t node,
                                            struct iroh_bytes_t hash_hex,
                                            uint8_t *out_buf,
                                            uintptr_t capacity,
                                            uintptr_t *out_len);

int32_t iroh_blobs_create_ticket(iroh_runtime_t runtime,
                                 iroh_node_t node,
                                 struct iroh_bytes_t hash_hex,
                                 uint8_t *out_buf,
                                 uintptr_t capacity,
                                 uintptr_t *out_len);

int32_t iroh_blobs_download(iroh_runtime_t runtime,
                            iroh_node_t node,
                            struct iroh_bytes_t ticket,
                            uint64_t user_data,
                            iroh_operation_t *out_operation);

/**
 * Check the status of a blob in the local store. Synchronous.
 *
 * Writes to `out_status`: 0 = not_found, 1 = partial, 2 = complete.
 * Writes to `out_size`: byte size (0 if not_found).
 */
int32_t iroh_blobs_status(iroh_runtime_t runtime,
                          iroh_node_t node,
                          const uint8_t *hash_hex_ptr,
                          uintptr_t hash_hex_len,
                          uint32_t *out_status,
                          uint64_t *out_size);

/**
 * Check if a blob is fully stored locally. Synchronous.
 *
 * Writes to `out_has`: 1 = complete/present, 0 = not complete.
 */
int32_t iroh_blobs_has(iroh_runtime_t runtime,
                       iroh_node_t node,
                       const uint8_t *hash_hex_ptr,
                       uintptr_t hash_hex_len,
                       uint32_t *out_has);

/**
 * Snapshot of the current bitfield for a blob.
 * Fills `out_is_complete` (1=complete, 0=partial/not-found) and `out_size` (total bytes, 0 if unknown).
 * Returns IROH_STATUS_NOT_FOUND if the node handle is unknown.
 * Returns IROH_STATUS_INVALID_ARGUMENT if any pointer is null.
 */
int32_t iroh_blobs_observe_snapshot(iroh_runtime_t runtime,
                                    iroh_node_t node,
                                    const uint8_t *hash_hex_ptr,
                                    uintptr_t hash_hex_len,
                                    uint32_t *out_is_complete,
                                    uint64_t *out_size);

/**
 * Wait until a blob is fully downloaded locally.
 * Emits IROH_EVENT_BLOB_OBSERVE_COMPLETE (via IROH_EVENT_UNIT_RESULT) when complete,
 * or an error event if the observation stream ends without completion.
 */
int32_t iroh_blobs_observe_complete(iroh_runtime_t runtime,
                                    iroh_node_t node,
                                    const uint8_t *hash_hex_ptr,
                                    uintptr_t hash_hex_len,
                                    uint64_t user_data,
                                    iroh_operation_t *out_operation);

/**
 * Check local availability of a blob using the Remote API.
 * Fills `out_is_complete` (1=complete, 0=partial) and `out_local_bytes` (bytes we have locally).
 * Returns IROH_STATUS_NOT_FOUND if the node handle is unknown.
 * Returns IROH_STATUS_INVALID_ARGUMENT if any pointer is null.
 */
int32_t iroh_blobs_local_info(iroh_runtime_t runtime,
                              iroh_node_t node,
                              const uint8_t *hash_hex_ptr,
                              uintptr_t hash_hex_len,
                              uint32_t *out_is_complete,
                              uint64_t *out_local_bytes);

/**
 * Set a named tag. format: 0 = raw, 1 = hash_seq. Emits IROH_EVENT_TAG_SET.
 */
int32_t iroh_tags_set(iroh_runtime_t runtime,
                      iroh_node_t node,
                      const uint8_t *name_ptr,
                      uintptr_t name_len,
                      const uint8_t *hash_hex_ptr,
                      uintptr_t hash_hex_len,
                      uint32_t format,
                      uint64_t user_data,
                      iroh_operation_t *out_operation);

/**
 * Get a tag by name. Emits IROH_EVENT_TAG_GET with payload on found, NOT_FOUND status if absent.
 */
int32_t iroh_tags_get(iroh_runtime_t runtime,
                      iroh_node_t node,
                      const uint8_t *name_ptr,
                      uintptr_t name_len,
                      uint64_t user_data,
                      iroh_operation_t *out_operation);

/**
 * Delete a tag by name. Emits IROH_EVENT_TAG_DELETED with count in event.flags.
 */
int32_t iroh_tags_delete(iroh_runtime_t runtime,
                         iroh_node_t node,
                         const uint8_t *name_ptr,
                         uintptr_t name_len,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

/**
 * List tags matching a prefix (empty prefix = all tags).
 * Emits IROH_EVENT_TAG_LIST with packed tag records in payload; event.flags = count.
 */
int32_t iroh_tags_list_prefix(iroh_runtime_t runtime,
                              iroh_node_t node,
                              const uint8_t *prefix_ptr,
                              uintptr_t prefix_len,
                              uint64_t user_data,
                              iroh_operation_t *out_operation);

int32_t iroh_docs_create(iroh_runtime_t runtime,
                         iroh_node_t node,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

int32_t iroh_docs_create_author(iroh_runtime_t runtime,
                                iroh_node_t node,
                                uint64_t user_data,
                                iroh_operation_t *out_operation);

int32_t iroh_docs_join(iroh_runtime_t runtime,
                       iroh_node_t node,
                       struct iroh_bytes_t ticket,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

int32_t iroh_doc_set_bytes(iroh_runtime_t runtime,
                           uint64_t doc,
                           struct iroh_bytes_t author_hex,
                           struct iroh_bytes_t key,
                           struct iroh_bytes_t value,
                           uint64_t user_data,
                           iroh_operation_t *out_operation);

int32_t iroh_doc_get_exact(iroh_runtime_t runtime,
                           uint64_t doc,
                           struct iroh_bytes_t author_hex,
                           struct iroh_bytes_t key,
                           uint64_t user_data,
                           iroh_operation_t *out_operation);

int32_t iroh_doc_share(iroh_runtime_t runtime,
                       uint64_t doc,
                       uint32_t mode,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

int32_t iroh_doc_query(iroh_runtime_t runtime,
                       uint64_t doc,
                       uint32_t mode,
                       struct iroh_bytes_t key,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

/**
 * Read the content bytes for a doc entry given its content hash.
 */
int32_t iroh_doc_read_entry_content(iroh_runtime_t runtime,
                                    uint64_t doc,
                                    struct iroh_bytes_t content_hash_hex,
                                    uint64_t user_data,
                                    iroh_operation_t *out_operation);

/**
 * Start syncing a document with the specified peers (endpoint-ID hex strings).
 * Emits IROH_EVENT_UNIT_RESULT on completion.
 */
int32_t iroh_doc_start_sync(iroh_runtime_t runtime,
                            uint64_t doc,
                            struct iroh_bytes_list_t peers,
                            uint64_t user_data,
                            iroh_operation_t *out_operation);

/**
 * Leave (stop syncing) a document.
 * Emits IROH_EVENT_UNIT_RESULT on completion.
 */
int32_t iroh_doc_leave(iroh_runtime_t runtime,
                       uint64_t doc,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

/**
 * Subscribe to live document events.
 * Emits IROH_EVENT_DOC_SUBSCRIBED (status=OK, handle=receiver_handle) on success.
 */
int32_t iroh_doc_subscribe(iroh_runtime_t runtime,
                           uint64_t doc,
                           uint64_t user_data,
                           iroh_operation_t *out_operation);

/**
 * Receive the next live document event (long-poll, like gossip_recv).
 * Emits IROH_EVENT_DOC_EVENT with event.subtype indicating the event kind and
 * packed data in the payload.  When the subscription ends, emits with status=NOT_FOUND.
 */
int32_t iroh_doc_event_recv(iroh_runtime_t runtime,
                            uint64_t receiver,
                            uint64_t user_data,
                            iroh_operation_t *out_operation);

/**
 * Set the download policy for a document.
 * prefixes: list of byte-string prefixes (used for NOTHING_EXCEPT / EVERYTHING_EXCEPT modes).
 * Emits IROH_EVENT_UNIT_RESULT on success.
 */
int32_t iroh_doc_set_download_policy(iroh_runtime_t runtime,
                                     uint64_t doc,
                                     uint32_t mode,
                                     struct iroh_bytes_list_t prefixes,
                                     uint64_t user_data,
                                     iroh_operation_t *out_operation);

/**
 * Share a document with full relay+address info (AddrInfoOptions::RelayAndAddresses).
 * mode: 0 = read, 1 = write.
 * Emits IROH_EVENT_DOC_SHARED with the ticket string in the payload.
 */
int32_t iroh_doc_share_with_addr(iroh_runtime_t runtime,
                                 uint64_t doc,
                                 uint32_t mode,
                                 uint64_t user_data,
                                 iroh_operation_t *out_operation);

/**
 * Join a document and subscribe to live events atomically.
 * Emits IROH_EVENT_DOC_JOINED_AND_SUBSCRIBED:
 *   event.handle = doc handle
 *   event.flags  = event-receiver handle
 */
int32_t iroh_docs_join_and_subscribe(iroh_runtime_t runtime,
                                     iroh_node_t node,
                                     struct iroh_bytes_t ticket,
                                     uint64_t user_data,
                                     iroh_operation_t *out_operation);

int32_t iroh_gossip_subscribe(iroh_runtime_t runtime,
                              iroh_node_t node,
                              struct iroh_bytes_t topic,
                              struct iroh_bytes_list_t peers,
                              uint64_t user_data,
                              iroh_operation_t *out_operation);

int32_t iroh_gossip_broadcast(iroh_runtime_t runtime,
                              uint64_t topic,
                              struct iroh_bytes_t data,
                              uint64_t user_data,
                              iroh_operation_t *out_operation);

int32_t iroh_gossip_recv(iroh_runtime_t runtime,
                         uint64_t topic,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

int32_t iroh_connection_max_datagram_size(iroh_runtime_t runtime,
                                          iroh_connection_t connection,
                                          uint64_t *out_size,
                                          uint32_t *out_is_some);

int32_t iroh_connection_datagram_send_buffer_space(iroh_runtime_t runtime,
                                                   iroh_connection_t connection,
                                                   uint64_t *out_bytes);

int32_t iroh_endpoint_remote_info(iroh_runtime_t runtime,
                                  uint64_t endpoint_or_node,
                                  struct iroh_bytes_t node_id,
                                  struct iroh_remote_info_t *out_info);

int32_t iroh_endpoint_remote_info_list(iroh_runtime_t runtime,
                                       uint64_t endpoint_or_node,
                                       struct iroh_remote_info_t *out_infos,
                                       uintptr_t max_infos,
                                       uintptr_t *out_count);

int32_t iroh_connection_info(iroh_runtime_t runtime,
                             iroh_connection_t connection,
                             struct iroh_connection_info_t *out_info);

/**
 * Respond to a pending before_connect hook invocation.
 *
 * `decision` is IROH_HOOK_DECISION_ALLOW (0) or IROH_HOOK_DECISION_DENY (1).
 * Calling this consumes the invocation; a second call returns NOT_FOUND.
 */
int32_t iroh_hook_before_connect_respond(iroh_runtime_t runtime,
                                         iroh_hook_invocation_t invocation,
                                         enum iroh_hook_decision_t decision);

/**
 * Respond to a pending after_connect hook invocation (always accepts).
 *
 * Calling this consumes the invocation; a second call returns NOT_FOUND.
 */
int32_t iroh_hook_after_connect_respond(iroh_runtime_t runtime, iroh_hook_invocation_t invocation);

/**
 * Snapshot current transport metrics from the iroh endpoint.
 *
 * `endpoint_or_node` may be either an endpoint handle or a node handle.
 * Writes the metrics into `out_metrics`.
 */
int32_t iroh_endpoint_transport_metrics(iroh_runtime_t runtime,
                                        uint64_t endpoint_or_node,
                                        struct iroh_transport_metrics_t *out_metrics);

/**
 * Compute contract_id from a ServiceContract JSON string.
 * Writes 64-byte hex string (no null terminator) to out_buf.
 * On BUFFER_TOO_SMALL, sets `*out_len` to required size.
 */
int32_t aster_contract_id(const uint8_t *json_ptr,
                          uintptr_t json_len,
                          uint8_t *out_buf,
                          uintptr_t *out_len);

/**
 * Compute canonical bytes for a named type from JSON.
 * `type_name`: `"ServiceContract"`, `"TypeDef"`, or `"MethodDef"`.
 */
int32_t aster_canonical_bytes(const uint8_t *type_name_ptr,
                              uintptr_t type_name_len,
                              const uint8_t *json_ptr,
                              uintptr_t json_len,
                              uint8_t *out_buf,
                              uintptr_t *out_len);

/**
 * Encode a frame: `[4-byte LE length][flags][payload]`.
 */
int32_t aster_frame_encode(const uint8_t *payload_ptr,
                           uintptr_t payload_len,
                           uint8_t flags,
                           uint8_t *out_buf,
                           uintptr_t *out_len);

/**
 * Decode a frame. Writes payload to `out_payload`, flags byte to `*out_flags`.
 *
 * `*out_payload_len` must be set to the capacity of `out_payload` on entry.
 * On success it is set to the actual payload length.
 * On BUFFER_TOO_SMALL it is set to the required payload size.
 */
int32_t aster_frame_decode(const uint8_t *data_ptr,
                           uintptr_t data_len,
                           uint8_t *out_payload,
                           uintptr_t *out_payload_len,
                           uint8_t *out_flags);

/**
 * Compute canonical signing bytes from credential JSON.
 *
 * The JSON must contain a `"kind"` field (`"producer"` or `"consumer"`)
 * to dispatch to the correct signing bytes format.
 */
int32_t aster_signing_bytes(const uint8_t *json_ptr,
                            uintptr_t json_len,
                            uint8_t *out_buf,
                            uintptr_t *out_len);

/**
 * Canonical JSON normalization: parse, sort all keys recursively, re-serialize compact.
 *
 * This is a general-purpose canonical form — not specific to credentials or contracts.
 * Useful for computing deterministic hashes of arbitrary JSON payloads.
 */
int32_t aster_canonical_json(const uint8_t *json_ptr,
                             uintptr_t json_len,
                             uint8_t *out_buf,
                             uintptr_t *out_len);

/**
 * Encode an AsterTicket to a base58 string (``aster1<base58>``).
 *
 * # Parameters
 * - `endpoint_id_hex`: 64-char hex endpoint ID
 * - `relay_addr_ptr/len`: relay "ip:port" string (NULL/0 for none)
 * - `direct_addrs_json_ptr/len`: JSON array of "ip:port" strings (NULL/0 for none)
 * - `credential_type_ptr/len`: credential type string: "open", "consumer_rcan",
 *   "enrollment", "registry_read" (NULL/0 for none)
 * - `credential_data_ptr/len`: credential payload bytes (NULL/0 for none)
 * - `out_buf/out_len`: output buffer for the aster1... string
 */
int32_t aster_ticket_encode(const uint8_t *endpoint_id_hex_ptr,
                            uintptr_t endpoint_id_hex_len,
                            const uint8_t *relay_addr_ptr,
                            uintptr_t relay_addr_len,
                            const uint8_t *direct_addrs_json_ptr,
                            uintptr_t direct_addrs_json_len,
                            const uint8_t *credential_type_ptr,
                            uintptr_t credential_type_len,
                            const uint8_t *credential_data_ptr,
                            uintptr_t credential_data_len,
                            uint8_t *out_buf,
                            uintptr_t *out_len);

/**
 * Decode an AsterTicket from a base58 string (``aster1<base58>``).
 *
 * Writes a JSON object to `out_buf`:
 * ```json
 * {
 *   "endpoint_id": "hex...",
 *   "relay_addr": "ip:port" | null,
 *   "direct_addrs": ["ip:port", ...],
 *   "credential_type": "open" | "consumer_rcan" | "enrollment" | "registry_read" | null,
 *   "credential_data_hex": "hex..." | null
 * }
 * ```
 */
int32_t aster_ticket_decode(const uint8_t *ticket_ptr,
                            uintptr_t ticket_len,
                            uint8_t *out_buf,
                            uintptr_t *out_len);
