// @ts-nocheck
// AUTOGENERATED by @aster-rpc/aster — do not edit.
// Regenerate with: npx aster-gen

import { RpcPattern } from '@aster-rpc/aster';
import { Entry as T0_Entry, TreeRequest as T1_TreeRequest, TreeResponse as T2_TreeResponse } from './src/types.js';
import { TreeServiceImpl as T3_TreeServiceImpl } from './src/service.js';

export const WIRE_TYPES = [
  {
    ctor: T0_Entry,
    tag: "tree/Entry",
    fields: [
    { name: "name", kind: 'primitive', wire: "string", nullable: false },
    { name: "children", kind: 'list', element: { name: "children[]", kind: 'ref', refTag: "tree/Entry", nullable: false }, nullable: false },
    ],
    fieldNameSet: new Set(["name", "children"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([["children", T0_Entry]]),
  },
  {
    ctor: T1_TreeRequest,
    tag: "tree/TreeRequest",
    fields: [
    { name: "root", kind: 'ref', refTag: "tree/Entry", nullable: false },
    ],
    fieldNameSet: new Set(["root"]),
    nestedTypes: new Map([["root", T0_Entry]]),
    elementTypes: new Map([]),
  },
  {
    ctor: T2_TreeResponse,
    tag: "tree/TreeResponse",
    fields: [
    { name: "tree", kind: 'ref', refTag: "tree/Entry", nullable: false },
    ],
    fieldNameSet: new Set(["tree"]),
    nestedTypes: new Map([["tree", T0_Entry]]),
    elementTypes: new Map([]),
  },
] as const;

/**
 * Build and register all @WireType classes with Fory, using Type.struct()
 * to describe each struct's fields with explicit wire types.
 *
 * Iterates over WIRE_TYPES so that entry.ctor is the actual class ref.
 * For 'ref' fields, looks up the target type from typesByTag by refTag.
 * Types are registered in topological order (leaves first), so all
 * dependencies are available when any given type is being registered.
 *
 * @returns Map<tag, typeStruct> — each registered Fory type struct, keyed
 *   by wire tag (e.g. "sample/StatusRequest"). Callers can use this to
 *   look up any type after registration.
 */
export function BUILD_ALL_TYPES(
  fory: any,
  Type: any,
  codec: { registerType(typeInfo: any): void },
): Map<string, any> {
  const typesByTag = new Map();
  for (const entry of WIRE_TYPES) {
  // tree/Entry
  {
    const [ns, typeName] = "tree/Entry".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "name": Type.string(),
      "children": Type.array(typesByTag.get("tree/Entry"))
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("tree/Entry", typeStruct);
  }
  // tree/TreeRequest
  {
    const [ns, typeName] = "tree/TreeRequest".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "root": typesByTag.get("tree/Entry")
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("tree/TreeRequest", typeStruct);
  }
  // tree/TreeResponse
  {
    const [ns, typeName] = "tree/TreeResponse".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "tree": typesByTag.get("tree/Entry")
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("tree/TreeResponse", typeStruct);
  }
  }
  return typesByTag;
}


export const SERVICES = [
  {
    ctor: T3_TreeServiceImpl,
    name: "TreeService",
    version: 1,
    scoped: "shared",
    serializationModes: [],
    requires: undefined,
    metadata: undefined,
    methods: [
    {
      name: "fetchTree",
      pattern: RpcPattern.UNARY,
      requestType: T1_TreeRequest,
      responseType: T2_TreeResponse,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"root","type":"dict","required":true,"default":{}}],
      responseFields: [{"name":"tree","type":"dict","required":true,"default":{}}],
      requestTypeHash: new Uint8Array([0xa0, 0x1a, 0x00, 0x99, 0x7b, 0x00, 0x90, 0xa8, 0xfd, 0xe4, 0xd3, 0x3d, 0x20, 0x89, 0x3e, 0x90, 0x53, 0x36, 0x74, 0x0e, 0x91, 0x17, 0xec, 0x81, 0xcd, 0x22, 0xa7, 0x58, 0xab, 0xb3, 0x4b, 0x60]),
      responseTypeHash: new Uint8Array([0x54, 0x72, 0x57, 0x1e, 0x4a, 0xc6, 0x2f, 0x31, 0x80, 0xfb, 0x1e, 0x9c, 0x56, 0x4c, 0x32, 0x44, 0xc9, 0x29, 0x3f, 0xe7, 0x22, 0x50, 0x9c, 0x26, 0x68, 0x77, 0xc8, 0x39, 0xbe, 0xa1, 0x82, 0x94]),
    },
    ],
  },
] as const;
