// @ts-nocheck
// AUTOGENERATED by @aster-rpc/aster — do not edit.
// Regenerate with: npx aster-gen

import { RpcPattern } from '@aster-rpc/aster';
import { Entry as T0_Entry, TreeRequest as T1_TreeRequest, TreeResponse as T2_TreeResponse } from './src/types.js';
import { TreeServiceImpl as T3_TreeServiceImpl } from './src/service.js';

export const WIRE_TYPES = [
  {
    ctor: T0_Entry,
    tag: "tree/Entry",
    fields: [
    { name: "name", kind: 'primitive', wire: "string", nullable: false },
    { name: "children", kind: 'list', element: { name: "children[]", kind: 'ref', refTag: "tree/Entry", nullable: false }, nullable: false },
    ],
    fieldNameSet: new Set(["name", "children"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([["children", T0_Entry]]),
    typeHashHex: "997ca7312bd51ae09cd820ca96f43816002f320856d3e4e9e4c8e18c9d7adcab",
    typeDefBytes: new Uint8Array([0x00, 0x12, 0x74, 0x72, 0x65, 0x65, 0x16, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x02, 0x0c, 0x02, 0x22, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x02, 0x02, 0x00, 0x2a, 0x74, 0x72, 0x65, 0x65, 0x2f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x00, 0x00, 0x01, 0x00, 0x02, 0x00, 0x01, 0x00, 0x04, 0x12, 0x6e, 0x61, 0x6d, 0x65, 0x00, 0x1a, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x00, 0x00, 0x0c, 0x00, 0x0c]),
  },
  {
    ctor: T1_TreeRequest,
    tag: "tree/TreeRequest",
    fields: [
    { name: "root", kind: 'ref', refTag: "tree/Entry", nullable: false },
    ],
    fieldNameSet: new Set(["root"]),
    nestedTypes: new Map([["root", T0_Entry]]),
    elementTypes: new Map([]),
    typeHashHex: "a01a00997b0090a8fde4d33d20893e905336740e9117ec81cd22a758abb34b60",
    typeDefBytes: new Uint8Array([0x00, 0x12, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x01, 0x0c, 0x02, 0x12, 0x72, 0x6f, 0x6f, 0x74, 0x01, 0x02, 0x20, 0x99, 0x7c, 0xa7, 0x31, 0x2b, 0xd5, 0x1a, 0xe0, 0x9c, 0xd8, 0x20, 0xca, 0x96, 0xf4, 0x38, 0x16, 0x00, 0x2f, 0x32, 0x08, 0x56, 0xd3, 0xe4, 0xe9, 0xe4, 0xc8, 0xe1, 0x8c, 0x9d, 0x7a, 0xdc, 0xab, 0x02, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x00, 0x00, 0x0c, 0x00, 0x0c]),
  },
  {
    ctor: T2_TreeResponse,
    tag: "tree/TreeResponse",
    fields: [
    { name: "tree", kind: 'ref', refTag: "tree/Entry", nullable: false },
    ],
    fieldNameSet: new Set(["tree"]),
    nestedTypes: new Map([["tree", T0_Entry]]),
    elementTypes: new Map([]),
    typeHashHex: "5472571e4ac62f3180fb1e9c564c3244c9293fe722509c266877c839bea18294",
    typeDefBytes: new Uint8Array([0x00, 0x12, 0x74, 0x72, 0x65, 0x65, 0x32, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x01, 0x0c, 0x02, 0x12, 0x74, 0x72, 0x65, 0x65, 0x01, 0x02, 0x20, 0x99, 0x7c, 0xa7, 0x31, 0x2b, 0xd5, 0x1a, 0xe0, 0x9c, 0xd8, 0x20, 0xca, 0x96, 0xf4, 0x38, 0x16, 0x00, 0x2f, 0x32, 0x08, 0x56, 0xd3, 0xe4, 0xe9, 0xe4, 0xc8, 0xe1, 0x8c, 0x9d, 0x7a, 0xdc, 0xab, 0x02, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x00, 0x00, 0x0c, 0x00, 0x0c]),
  },
] as const;

/**
 * Build and register all @WireType classes with Fory, using Type.struct()
 * to describe each struct's fields with explicit wire types.
 *
 * Each block references its class by aliased import name directly. For
 * 'ref' fields, looks up the target type from typesByTag by refTag.
 * Types are registered in topological order (leaves first), so all
 * dependencies are available when any given type is being registered.
 *
 * @returns Map<tag, typeStruct> — each registered Fory type struct, keyed
 *   by wire tag (e.g. "sample/StatusRequest"). Callers can use this to
 *   look up any type after registration.
 */
export function BUILD_ALL_TYPES(
  fory: any,
  Type: any,
  codec: { registerType(typeInfo: any): void },
): Map<string, any> {
  const typesByTag = new Map();
  // tree/Entry
  {
    const typeStruct = Type.struct(
      { namespace: "tree", typeName: "Entry" },
      {
      "name": Type.string(),
      "children": Type.array(typesByTag.get("tree/Entry"))
      },
      { withConstructor: true },
    );
    // initMeta can only be called once per class (sets non-configurable
    // property on the prototype). Skip if already initialized.
    const proto = T0_Entry.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(T0_Entry);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("tree/Entry", typeStruct);
  }
  // tree/TreeRequest
  {
    const typeStruct = Type.struct(
      { namespace: "tree", typeName: "TreeRequest" },
      {
      "root": typesByTag.get("tree/Entry")
      },
      { withConstructor: true },
    );
    // initMeta can only be called once per class (sets non-configurable
    // property on the prototype). Skip if already initialized.
    const proto = T1_TreeRequest.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(T1_TreeRequest);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("tree/TreeRequest", typeStruct);
  }
  // tree/TreeResponse
  {
    const typeStruct = Type.struct(
      { namespace: "tree", typeName: "TreeResponse" },
      {
      "tree": typesByTag.get("tree/Entry")
      },
      { withConstructor: true },
    );
    // initMeta can only be called once per class (sets non-configurable
    // property on the prototype). Skip if already initialized.
    const proto = T2_TreeResponse.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(T2_TreeResponse);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("tree/TreeResponse", typeStruct);
  }
  return typesByTag;
}


export const SERVICES = [
  {
    ctor: T3_TreeServiceImpl,
    name: "TreeService",
    version: 1,
    scoped: "shared",
    serializationModes: [],
    requires: undefined,
    metadata: undefined,
    methods: [
    {
      name: "fetchTree",
      pattern: RpcPattern.UNARY,
      requestType: T1_TreeRequest,
      responseType: T2_TreeResponse,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"root","type":"dict","required":true,"default":{}}],
      responseFields: [{"name":"tree","type":"dict","required":true,"default":{}}],
      requestTypeHash: new Uint8Array([0xa0, 0x1a, 0x00, 0x99, 0x7b, 0x00, 0x90, 0xa8, 0xfd, 0xe4, 0xd3, 0x3d, 0x20, 0x89, 0x3e, 0x90, 0x53, 0x36, 0x74, 0x0e, 0x91, 0x17, 0xec, 0x81, 0xcd, 0x22, 0xa7, 0x58, 0xab, 0xb3, 0x4b, 0x60]),
      responseTypeHash: new Uint8Array([0x54, 0x72, 0x57, 0x1e, 0x4a, 0xc6, 0x2f, 0x31, 0x80, 0xfb, 0x1e, 0x9c, 0x56, 0x4c, 0x32, 0x44, 0xc9, 0x29, 0x3f, 0xe7, 0x22, 0x50, 0x9c, 0x26, 0x68, 0x77, 0xc8, 0x39, 0xbe, 0xa1, 0x82, 0x94]),
    },
    ],
  },
] as const;
