// @ts-nocheck
// AUTOGENERATED by @aster-rpc/aster — do not edit.
// Regenerate with: bunx aster-gen

import { RpcPattern } from '@aster-rpc/aster';
import { Entry as T0_Entry, TreeRequest as T1_TreeRequest, TreeResponse as T2_TreeResponse } from './src/types.js';
import { TreeServiceImpl as T3_TreeServiceImpl } from './src/service.js';

export const WIRE_TYPES = [
  {
    ctor: T0_Entry,
    tag: "tree/Entry",
    fields: [
    { name: "name", kind: 'primitive', wire: "string", nullable: false },
    { name: "children", kind: 'list', element: { name: "children[]", kind: 'ref', refTag: "tree/Entry", nullable: false }, nullable: false },
    ],
    fieldNameSet: new Set(["name", "children"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([["children", T0_Entry]]),
    // foryTypeInfo is intentionally null: the current Fory JS API
    // requires user code to build a typeInfo with a `buildTypeInfo`
    // callback (see `ForyCodec.registerTypeGraph`). The scanner
    // doesn't know Fory's internal shape. Follow-up: once the Fory
    // JS binding exposes a declarative schema form, the scanner can
    // emit it here and `registerGenerated` will feed it to Fory
    // directly — no user callback needed.
    foryTypeInfo: null,
  },
  {
    ctor: T1_TreeRequest,
    tag: "tree/TreeRequest",
    fields: [
    { name: "root", kind: 'ref', refTag: "tree/Entry", nullable: false },
    ],
    fieldNameSet: new Set(["root"]),
    nestedTypes: new Map([["root", T0_Entry]]),
    elementTypes: new Map([]),
    // foryTypeInfo is intentionally null: the current Fory JS API
    // requires user code to build a typeInfo with a `buildTypeInfo`
    // callback (see `ForyCodec.registerTypeGraph`). The scanner
    // doesn't know Fory's internal shape. Follow-up: once the Fory
    // JS binding exposes a declarative schema form, the scanner can
    // emit it here and `registerGenerated` will feed it to Fory
    // directly — no user callback needed.
    foryTypeInfo: null,
  },
  {
    ctor: T2_TreeResponse,
    tag: "tree/TreeResponse",
    fields: [
    { name: "tree", kind: 'ref', refTag: "tree/Entry", nullable: false },
    ],
    fieldNameSet: new Set(["tree"]),
    nestedTypes: new Map([["tree", T0_Entry]]),
    elementTypes: new Map([]),
    // foryTypeInfo is intentionally null: the current Fory JS API
    // requires user code to build a typeInfo with a `buildTypeInfo`
    // callback (see `ForyCodec.registerTypeGraph`). The scanner
    // doesn't know Fory's internal shape. Follow-up: once the Fory
    // JS binding exposes a declarative schema form, the scanner can
    // emit it here and `registerGenerated` will feed it to Fory
    // directly — no user callback needed.
    foryTypeInfo: null,
  },
] as const;

export const SERVICES = [
  {
    ctor: T3_TreeServiceImpl,
    name: "TreeService",
    version: 1,
    scoped: "shared",
    serializationModes: [],
    requires: undefined,
    metadata: undefined,
    methods: [
    {
      name: "fetchTree",
      pattern: RpcPattern.UNARY,
      requestType: T1_TreeRequest,
      responseType: T2_TreeResponse,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"root","type":"dict","required":true,"default":{}}],
      responseFields: [{"name":"tree","type":"dict","required":true,"default":{}}],
      requestTypeHash: new Uint8Array([0xa0, 0x1a, 0x00, 0x99, 0x7b, 0x00, 0x90, 0xa8, 0xfd, 0xe4, 0xd3, 0x3d, 0x20, 0x89, 0x3e, 0x90, 0x53, 0x36, 0x74, 0x0e, 0x91, 0x17, 0xec, 0x81, 0xcd, 0x22, 0xa7, 0x58, 0xab, 0xb3, 0x4b, 0x60]),
      responseTypeHash: new Uint8Array([0x54, 0x72, 0x57, 0x1e, 0x4a, 0xc6, 0x2f, 0x31, 0x80, 0xfb, 0x1e, 0x9c, 0x56, 0x4c, 0x32, 0x44, 0xc9, 0x29, 0x3f, 0xe7, 0x22, 0x50, 0x9c, 0x26, 0x68, 0x77, 0xc8, 0x39, 0xbe, 0xa1, 0x82, 0x94]),
    },
    ],
  },
] as const;
