"""Type stubs for iroh_python package."""

from typing import Any, Coroutine, Optional


class IrohError(Exception): ...

__version__: str
__all__: list[str]


class NodeAddr:
    endpoint_id: str
    relay_url: Optional[str]
    direct_addresses: list[str]

    def __init__(
        self,
        endpoint_id: str,
        relay_url: Optional[str] = ...,
        direct_addresses: Optional[list[str]] = ...,
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> "NodeAddr": ...
    @staticmethod
    def from_dict(data: dict[str, Any]) -> "NodeAddr": ...


class EndpointConfig:
    relay_mode: Optional[str]
    alpns: list[bytes]
    secret_key: Optional[bytes]

    def __init__(
        self,
        alpns: list[bytes],
        relay_mode: Optional[str] = ...,
        secret_key: Optional[bytes] = ...,
    ) -> None: ...


class IrohNode:
    @staticmethod
    def memory() -> Coroutine[Any, Any, "IrohNode"]: ...
    @staticmethod
    def persistent(path: str) -> Coroutine[Any, Any, "IrohNode"]: ...
    def node_id(self) -> str: ...
    def node_addr(self) -> str: ...
    def node_addr_info(self) -> NodeAddr: ...
    def close(self) -> Coroutine[Any, Any, None]: ...
    def shutdown(self) -> Coroutine[Any, Any, None]: ...
    def add_node_addr(self, other: "IrohNode") -> None: ...


class BlobsClient: ...
def blobs_client(node: IrohNode) -> BlobsClient: ...


class DocsClient: ...
class DocHandle: ...
def docs_client(node: IrohNode) -> DocsClient: ...


class GossipClient: ...
class GossipTopicHandle: ...
def gossip_client(node: IrohNode) -> GossipClient: ...


class NetClient:
    def connect(self, node_id: str, alpn: bytes) -> Coroutine[Any, Any, "IrohConnection"]: ...
    def connect_node_addr(
        self, addr: NodeAddr, alpn: bytes
    ) -> Coroutine[Any, Any, "IrohConnection"]: ...
    def accept(self) -> Coroutine[Any, Any, "IrohConnection"]: ...
    def endpoint_id(self) -> str: ...
    def endpoint_addr(self) -> str: ...
    def endpoint_addr_info(self) -> NodeAddr: ...
    def close(self) -> Coroutine[Any, Any, None]: ...
    def closed(self) -> Coroutine[Any, Any, None]: ...


class IrohConnection:
    def open_bi(self) -> Coroutine[Any, Any, tuple["IrohSendStream", "IrohRecvStream"]]: ...
    def accept_bi(self) -> Coroutine[Any, Any, tuple["IrohSendStream", "IrohRecvStream"]]: ...
    def open_uni(self) -> Coroutine[Any, Any, "IrohSendStream"]: ...
    def accept_uni(self) -> Coroutine[Any, Any, "IrohRecvStream"]: ...
    def send_datagram(self, data: bytes) -> None: ...
    def read_datagram(self) -> Coroutine[Any, Any, bytes]: ...
    def remote_id(self) -> str: ...
    def close(self, code: int, reason: bytes) -> None: ...
    def closed(self) -> Coroutine[Any, Any, dict[str, Any]]: ...


class IrohSendStream:
    def write_all(self, data: bytes) -> Coroutine[Any, Any, None]: ...
    def finish(self) -> Coroutine[Any, Any, None]: ...
    def stopped(self) -> Coroutine[Any, Any, Optional[int]]: ...


class IrohRecvStream:
    def read(self, max_len: int) -> Coroutine[Any, Any, Optional[bytes]]: ...
    def read_exact(self, n: int) -> Coroutine[Any, Any, bytes]: ...
    def read_to_end(self, max_size: int) -> Coroutine[Any, Any, bytes]: ...
    def stop(self, code: int) -> None: ...


def net_client(node: IrohNode) -> NetClient: ...
def create_endpoint(alpn: bytes) -> Coroutine[Any, Any, NetClient]: ...
def create_endpoint_with_config(config: EndpointConfig) -> Coroutine[Any, Any, NetClient]: ...