//go:build cgo

package aster

// IrohStatus constants — mirrors iroh_status_t in iroh_ffi.h
const (
	IROH_STATUS_OK                 = 0
	IROH_STATUS_INVALID_ARGUMENT   = 1
	IROH_STATUS_NOT_FOUND          = 2
	IROH_STATUS_ALREADY_CLOSED     = 3
	IROH_STATUS_QUEUE_FULL         = 4
	IROH_STATUS_BUFFER_TOO_SMALL   = 5
	IROH_STATUS_UNSUPPORTED        = 6
	IROH_STATUS_INTERNAL           = 7
	IROH_STATUS_TIMEOUT            = 8
	IROH_STATUS_CANCELLED          = 9
	IROH_STATUS_CONNECTION_REFUSED = 10
	IROH_STATUS_STREAM_RESET       = 11
)

// IrohEventKind constants — mirrors iroh_event_kind_t in iroh_ffi.h
const (
	IROH_EVENT_NONE                   = 0
	IROH_EVENT_NODE_CREATED           = 1
	IROH_EVENT_NODE_CREATE_FAILED     = 2
	IROH_EVENT_ENDPOINT_CREATED       = 3
	IROH_EVENT_ENDPOINT_CREATE_FAILED = 4
	IROH_EVENT_CLOSED                 = 5
	IROH_EVENT_CONNECTED              = 10
	IROH_EVENT_CONNECT_FAILED         = 11
	IROH_EVENT_CONNECTION_ACCEPTED    = 12
	IROH_EVENT_CONNECTION_CLOSED      = 13
	IROH_EVENT_STREAM_OPENED          = 20
	IROH_EVENT_STREAM_ACCEPTED        = 21
	IROH_EVENT_FRAME_RECEIVED         = 22
	IROH_EVENT_SEND_COMPLETED         = 23
	IROH_EVENT_STREAM_FINISHED        = 24
	IROH_EVENT_STREAM_RESET           = 25
	// Blobs
	IROH_EVENT_BLOB_ADDED            = 30
	IROH_EVENT_BLOB_READ             = 31
	IROH_EVENT_BLOB_DOWNLOADED       = 32
	IROH_EVENT_BLOB_TICKET_CREATED   = 33
	IROH_EVENT_BLOB_COLLECTION_ADDED = 34
	// Tags
	IROH_EVENT_TAG_SET             = 36
	IROH_EVENT_TAG_GET             = 37
	IROH_EVENT_TAG_DELETED         = 38
	IROH_EVENT_TAG_LIST            = 39
	// Docs
	IROH_EVENT_DOC_CREATED             = 40
	IROH_EVENT_DOC_JOINED             = 41
	IROH_EVENT_DOC_SET                = 42
	IROH_EVENT_DOC_GET                = 43
	IROH_EVENT_DOC_SHARED             = 44
	IROH_EVENT_AUTHOR_CREATED         = 45
	IROH_EVENT_DOC_QUERY              = 46
	IROH_EVENT_DOC_SUBSCRIBED         = 47
	IROH_EVENT_DOC_EVENT              = 48
	IROH_EVENT_DOC_JOINED_AND_SUBSCRIBED = 49
	// Gossip
	IROH_EVENT_GOSSIP_SUBSCRIBED      = 50
	IROH_EVENT_GOSSIP_BROADCAST_DONE  = 51
	IROH_EVENT_GOSSIP_RECEIVED        = 52
	IROH_EVENT_GOSSIP_NEIGHBOR_UP     = 53
	IROH_EVENT_GOSSIP_NEIGHBOR_DOWN   = 54
	IROH_EVENT_GOSSIP_LAGGED          = 55
	// Datagrams
	IROH_EVENT_DATAGRAM_RECEIVED      = 60
	// Aster custom-ALPN
	IROH_EVENT_ASTER_ACCEPTED         = 65
	// Hooks
	IROH_EVENT_HOOK_BEFORE_CONNECT   = 70
	IROH_EVENT_HOOK_AFTER_CONNECT    = 71
	IROH_EVENT_HOOK_INVOCATION_RELEASED = 72
	// Generic
	IROH_EVENT_STRING_RESULT       = 90
	IROH_EVENT_BYTES_RESULT        = 91
	IROH_EVENT_UNIT_RESULT         = 92
	IROH_EVENT_OPERATION_CANCELLED = 98
	IROH_EVENT_ERROR               = 99
)
