/* Generated by cbindgen */

/* Generated with cbindgen:0.29.2 */

/* DO NOT EDIT */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define IROH_ABI_VERSION_MAJOR 1

#define IROH_ABI_VERSION_MINOR 0

#define IROH_ABI_VERSION_PATCH 0

/**
 * Status codes
 */
typedef enum iroh_status_t {
  IROH_STATUS_OK = 0,
  IROH_STATUS_INVALID_ARGUMENT = 1,
  IROH_STATUS_NOT_FOUND = 2,
  IROH_STATUS_ALREADY_CLOSED = 3,
  IROH_STATUS_QUEUE_FULL = 4,
  IROH_STATUS_BUFFER_TOO_SMALL = 5,
  IROH_STATUS_UNSUPPORTED = 6,
  IROH_STATUS_INTERNAL = 7,
  IROH_STATUS_TIMEOUT = 8,
  IROH_STATUS_CANCELLED = 9,
  IROH_STATUS_CONNECTION_REFUSED = 10,
  IROH_STATUS_STREAM_RESET = 11,
} iroh_status_t;

typedef struct iroh_runtime_config_t {
  uint32_t struct_size;
  uint32_t worker_threads;
  uint32_t event_queue_capacity;
  uint32_t reserved;
} iroh_runtime_config_t;

/**
 * Opaque handle types
 */
typedef uint64_t iroh_runtime_t;

/**
 * C-compatible event structure for FFI output
 */
typedef struct iroh_event_t {
  uint32_t struct_size;
  uint32_t kind;
  uint32_t status;
  uint64_t operation;
  uint64_t handle;
  uint64_t related;
  uint64_t user_data;
  const uint8_t *data_ptr;
  uintptr_t data_len;
  uint64_t buffer;
  int32_t error_code;
  uint32_t flags;
} iroh_event_t;

typedef uint64_t iroh_operation_t;

typedef struct iroh_bytes_t {
  const uint8_t *ptr;
  uintptr_t len;
} iroh_bytes_t;

typedef uint64_t iroh_node_t;

typedef struct iroh_bytes_list_t {
  const struct iroh_bytes_t *items;
  uintptr_t len;
} iroh_bytes_list_t;

typedef struct iroh_node_addr_t {
  struct iroh_bytes_t endpoint_id;
  struct iroh_bytes_t relay_url;
  struct iroh_bytes_list_t direct_addresses;
} iroh_node_addr_t;

typedef struct iroh_endpoint_config_t {
  uint32_t struct_size;
  uint32_t relay_mode;
  struct iroh_bytes_t secret_key;
  struct iroh_bytes_list_t alpns;
  struct iroh_bytes_list_t relay_urls;
  uint32_t enable_discovery;
  uint32_t reserved;
} iroh_endpoint_config_t;

typedef uint64_t iroh_endpoint_t;

typedef struct iroh_connect_config_t {
  uint32_t struct_size;
  uint32_t flags;
  struct iroh_bytes_t node_id;
  struct iroh_bytes_t alpn;
  const struct iroh_node_addr_t *addr;
} iroh_connect_config_t;

typedef uint64_t iroh_connection_t;

typedef uint64_t iroh_send_stream_t;

typedef uint64_t iroh_recv_stream_t;

uint32_t iroh_abi_version_major(void);

uint32_t iroh_abi_version_minor(void);

uint32_t iroh_abi_version_patch(void);

int32_t iroh_runtime_new(const struct iroh_runtime_config_t *config, iroh_runtime_t *out_runtime);

int32_t iroh_runtime_close(iroh_runtime_t runtime);

int32_t iroh_secret_key_generate(uint8_t *out_key_ptr,
                                 uintptr_t out_key_capacity,
                                 uintptr_t *out_len);

uintptr_t iroh_poll_events(iroh_runtime_t runtime,
                           struct iroh_event_t *out_events,
                           uintptr_t max_events,
                           uint32_t timeout_ms);

int32_t iroh_buffer_release(iroh_runtime_t runtime, uint64_t buffer);

int32_t iroh_operation_cancel(iroh_runtime_t runtime, iroh_operation_t operation);

uintptr_t iroh_last_error_message(uint8_t *buffer, uintptr_t capacity);

const char *iroh_status_name(enum iroh_status_t status);

int32_t iroh_node_memory(iroh_runtime_t runtime,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

int32_t iroh_node_persistent(iroh_runtime_t runtime,
                             struct iroh_bytes_t path,
                             uint64_t user_data,
                             iroh_operation_t *out_operation);

int32_t iroh_node_close(iroh_runtime_t runtime,
                        iroh_node_t node,
                        uint64_t user_data,
                        iroh_operation_t *out_operation);

int32_t iroh_node_id(iroh_runtime_t runtime,
                     iroh_node_t node,
                     uint8_t *out_buf,
                     uintptr_t capacity,
                     uintptr_t *out_len);

int32_t iroh_node_addr_info(iroh_runtime_t runtime,
                            iroh_node_t node,
                            uint8_t *out_buf,
                            uintptr_t buf_capacity,
                            struct iroh_node_addr_t *out_addr);

int32_t iroh_node_export_secret_key(iroh_runtime_t runtime,
                                    iroh_node_t node,
                                    uint8_t *out_buf,
                                    uintptr_t capacity,
                                    uintptr_t *out_len);

int32_t iroh_endpoint_create(iroh_runtime_t runtime,
                             const struct iroh_endpoint_config_t *config,
                             uint64_t user_data,
                             iroh_operation_t *out_operation);

int32_t iroh_endpoint_close(iroh_runtime_t runtime,
                            iroh_endpoint_t endpoint,
                            uint64_t user_data,
                            iroh_operation_t *out_operation);

int32_t iroh_endpoint_id(iroh_runtime_t runtime,
                         iroh_endpoint_t endpoint,
                         uint8_t *out_buf,
                         uintptr_t capacity,
                         uintptr_t *out_len);

int32_t iroh_connect(iroh_runtime_t runtime,
                     uint64_t endpoint_or_node,
                     const struct iroh_connect_config_t *config,
                     uint64_t user_data,
                     iroh_operation_t *out_operation);

int32_t iroh_accept(iroh_runtime_t runtime,
                    uint64_t endpoint_or_node,
                    uint64_t user_data,
                    iroh_operation_t *out_operation);

int32_t iroh_connection_remote_id(iroh_runtime_t runtime,
                                  iroh_connection_t connection,
                                  uint8_t *out_buf,
                                  uintptr_t capacity,
                                  uintptr_t *out_len);

int32_t iroh_connection_close(iroh_runtime_t runtime,
                              iroh_connection_t connection,
                              uint32_t error_code,
                              struct iroh_bytes_t reason);

int32_t iroh_connection_send_datagram(iroh_runtime_t runtime,
                                      iroh_connection_t connection,
                                      struct iroh_bytes_t data);

int32_t iroh_connection_read_datagram(iroh_runtime_t runtime,
                                      iroh_connection_t connection,
                                      uint64_t user_data,
                                      iroh_operation_t *out_operation);

int32_t iroh_open_bi(iroh_runtime_t runtime,
                     iroh_connection_t connection,
                     uint64_t user_data,
                     iroh_operation_t *out_operation);

int32_t iroh_accept_bi(iroh_runtime_t runtime,
                       iroh_connection_t connection,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

int32_t iroh_open_uni(iroh_runtime_t runtime,
                      iroh_connection_t connection,
                      uint64_t user_data,
                      iroh_operation_t *out_operation);

int32_t iroh_accept_uni(iroh_runtime_t runtime,
                        iroh_connection_t connection,
                        uint64_t user_data,
                        iroh_operation_t *out_operation);

int32_t iroh_stream_write(iroh_runtime_t runtime,
                          iroh_send_stream_t send_stream,
                          struct iroh_bytes_t data,
                          uint64_t user_data,
                          iroh_operation_t *out_operation);

int32_t iroh_stream_finish(iroh_runtime_t runtime,
                           iroh_send_stream_t send_stream,
                           uint64_t user_data,
                           iroh_operation_t *out_operation);

int32_t iroh_stream_read(iroh_runtime_t runtime,
                         iroh_recv_stream_t recv_stream,
                         uintptr_t max_len,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

int32_t iroh_stream_read_to_end(iroh_runtime_t runtime,
                                iroh_recv_stream_t recv_stream,
                                uintptr_t max_size,
                                uint64_t user_data,
                                iroh_operation_t *out_operation);

int32_t iroh_stream_stop(iroh_runtime_t runtime,
                         iroh_recv_stream_t recv_stream,
                         uint32_t error_code);

int32_t iroh_node_free(iroh_runtime_t runtime, iroh_node_t node);

int32_t iroh_endpoint_free(iroh_runtime_t runtime, iroh_endpoint_t endpoint);

int32_t iroh_connection_free(iroh_runtime_t runtime, iroh_connection_t connection);

int32_t iroh_send_stream_free(iroh_runtime_t runtime, iroh_send_stream_t stream);

int32_t iroh_recv_stream_free(iroh_runtime_t runtime, iroh_recv_stream_t stream);

int32_t iroh_doc_free(iroh_runtime_t runtime, uint64_t doc);

int32_t iroh_gossip_topic_free(iroh_runtime_t runtime, uint64_t topic);

int32_t iroh_blobs_add_bytes(iroh_runtime_t runtime,
                             iroh_node_t node,
                             struct iroh_bytes_t data,
                             uint64_t user_data,
                             iroh_operation_t *out_operation);

int32_t iroh_blobs_read(iroh_runtime_t runtime,
                        iroh_node_t node,
                        struct iroh_bytes_t hash_hex,
                        uint64_t user_data,
                        iroh_operation_t *out_operation);

int32_t iroh_docs_create(iroh_runtime_t runtime,
                         iroh_node_t node,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);

int32_t iroh_docs_create_author(iroh_runtime_t runtime,
                                iroh_node_t node,
                                uint64_t user_data,
                                iroh_operation_t *out_operation);

int32_t iroh_doc_set_bytes(iroh_runtime_t runtime,
                           uint64_t doc,
                           struct iroh_bytes_t author_hex,
                           struct iroh_bytes_t key,
                           struct iroh_bytes_t value,
                           uint64_t user_data,
                           iroh_operation_t *out_operation);

int32_t iroh_doc_get_exact(iroh_runtime_t runtime,
                           uint64_t doc,
                           struct iroh_bytes_t author_hex,
                           struct iroh_bytes_t key,
                           uint64_t user_data,
                           iroh_operation_t *out_operation);

int32_t iroh_doc_share(iroh_runtime_t runtime,
                       uint64_t doc,
                       uint32_t mode,
                       uint64_t user_data,
                       iroh_operation_t *out_operation);

int32_t iroh_gossip_subscribe(iroh_runtime_t runtime,
                              iroh_node_t node,
                              struct iroh_bytes_t topic,
                              struct iroh_bytes_list_t peers,
                              uint64_t user_data,
                              iroh_operation_t *out_operation);

int32_t iroh_gossip_broadcast(iroh_runtime_t runtime,
                              uint64_t topic,
                              struct iroh_bytes_t data,
                              uint64_t user_data,
                              iroh_operation_t *out_operation);

int32_t iroh_gossip_recv(iroh_runtime_t runtime,
                         uint64_t topic,
                         uint64_t user_data,
                         iroh_operation_t *out_operation);
