// @ts-nocheck
// AUTOGENERATED by @aster-rpc/aster — do not edit.
// Regenerate with: npx aster-gen

import { RpcPattern } from '@aster-rpc/aster';
import { Assignment as T0_Assignment, Command as T1_Command, CommandResult as T2_CommandResult, Heartbeat as T3_Heartbeat, IngestResult as T4_IngestResult, LogEntry as T5_LogEntry, MetricPoint as T6_MetricPoint, StatusRequest as T7_StatusRequest, StatusResponse as T8_StatusResponse, SubmitLogResult as T9_SubmitLogResult, TailRequest as T10_TailRequest } from './types.js';
import { MissionControl as T11_MissionControl, AgentSession as T12_AgentSession } from './services.js';
import { MissionControl as T13_MissionControl, AgentSession as T14_AgentSession } from './services-auth.js';

export const WIRE_TYPES = [
  {
    ctor: T0_Assignment,
    tag: "mission/Assignment",
    fields: [
    { name: "task_id", kind: 'primitive', wire: "string", nullable: false },
    { name: "command", kind: 'primitive', wire: "string", nullable: false },
    ],
    fieldNameSet: new Set(["task_id", "command"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T1_Command,
    tag: "mission/Command",
    fields: [
    { name: "command", kind: 'primitive', wire: "string", nullable: false },
    ],
    fieldNameSet: new Set(["command"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T2_CommandResult,
    tag: "mission/CommandResult",
    fields: [
    { name: "stdout", kind: 'primitive', wire: "string", nullable: false },
    { name: "stderr", kind: 'primitive', wire: "string", nullable: false },
    { name: "exit_code", kind: 'primitive', wire: "float64", nullable: false },
    ],
    fieldNameSet: new Set(["stdout", "stderr", "exit_code"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T3_Heartbeat,
    tag: "mission/Heartbeat",
    fields: [
    { name: "agent_id", kind: 'primitive', wire: "string", nullable: false },
    { name: "capabilities", kind: 'list', element: { name: "capabilities[]", kind: 'primitive', wire: "string", nullable: false }, nullable: false },
    { name: "load_avg", kind: 'primitive', wire: "float64", nullable: false },
    ],
    fieldNameSet: new Set(["agent_id", "capabilities", "load_avg"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T4_IngestResult,
    tag: "mission/IngestResult",
    fields: [
    { name: "accepted", kind: 'primitive', wire: "float64", nullable: false },
    { name: "dropped", kind: 'primitive', wire: "float64", nullable: false },
    ],
    fieldNameSet: new Set(["accepted", "dropped"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T5_LogEntry,
    tag: "mission/LogEntry",
    fields: [
    { name: "timestamp", kind: 'primitive', wire: "float64", nullable: false },
    { name: "level", kind: 'primitive', wire: "string", nullable: false },
    { name: "message", kind: 'primitive', wire: "string", nullable: false },
    { name: "agent_id", kind: 'primitive', wire: "string", nullable: false },
    ],
    fieldNameSet: new Set(["timestamp", "level", "message", "agent_id"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T6_MetricPoint,
    tag: "mission/MetricPoint",
    fields: [
    { name: "name", kind: 'primitive', wire: "string", nullable: false },
    { name: "value", kind: 'primitive', wire: "float64", nullable: false },
    { name: "timestamp", kind: 'primitive', wire: "float64", nullable: false },
    { name: "tags", kind: 'map', key: { name: "tags[key]", kind: 'primitive', wire: "string", nullable: false }, value: { name: "tags[value]", kind: 'primitive', wire: "string", nullable: false }, nullable: false },
    ],
    fieldNameSet: new Set(["name", "value", "timestamp", "tags"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T7_StatusRequest,
    tag: "mission/StatusRequest",
    fields: [
    { name: "agent_id", kind: 'primitive', wire: "string", nullable: false },
    ],
    fieldNameSet: new Set(["agent_id"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T8_StatusResponse,
    tag: "mission/StatusResponse",
    fields: [
    { name: "agent_id", kind: 'primitive', wire: "string", nullable: false },
    { name: "status", kind: 'primitive', wire: "string", nullable: false },
    { name: "uptime_secs", kind: 'primitive', wire: "float64", nullable: false },
    ],
    fieldNameSet: new Set(["agent_id", "status", "uptime_secs"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T9_SubmitLogResult,
    tag: "mission/SubmitLogResult",
    fields: [
    { name: "accepted", kind: 'primitive', wire: "bool", nullable: false },
    ],
    fieldNameSet: new Set(["accepted"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T10_TailRequest,
    tag: "mission/TailRequest",
    fields: [
    { name: "agent_id", kind: 'primitive', wire: "string", nullable: false },
    { name: "level", kind: 'primitive', wire: "string", nullable: false },
    ],
    fieldNameSet: new Set(["agent_id", "level"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
] as const;

/**
 * Build and register all @WireType classes with Fory, using Type.struct()
 * to describe each struct's fields with explicit wire types.
 *
 * Iterates over WIRE_TYPES so that entry.ctor is the actual class ref.
 * For 'ref' fields, looks up the target type from typesByTag by refTag.
 * Types are registered in topological order (leaves first), so all
 * dependencies are available when any given type is being registered.
 *
 * @returns Map<tag, typeStruct> — each registered Fory type struct, keyed
 *   by wire tag (e.g. "sample/StatusRequest"). Callers can use this to
 *   look up any type after registration.
 */
export function BUILD_ALL_TYPES(
  fory: any,
  Type: any,
  codec: { registerType(typeInfo: any): void },
): Map<string, any> {
  const typesByTag = new Map();
  for (const entry of WIRE_TYPES) {
  // mission/Assignment
  {
    const [ns, typeName] = "mission/Assignment".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "task_id": Type.string(),
      "command": Type.string()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("mission/Assignment", typeStruct);
  }
  // mission/Command
  {
    const [ns, typeName] = "mission/Command".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "command": Type.string()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("mission/Command", typeStruct);
  }
  // mission/CommandResult
  {
    const [ns, typeName] = "mission/CommandResult".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "stdout": Type.string(),
      "stderr": Type.string(),
      "exit_code": Type.float64()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("mission/CommandResult", typeStruct);
  }
  // mission/Heartbeat
  {
    const [ns, typeName] = "mission/Heartbeat".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "agent_id": Type.string(),
      "capabilities": Type.array(Type.string()),
      "load_avg": Type.float64()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("mission/Heartbeat", typeStruct);
  }
  // mission/IngestResult
  {
    const [ns, typeName] = "mission/IngestResult".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "accepted": Type.float64(),
      "dropped": Type.float64()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("mission/IngestResult", typeStruct);
  }
  // mission/LogEntry
  {
    const [ns, typeName] = "mission/LogEntry".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "timestamp": Type.float64(),
      "level": Type.string(),
      "message": Type.string(),
      "agent_id": Type.string()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("mission/LogEntry", typeStruct);
  }
  // mission/MetricPoint
  {
    const [ns, typeName] = "mission/MetricPoint".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "name": Type.string(),
      "value": Type.float64(),
      "timestamp": Type.float64(),
      "tags": Type.map(Type.string(), Type.string())
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("mission/MetricPoint", typeStruct);
  }
  // mission/StatusRequest
  {
    const [ns, typeName] = "mission/StatusRequest".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "agent_id": Type.string()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("mission/StatusRequest", typeStruct);
  }
  // mission/StatusResponse
  {
    const [ns, typeName] = "mission/StatusResponse".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "agent_id": Type.string(),
      "status": Type.string(),
      "uptime_secs": Type.float64()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("mission/StatusResponse", typeStruct);
  }
  // mission/SubmitLogResult
  {
    const [ns, typeName] = "mission/SubmitLogResult".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "accepted": Type.bool()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("mission/SubmitLogResult", typeStruct);
  }
  // mission/TailRequest
  {
    const [ns, typeName] = "mission/TailRequest".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "agent_id": Type.string(),
      "level": Type.string()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("mission/TailRequest", typeStruct);
  }
  }
  return typesByTag;
}


export const SERVICES = [
  {
    ctor: T11_MissionControl,
    name: "MissionControl",
    version: 1,
    scoped: "shared",
    serializationModes: [],
    requires: undefined,
    metadata: undefined,
    methods: [
    {
      name: "getStatus",
      pattern: RpcPattern.UNARY,
      requestType: T7_StatusRequest,
      responseType: T8_StatusResponse,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agent_id","type":"str","required":true,"default":""}],
      responseFields: [{"name":"agent_id","type":"str","required":true,"default":""},{"name":"status","type":"str","required":true,"default":""},{"name":"uptime_secs","type":"float","required":true,"default":0}],
      requestTypeHash: new Uint8Array([0xc0, 0x7e, 0x2a, 0xc3, 0xdf, 0x1f, 0xa1, 0x91, 0x4d, 0x97, 0xc7, 0xcf, 0xac, 0x33, 0xd9, 0xd8, 0x67, 0xd0, 0x71, 0x0b, 0xac, 0xc6, 0x0e, 0xa8, 0x1b, 0x7f, 0x93, 0xf6, 0x2d, 0x92, 0xe7, 0xce]),
      responseTypeHash: new Uint8Array([0x5e, 0x23, 0x1e, 0x01, 0x39, 0x19, 0x58, 0x02, 0xdd, 0xba, 0x06, 0x02, 0x7a, 0xbd, 0x70, 0xb5, 0xb4, 0xaf, 0xba, 0xc3, 0x76, 0xdc, 0xf4, 0x9e, 0xae, 0x96, 0x1c, 0xd1, 0x8a, 0xb7, 0x95, 0x93]),
    },
    {
      name: "submitLog",
      pattern: RpcPattern.UNARY,
      requestType: T5_LogEntry,
      responseType: T9_SubmitLogResult,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"timestamp","type":"float","required":true,"default":0},{"name":"level","type":"str","required":true,"default":""},{"name":"message","type":"str","required":true,"default":""},{"name":"agent_id","type":"str","required":true,"default":""}],
      responseFields: [{"name":"accepted","type":"bool","required":true,"default":false}],
      requestTypeHash: new Uint8Array([0x07, 0x3d, 0xa4, 0x8b, 0x88, 0x4e, 0x6a, 0x49, 0xf3, 0x35, 0x2b, 0x35, 0xd8, 0xde, 0xa1, 0x28, 0x41, 0x83, 0x4a, 0xb0, 0xe1, 0x67, 0xe5, 0xa5, 0x14, 0x9c, 0x6c, 0x46, 0x38, 0x81, 0xf7, 0xb3]),
      responseTypeHash: new Uint8Array([0x51, 0x89, 0x79, 0x57, 0x96, 0x75, 0x20, 0x33, 0x41, 0x84, 0x77, 0x50, 0xc3, 0xb8, 0x73, 0x3b, 0x05, 0x8b, 0xc3, 0x5e, 0xd5, 0x5b, 0xaa, 0x69, 0x5a, 0xed, 0x49, 0xd8, 0x7d, 0xb8, 0x1f, 0x49]),
    },
    {
      name: "tailLogs",
      pattern: RpcPattern.SERVER_STREAM,
      requestType: T10_TailRequest,
      responseType: T5_LogEntry,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agent_id","type":"str","required":true,"default":""},{"name":"level","type":"str","required":true,"default":""}],
      responseFields: [{"name":"timestamp","type":"float","required":true,"default":0},{"name":"level","type":"str","required":true,"default":""},{"name":"message","type":"str","required":true,"default":""},{"name":"agent_id","type":"str","required":true,"default":""}],
      requestTypeHash: new Uint8Array([0x59, 0x8a, 0x60, 0xc1, 0xa2, 0x77, 0x9c, 0xbd, 0x1e, 0x25, 0x2d, 0xde, 0x02, 0x14, 0xbc, 0x45, 0xd9, 0x6f, 0xb7, 0x06, 0xae, 0x89, 0x06, 0x9d, 0x8c, 0x46, 0xd8, 0x15, 0x52, 0x92, 0x73, 0x83]),
      responseTypeHash: new Uint8Array([0x07, 0x3d, 0xa4, 0x8b, 0x88, 0x4e, 0x6a, 0x49, 0xf3, 0x35, 0x2b, 0x35, 0xd8, 0xde, 0xa1, 0x28, 0x41, 0x83, 0x4a, 0xb0, 0xe1, 0x67, 0xe5, 0xa5, 0x14, 0x9c, 0x6c, 0x46, 0x38, 0x81, 0xf7, 0xb3]),
    },
    {
      name: "ingestMetrics",
      pattern: RpcPattern.CLIENT_STREAM,
      requestType: T6_MetricPoint,
      responseType: T4_IngestResult,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"name","type":"str","required":true,"default":""},{"name":"value","type":"float","required":true,"default":0},{"name":"timestamp","type":"float","required":true,"default":0},{"name":"tags","type":"dict","required":true,"default":{}}],
      responseFields: [{"name":"accepted","type":"float","required":true,"default":0},{"name":"dropped","type":"float","required":true,"default":0}],
      requestTypeHash: new Uint8Array([0x13, 0x86, 0x9d, 0x74, 0xe3, 0x16, 0x9c, 0x25, 0x52, 0x1b, 0x55, 0x15, 0x71, 0x21, 0x20, 0xf4, 0x3e, 0x4a, 0xaf, 0x82, 0x1f, 0x6d, 0xcb, 0xfd, 0xf9, 0x10, 0x31, 0xda, 0xda, 0x31, 0xa5, 0x6f]),
      responseTypeHash: new Uint8Array([0x7e, 0xd8, 0xdc, 0xfc, 0x88, 0x99, 0xde, 0xe4, 0x0f, 0xf9, 0x07, 0xb2, 0x0a, 0xff, 0x00, 0x20, 0xbd, 0x0a, 0xfc, 0x4e, 0x93, 0x9f, 0x3d, 0x06, 0xfe, 0xcf, 0xd2, 0xdb, 0x12, 0x1d, 0x37, 0x6d]),
    },
    ],
  },
  {
    ctor: T12_AgentSession,
    name: "AgentSession",
    version: 1,
    scoped: "session",
    serializationModes: [],
    requires: undefined,
    metadata: undefined,
    methods: [
    {
      name: "register",
      pattern: RpcPattern.UNARY,
      requestType: T3_Heartbeat,
      responseType: T0_Assignment,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agent_id","type":"str","required":true,"default":""},{"name":"capabilities","type":"list","required":true,"default":[]},{"name":"load_avg","type":"float","required":true,"default":0}],
      responseFields: [{"name":"task_id","type":"str","required":true,"default":""},{"name":"command","type":"str","required":true,"default":""}],
      requestTypeHash: new Uint8Array([0xd4, 0xdc, 0x17, 0xa8, 0x9c, 0x4d, 0x12, 0xac, 0x44, 0x96, 0x11, 0x87, 0x5a, 0xe7, 0x0b, 0x9b, 0x39, 0x9e, 0x8e, 0xb1, 0xfc, 0xc4, 0x0b, 0xe1, 0xf7, 0xb6, 0x89, 0x63, 0x06, 0xa5, 0x17, 0x56]),
      responseTypeHash: new Uint8Array([0x4c, 0xbd, 0x6a, 0x77, 0xdf, 0x22, 0x49, 0x22, 0x6b, 0x3d, 0x68, 0xce, 0x74, 0x56, 0x42, 0x30, 0x37, 0xde, 0x08, 0xbd, 0x13, 0xb9, 0xf0, 0x0a, 0xed, 0xd0, 0xce, 0x14, 0x71, 0x8c, 0x36, 0xe4]),
    },
    {
      name: "heartbeat",
      pattern: RpcPattern.UNARY,
      requestType: T3_Heartbeat,
      responseType: T0_Assignment,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agent_id","type":"str","required":true,"default":""},{"name":"capabilities","type":"list","required":true,"default":[]},{"name":"load_avg","type":"float","required":true,"default":0}],
      responseFields: [{"name":"task_id","type":"str","required":true,"default":""},{"name":"command","type":"str","required":true,"default":""}],
      requestTypeHash: new Uint8Array([0xd4, 0xdc, 0x17, 0xa8, 0x9c, 0x4d, 0x12, 0xac, 0x44, 0x96, 0x11, 0x87, 0x5a, 0xe7, 0x0b, 0x9b, 0x39, 0x9e, 0x8e, 0xb1, 0xfc, 0xc4, 0x0b, 0xe1, 0xf7, 0xb6, 0x89, 0x63, 0x06, 0xa5, 0x17, 0x56]),
      responseTypeHash: new Uint8Array([0x4c, 0xbd, 0x6a, 0x77, 0xdf, 0x22, 0x49, 0x22, 0x6b, 0x3d, 0x68, 0xce, 0x74, 0x56, 0x42, 0x30, 0x37, 0xde, 0x08, 0xbd, 0x13, 0xb9, 0xf0, 0x0a, 0xed, 0xd0, 0xce, 0x14, 0x71, 0x8c, 0x36, 0xe4]),
    },
    {
      name: "runCommand",
      pattern: RpcPattern.BIDI_STREAM,
      requestType: T1_Command,
      responseType: T2_CommandResult,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"command","type":"str","required":true,"default":""}],
      responseFields: [{"name":"stdout","type":"str","required":true,"default":""},{"name":"stderr","type":"str","required":true,"default":""},{"name":"exit_code","type":"float","required":true,"default":0}],
      requestTypeHash: new Uint8Array([0x55, 0xb7, 0x9e, 0x20, 0x56, 0xcb, 0xb1, 0x10, 0x40, 0x40, 0xca, 0x22, 0x94, 0xa4, 0x77, 0xe1, 0xab, 0x38, 0xb7, 0x08, 0x68, 0x6a, 0x73, 0x2c, 0xcb, 0x87, 0x08, 0x70, 0xa7, 0x31, 0xff, 0xa2]),
      responseTypeHash: new Uint8Array([0x8b, 0x76, 0xe3, 0x9f, 0xd9, 0xb2, 0xf2, 0xbf, 0x7b, 0xf9, 0x31, 0x39, 0x9e, 0x19, 0xfa, 0xde, 0x4a, 0x64, 0x2f, 0x2e, 0x9d, 0x69, 0x1a, 0xce, 0x0b, 0x69, 0xce, 0x0f, 0x5b, 0x85, 0x16, 0x11]),
    },
    ],
  },
  {
    ctor: T13_MissionControl,
    name: "MissionControl",
    version: 1,
    scoped: "shared",
    serializationModes: [],
    requires: undefined,
    metadata: undefined,
    methods: [
    {
      name: "getStatus",
      pattern: RpcPattern.UNARY,
      requestType: T7_StatusRequest,
      responseType: T8_StatusResponse,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agent_id","type":"str","required":true,"default":""}],
      responseFields: [{"name":"agent_id","type":"str","required":true,"default":""},{"name":"status","type":"str","required":true,"default":""},{"name":"uptime_secs","type":"float","required":true,"default":0}],
      requestTypeHash: new Uint8Array([0xc0, 0x7e, 0x2a, 0xc3, 0xdf, 0x1f, 0xa1, 0x91, 0x4d, 0x97, 0xc7, 0xcf, 0xac, 0x33, 0xd9, 0xd8, 0x67, 0xd0, 0x71, 0x0b, 0xac, 0xc6, 0x0e, 0xa8, 0x1b, 0x7f, 0x93, 0xf6, 0x2d, 0x92, 0xe7, 0xce]),
      responseTypeHash: new Uint8Array([0x5e, 0x23, 0x1e, 0x01, 0x39, 0x19, 0x58, 0x02, 0xdd, 0xba, 0x06, 0x02, 0x7a, 0xbd, 0x70, 0xb5, 0xb4, 0xaf, 0xba, 0xc3, 0x76, 0xdc, 0xf4, 0x9e, 0xae, 0x96, 0x1c, 0xd1, 0x8a, 0xb7, 0x95, 0x93]),
    },
    {
      name: "submitLog",
      pattern: RpcPattern.UNARY,
      requestType: T5_LogEntry,
      responseType: T9_SubmitLogResult,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"timestamp","type":"float","required":true,"default":0},{"name":"level","type":"str","required":true,"default":""},{"name":"message","type":"str","required":true,"default":""},{"name":"agent_id","type":"str","required":true,"default":""}],
      responseFields: [{"name":"accepted","type":"bool","required":true,"default":false}],
      requestTypeHash: new Uint8Array([0x07, 0x3d, 0xa4, 0x8b, 0x88, 0x4e, 0x6a, 0x49, 0xf3, 0x35, 0x2b, 0x35, 0xd8, 0xde, 0xa1, 0x28, 0x41, 0x83, 0x4a, 0xb0, 0xe1, 0x67, 0xe5, 0xa5, 0x14, 0x9c, 0x6c, 0x46, 0x38, 0x81, 0xf7, 0xb3]),
      responseTypeHash: new Uint8Array([0x51, 0x89, 0x79, 0x57, 0x96, 0x75, 0x20, 0x33, 0x41, 0x84, 0x77, 0x50, 0xc3, 0xb8, 0x73, 0x3b, 0x05, 0x8b, 0xc3, 0x5e, 0xd5, 0x5b, 0xaa, 0x69, 0x5a, 0xed, 0x49, 0xd8, 0x7d, 0xb8, 0x1f, 0x49]),
    },
    {
      name: "tailLogs",
      pattern: RpcPattern.SERVER_STREAM,
      requestType: T10_TailRequest,
      responseType: T5_LogEntry,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agent_id","type":"str","required":true,"default":""},{"name":"level","type":"str","required":true,"default":""}],
      responseFields: [{"name":"timestamp","type":"float","required":true,"default":0},{"name":"level","type":"str","required":true,"default":""},{"name":"message","type":"str","required":true,"default":""},{"name":"agent_id","type":"str","required":true,"default":""}],
      requestTypeHash: new Uint8Array([0x59, 0x8a, 0x60, 0xc1, 0xa2, 0x77, 0x9c, 0xbd, 0x1e, 0x25, 0x2d, 0xde, 0x02, 0x14, 0xbc, 0x45, 0xd9, 0x6f, 0xb7, 0x06, 0xae, 0x89, 0x06, 0x9d, 0x8c, 0x46, 0xd8, 0x15, 0x52, 0x92, 0x73, 0x83]),
      responseTypeHash: new Uint8Array([0x07, 0x3d, 0xa4, 0x8b, 0x88, 0x4e, 0x6a, 0x49, 0xf3, 0x35, 0x2b, 0x35, 0xd8, 0xde, 0xa1, 0x28, 0x41, 0x83, 0x4a, 0xb0, 0xe1, 0x67, 0xe5, 0xa5, 0x14, 0x9c, 0x6c, 0x46, 0x38, 0x81, 0xf7, 0xb3]),
    },
    {
      name: "ingestMetrics",
      pattern: RpcPattern.CLIENT_STREAM,
      requestType: T6_MetricPoint,
      responseType: T4_IngestResult,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"name","type":"str","required":true,"default":""},{"name":"value","type":"float","required":true,"default":0},{"name":"timestamp","type":"float","required":true,"default":0},{"name":"tags","type":"dict","required":true,"default":{}}],
      responseFields: [{"name":"accepted","type":"float","required":true,"default":0},{"name":"dropped","type":"float","required":true,"default":0}],
      requestTypeHash: new Uint8Array([0x13, 0x86, 0x9d, 0x74, 0xe3, 0x16, 0x9c, 0x25, 0x52, 0x1b, 0x55, 0x15, 0x71, 0x21, 0x20, 0xf4, 0x3e, 0x4a, 0xaf, 0x82, 0x1f, 0x6d, 0xcb, 0xfd, 0xf9, 0x10, 0x31, 0xda, 0xda, 0x31, 0xa5, 0x6f]),
      responseTypeHash: new Uint8Array([0x7e, 0xd8, 0xdc, 0xfc, 0x88, 0x99, 0xde, 0xe4, 0x0f, 0xf9, 0x07, 0xb2, 0x0a, 0xff, 0x00, 0x20, 0xbd, 0x0a, 0xfc, 0x4e, 0x93, 0x9f, 0x3d, 0x06, 0xfe, 0xcf, 0xd2, 0xdb, 0x12, 0x1d, 0x37, 0x6d]),
    },
    ],
  },
  {
    ctor: T14_AgentSession,
    name: "AgentSession",
    version: 1,
    scoped: "session",
    serializationModes: [],
    requires: undefined,
    metadata: undefined,
    methods: [
    {
      name: "register",
      pattern: RpcPattern.UNARY,
      requestType: T3_Heartbeat,
      responseType: T0_Assignment,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agent_id","type":"str","required":true,"default":""},{"name":"capabilities","type":"list","required":true,"default":[]},{"name":"load_avg","type":"float","required":true,"default":0}],
      responseFields: [{"name":"task_id","type":"str","required":true,"default":""},{"name":"command","type":"str","required":true,"default":""}],
      requestTypeHash: new Uint8Array([0xd4, 0xdc, 0x17, 0xa8, 0x9c, 0x4d, 0x12, 0xac, 0x44, 0x96, 0x11, 0x87, 0x5a, 0xe7, 0x0b, 0x9b, 0x39, 0x9e, 0x8e, 0xb1, 0xfc, 0xc4, 0x0b, 0xe1, 0xf7, 0xb6, 0x89, 0x63, 0x06, 0xa5, 0x17, 0x56]),
      responseTypeHash: new Uint8Array([0x4c, 0xbd, 0x6a, 0x77, 0xdf, 0x22, 0x49, 0x22, 0x6b, 0x3d, 0x68, 0xce, 0x74, 0x56, 0x42, 0x30, 0x37, 0xde, 0x08, 0xbd, 0x13, 0xb9, 0xf0, 0x0a, 0xed, 0xd0, 0xce, 0x14, 0x71, 0x8c, 0x36, 0xe4]),
    },
    {
      name: "heartbeat",
      pattern: RpcPattern.UNARY,
      requestType: T3_Heartbeat,
      responseType: T0_Assignment,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agent_id","type":"str","required":true,"default":""},{"name":"capabilities","type":"list","required":true,"default":[]},{"name":"load_avg","type":"float","required":true,"default":0}],
      responseFields: [{"name":"task_id","type":"str","required":true,"default":""},{"name":"command","type":"str","required":true,"default":""}],
      requestTypeHash: new Uint8Array([0xd4, 0xdc, 0x17, 0xa8, 0x9c, 0x4d, 0x12, 0xac, 0x44, 0x96, 0x11, 0x87, 0x5a, 0xe7, 0x0b, 0x9b, 0x39, 0x9e, 0x8e, 0xb1, 0xfc, 0xc4, 0x0b, 0xe1, 0xf7, 0xb6, 0x89, 0x63, 0x06, 0xa5, 0x17, 0x56]),
      responseTypeHash: new Uint8Array([0x4c, 0xbd, 0x6a, 0x77, 0xdf, 0x22, 0x49, 0x22, 0x6b, 0x3d, 0x68, 0xce, 0x74, 0x56, 0x42, 0x30, 0x37, 0xde, 0x08, 0xbd, 0x13, 0xb9, 0xf0, 0x0a, 0xed, 0xd0, 0xce, 0x14, 0x71, 0x8c, 0x36, 0xe4]),
    },
    {
      name: "runCommand",
      pattern: RpcPattern.BIDI_STREAM,
      requestType: T1_Command,
      responseType: T2_CommandResult,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"command","type":"str","required":true,"default":""}],
      responseFields: [{"name":"stdout","type":"str","required":true,"default":""},{"name":"stderr","type":"str","required":true,"default":""},{"name":"exit_code","type":"float","required":true,"default":0}],
      requestTypeHash: new Uint8Array([0x55, 0xb7, 0x9e, 0x20, 0x56, 0xcb, 0xb1, 0x10, 0x40, 0x40, 0xca, 0x22, 0x94, 0xa4, 0x77, 0xe1, 0xab, 0x38, 0xb7, 0x08, 0x68, 0x6a, 0x73, 0x2c, 0xcb, 0x87, 0x08, 0x70, 0xa7, 0x31, 0xff, 0xa2]),
      responseTypeHash: new Uint8Array([0x8b, 0x76, 0xe3, 0x9f, 0xd9, 0xb2, 0xf2, 0xbf, 0x7b, 0xf9, 0x31, 0x39, 0x9e, 0x19, 0xfa, 0xde, 0x4a, 0x64, 0x2f, 0x2e, 0x9d, 0x69, 0x1a, 0xce, 0x0b, 0x69, 0xce, 0x0f, 0x5b, 0x85, 0x16, 0x11]),
    },
    ],
  },
] as const;
