"""
aster_cli.identity — Read/write ``.aster-identity`` TOML files.

The identity file is the node's complete runtime identity:
- One node secret key (→ stable EndpointId)
- One or more peer entries (enrollment credentials for different meshes/roles)

Format: TOML with ``[node]`` section and ``[[peers]]`` array of tables.
Permissions: 0600 (owner read/write only).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any


def _tomllib():
    if sys.version_info >= (3, 11):
        import tomllib
        return tomllib
    try:
        import tomli as tomllib  # type: ignore[no-redef]
        return tomllib
    except ImportError:
        print("Error: install tomli for Python < 3.11: pip install tomli", file=sys.stderr)
        sys.exit(1)


def load_identity(path: str | Path) -> dict:
    """Load an .aster-identity TOML file.

    Synthesizes ``aster.role`` and ``aster.name`` into each peer's
    ``attributes`` from the top-level ``role`` and ``name`` fields so
    callers always see a complete attributes dict.

    Returns:
        Dict with ``node`` (dict with ``secret_key``, ``endpoint_id``)
        and ``peers`` (list of dicts).
    """
    tomllib = _tomllib()
    with Path(path).open("rb") as f:
        data = tomllib.load(f)
    for peer in data.get("peers", []):
        attrs = peer.setdefault("attributes", {})
        if "aster.role" not in attrs and "role" in peer:
            attrs["aster.role"] = peer["role"]
        if "aster.name" not in attrs and "name" in peer:
            attrs["aster.name"] = peer["name"]
    return data


def save_identity(path: str | Path, data: dict) -> None:
    """Write an .aster-identity TOML file with 0600 permissions.

    Args:
        path: Output file path.
        data: Dict with ``node`` and ``peers`` keys.
    """
    lines = _serialize_identity(data)
    content = "\n".join(lines) + "\n"

    p = Path(path)
    tmp = p.with_suffix(".tmp")
    tmp.write_text(content)
    os.chmod(tmp, 0o600)
    tmp.replace(p)


def _serialize_identity(data: dict) -> list[str]:
    """Serialize an identity dict to TOML lines."""
    lines = ["# .aster-identity — generated by `aster enroll node`", ""]

    # [node] section
    node = data.get("node", {})
    lines.append("[node]")
    if "secret_key" in node:
        lines.append(f'secret_key = "{node["secret_key"]}"')
    if "endpoint_id" in node:
        lines.append(f'endpoint_id = "{node["endpoint_id"]}"')
    lines.append("")

    # [[peers]] array
    for peer in data.get("peers", []):
        lines.append("[[peers]]")
        # Write known fields in a stable order
        for field in ("name", "role", "type", "root_pubkey", "endpoint_id",
                      "expires_at", "nonce", "signature"):
            if field in peer:
                val = peer[field]
                if isinstance(val, str):
                    lines.append(f'{field} = "{val}"')
                elif isinstance(val, (int, float)):
                    lines.append(f'{field} = {val}')
                elif isinstance(val, bool):
                    lines.append(f'{field} = {"true" if val else "false"}')

        # Attributes as inline table (omit aster.role/aster.name if redundant)
        attrs = {k: v for k, v in peer.get("attributes", {}).items()
                 if not (k == "aster.role" and v == peer.get("role"))
                 and not (k == "aster.name" and v == peer.get("name"))}
        if attrs:
            pairs = ", ".join(f'"{k}" = "{v}"' for k, v in sorted(attrs.items()))
            lines.append(f"attributes = {{ {pairs} }}")

        lines.append("")

    return lines


def add_peer(identity_data: dict, peer: dict) -> dict:
    """Add a peer entry to an identity dict (or update by name).

    If a peer with the same ``name`` exists, it is replaced.

    Returns:
        The updated identity dict.
    """
    peers = identity_data.setdefault("peers", [])
    name = peer.get("name")
    if name:
        peers[:] = [p for p in peers if p.get("name") != name]
    peers.append(peer)
    return identity_data


def find_peer(identity_data: dict, name: str | None = None,
              role: str | None = None) -> dict | None:
    """Find a peer entry by name or role.

    If ``name`` is given, match by name. Otherwise match by role
    (returns the first match). Returns None if not found.
    """
    for peer in identity_data.get("peers", []):
        if name is not None and peer.get("name") == name:
            return peer
        if name is None and role is not None and peer.get("role") == role:
            return peer
    return None
