// @ts-nocheck
// AUTOGENERATED by @aster-rpc/aster — do not edit.
// Regenerate with: npx aster-gen

import { RpcPattern } from '@aster-rpc/aster';
import { StatusResponse as T0_StatusResponse, StatusEvent as T1_StatusEvent, StatusRequest as T2_StatusRequest, WatchRequest as T3_WatchRequest } from './src/types.js';
import { MissionControlService as T4_MissionControlService } from './src/service.js';

export const WIRE_TYPES = [
  {
    ctor: T0_StatusResponse,
    tag: "sample/StatusResponse",
    fields: [
    { name: "status", kind: 'primitive', wire: "string", nullable: false },
    { name: "uptime", kind: 'primitive', wire: "int32", nullable: false },
    { name: "warnings", kind: 'list', element: { name: "warnings[]", kind: 'primitive', wire: "string", nullable: false }, nullable: false },
    ],
    fieldNameSet: new Set(["status", "uptime", "warnings"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T1_StatusEvent,
    tag: "sample/StatusEvent",
    fields: [
    { name: "at", kind: 'primitive', wire: "timestamp", nullable: false },
    { name: "status", kind: 'ref', refTag: "sample/StatusResponse", nullable: false },
    { name: "optionalNote", kind: 'primitive', wire: "string", nullable: true },
    ],
    fieldNameSet: new Set(["at", "status", "optionalNote"]),
    nestedTypes: new Map([["status", T0_StatusResponse]]),
    elementTypes: new Map([]),
  },
  {
    ctor: T2_StatusRequest,
    tag: "sample/StatusRequest",
    fields: [
    { name: "agentId", kind: 'primitive', wire: "string", nullable: false },
    { name: "nonce", kind: 'primitive', wire: "int64", nullable: false },
    ],
    fieldNameSet: new Set(["agentId", "nonce"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
  {
    ctor: T3_WatchRequest,
    tag: "sample/WatchRequest",
    fields: [
    { name: "agentId", kind: 'primitive', wire: "string", nullable: false },
    { name: "includeWarnings", kind: 'primitive', wire: "bool", nullable: false },
    ],
    fieldNameSet: new Set(["agentId", "includeWarnings"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
  },
] as const;

/**
 * Build and register all @WireType classes with Fory, using Type.struct()
 * to describe each struct's fields with explicit wire types.
 *
 * Iterates over WIRE_TYPES so that entry.ctor is the actual class ref.
 * For 'ref' fields, looks up the target type from typesByTag by refTag.
 * Types are registered in topological order (leaves first), so all
 * dependencies are available when any given type is being registered.
 *
 * @returns Map<tag, typeStruct> — each registered Fory type struct, keyed
 *   by wire tag (e.g. "sample/StatusRequest"). Callers can use this to
 *   look up any type after registration.
 */
export function BUILD_ALL_TYPES(
  fory: any,
  Type: any,
  codec: { registerType(typeInfo: any): void },
): Map<string, any> {
  const typesByTag = new Map();
  for (const entry of WIRE_TYPES) {
  // sample/StatusResponse
  {
    const [ns, typeName] = "sample/StatusResponse".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "status": Type.string(),
      "uptime": Type.int32(),
      "warnings": Type.array(Type.string())
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("sample/StatusResponse", typeStruct);
  }
  // sample/StatusEvent
  {
    const [ns, typeName] = "sample/StatusEvent".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "at": Type.timestamp(),
      "status": typesByTag.get("sample/StatusResponse"),
      "optionalNote": Type.optional(Type.string())
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("sample/StatusEvent", typeStruct);
  }
  // sample/StatusRequest
  {
    const [ns, typeName] = "sample/StatusRequest".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "agentId": Type.string(),
      "nonce": Type.int64()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("sample/StatusRequest", typeStruct);
  }
  // sample/WatchRequest
  {
    const [ns, typeName] = "sample/WatchRequest".split('/');
    const typeStruct = Type.struct(
      { namespace: ns, typeName },
      {
      "agentId": Type.string(),
      "includeWarnings": Type.bool()
      },
      { withConstructor: true },
    );
    // entry.ctor is the actual class constructor from WIRE_TYPES.
    // initMeta can only be called once per class (sets non-configurable property).
    // Skip if already initialized (prototype already has ForyTypeInfoSymbol set).
    const proto = entry.ctor.prototype;
    if (!proto.hasOwnProperty('__foryTypeInfoInit__')) {
      try {
        typeStruct.initMeta(entry.ctor);
        Object.defineProperty(proto, '__foryTypeInfoInit__', { value: true, configurable: true });
      } catch (e: any) {
        // already initialized — skip
      }
    }
    codec.registerType(typeStruct);
    typesByTag.set("sample/WatchRequest", typeStruct);
  }
  }
  return typesByTag;
}


export const SERVICES = [
  {
    ctor: T4_MissionControlService,
    name: "MissionControl",
    version: 1,
    scoped: "shared",
    serializationModes: [],
    requires: undefined,
    metadata: undefined,
    methods: [
    {
      name: "getStatus",
      pattern: RpcPattern.UNARY,
      requestType: T2_StatusRequest,
      responseType: T0_StatusResponse,
      acceptsCtx: false,
      idempotent: true,
      timeout: 30,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agentId","type":"str","required":true,"default":""},{"name":"nonce","type":"int","required":true,"default":0}],
      responseFields: [{"name":"status","type":"str","required":true,"default":""},{"name":"uptime","type":"int","required":true,"default":0},{"name":"warnings","type":"list","required":true,"default":[]}],
      requestTypeHash: new Uint8Array([0xa3, 0xc1, 0x6e, 0x64, 0x3a, 0x31, 0x3a, 0xbb, 0x34, 0x29, 0xa9, 0x4e, 0x94, 0x1e, 0x70, 0xf8, 0xc9, 0xd3, 0xb0, 0xd4, 0x10, 0x93, 0x6f, 0xc3, 0x0c, 0x8e, 0x49, 0x69, 0xa7, 0x3a, 0xfc, 0x57]),
      responseTypeHash: new Uint8Array([0x29, 0x1c, 0x26, 0x37, 0xf6, 0x46, 0x7d, 0x3f, 0x28, 0x40, 0x15, 0x33, 0xc5, 0x7d, 0xcd, 0x6e, 0x3c, 0xae, 0x82, 0x33, 0x61, 0x17, 0x46, 0x43, 0x2b, 0xe5, 0xb4, 0x7a, 0x95, 0x54, 0x7e, 0xa0]),
    },
    {
      name: "getStatusWithCtx",
      pattern: RpcPattern.UNARY,
      requestType: T2_StatusRequest,
      responseType: T0_StatusResponse,
      acceptsCtx: true,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agentId","type":"str","required":true,"default":""},{"name":"nonce","type":"int","required":true,"default":0}],
      responseFields: [{"name":"status","type":"str","required":true,"default":""},{"name":"uptime","type":"int","required":true,"default":0},{"name":"warnings","type":"list","required":true,"default":[]}],
      requestTypeHash: new Uint8Array([0xa3, 0xc1, 0x6e, 0x64, 0x3a, 0x31, 0x3a, 0xbb, 0x34, 0x29, 0xa9, 0x4e, 0x94, 0x1e, 0x70, 0xf8, 0xc9, 0xd3, 0xb0, 0xd4, 0x10, 0x93, 0x6f, 0xc3, 0x0c, 0x8e, 0x49, 0x69, 0xa7, 0x3a, 0xfc, 0x57]),
      responseTypeHash: new Uint8Array([0x29, 0x1c, 0x26, 0x37, 0xf6, 0x46, 0x7d, 0x3f, 0x28, 0x40, 0x15, 0x33, 0xc5, 0x7d, 0xcd, 0x6e, 0x3c, 0xae, 0x82, 0x33, 0x61, 0x17, 0x46, 0x43, 0x2b, 0xe5, 0xb4, 0x7a, 0x95, 0x54, 0x7e, 0xa0]),
    },
    {
      name: "watchStatus",
      pattern: RpcPattern.SERVER_STREAM,
      requestType: T3_WatchRequest,
      responseType: T1_StatusEvent,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agentId","type":"str","required":true,"default":""},{"name":"includeWarnings","type":"bool","required":true,"default":false}],
      responseFields: [{"name":"at","type":"str","required":true,"default":""},{"name":"status","type":"dict","required":true,"default":{}},{"name":"optionalNote","type":"str","required":false,"default":null}],
      requestTypeHash: new Uint8Array([0x70, 0x13, 0x0c, 0xe0, 0x7c, 0xb7, 0xd9, 0xaf, 0x18, 0xa5, 0x2b, 0x89, 0x6d, 0x96, 0xc8, 0x19, 0x98, 0xe8, 0xe4, 0xac, 0x84, 0x05, 0x28, 0xae, 0x7a, 0x49, 0x07, 0x33, 0x96, 0xe3, 0xce, 0xb4]),
      responseTypeHash: new Uint8Array([0x76, 0x89, 0xad, 0x6f, 0x51, 0xb2, 0x00, 0x00, 0x0d, 0x19, 0x86, 0xe9, 0x35, 0x99, 0x6d, 0x33, 0x47, 0xf0, 0xc3, 0x53, 0x96, 0x9a, 0xd5, 0x83, 0x1e, 0x29, 0x0e, 0x77, 0x2e, 0x76, 0x96, 0x6b]),
    },
    {
      name: "ingestEvents",
      pattern: RpcPattern.CLIENT_STREAM,
      requestType: T1_StatusEvent,
      responseType: T0_StatusResponse,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"at","type":"str","required":true,"default":""},{"name":"status","type":"dict","required":true,"default":{}},{"name":"optionalNote","type":"str","required":false,"default":null}],
      responseFields: [{"name":"status","type":"str","required":true,"default":""},{"name":"uptime","type":"int","required":true,"default":0},{"name":"warnings","type":"list","required":true,"default":[]}],
      requestTypeHash: new Uint8Array([0x76, 0x89, 0xad, 0x6f, 0x51, 0xb2, 0x00, 0x00, 0x0d, 0x19, 0x86, 0xe9, 0x35, 0x99, 0x6d, 0x33, 0x47, 0xf0, 0xc3, 0x53, 0x96, 0x9a, 0xd5, 0x83, 0x1e, 0x29, 0x0e, 0x77, 0x2e, 0x76, 0x96, 0x6b]),
      responseTypeHash: new Uint8Array([0x29, 0x1c, 0x26, 0x37, 0xf6, 0x46, 0x7d, 0x3f, 0x28, 0x40, 0x15, 0x33, 0xc5, 0x7d, 0xcd, 0x6e, 0x3c, 0xae, 0x82, 0x33, 0x61, 0x17, 0x46, 0x43, 0x2b, 0xe5, 0xb4, 0x7a, 0x95, 0x54, 0x7e, 0xa0]),
    },
    {
      name: "exchange",
      pattern: RpcPattern.BIDI_STREAM,
      requestType: T2_StatusRequest,
      responseType: T1_StatusEvent,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agentId","type":"str","required":true,"default":""},{"name":"nonce","type":"int","required":true,"default":0}],
      responseFields: [{"name":"at","type":"str","required":true,"default":""},{"name":"status","type":"dict","required":true,"default":{}},{"name":"optionalNote","type":"str","required":false,"default":null}],
      requestTypeHash: new Uint8Array([0xa3, 0xc1, 0x6e, 0x64, 0x3a, 0x31, 0x3a, 0xbb, 0x34, 0x29, 0xa9, 0x4e, 0x94, 0x1e, 0x70, 0xf8, 0xc9, 0xd3, 0xb0, 0xd4, 0x10, 0x93, 0x6f, 0xc3, 0x0c, 0x8e, 0x49, 0x69, 0xa7, 0x3a, 0xfc, 0x57]),
      responseTypeHash: new Uint8Array([0x76, 0x89, 0xad, 0x6f, 0x51, 0xb2, 0x00, 0x00, 0x0d, 0x19, 0x86, 0xe9, 0x35, 0x99, 0x6d, 0x33, 0x47, 0xf0, 0xc3, 0x53, 0x96, 0x9a, 0xd5, 0x83, 0x1e, 0x29, 0x0e, 0x77, 0x2e, 0x76, 0x96, 0x6b]),
    },
    ],
  },
] as const;
