// @ts-nocheck
// AUTOGENERATED by @aster-rpc/aster — do not edit.
// Regenerate with: bunx aster-gen

import { RpcPattern } from '@aster-rpc/aster';
import { StatusRequest as T0_StatusRequest, StatusResponse as T1_StatusResponse, WatchRequest as T2_WatchRequest, StatusEvent as T3_StatusEvent } from './src/types.js';
import { MissionControlService as T4_MissionControlService } from './src/service.js';

export const WIRE_TYPES = [
  {
    ctor: T0_StatusRequest,
    tag: "sample/StatusRequest",
    fields: [
    { name: "agentId", kind: 'primitive', wire: "string", nullable: false },
    { name: "nonce", kind: 'primitive', wire: "int64", nullable: false },
    ],
    fieldNameSet: new Set(["agentId", "nonce"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
    // foryTypeInfo is intentionally null: the current Fory JS API
    // requires user code to build a typeInfo with a `buildTypeInfo`
    // callback (see `ForyCodec.registerTypeGraph`). The scanner
    // doesn't know Fory's internal shape. Follow-up: once the Fory
    // JS binding exposes a declarative schema form, the scanner can
    // emit it here and `registerGenerated` will feed it to Fory
    // directly — no user callback needed.
    foryTypeInfo: null,
  },
  {
    ctor: T1_StatusResponse,
    tag: "sample/StatusResponse",
    fields: [
    { name: "status", kind: 'primitive', wire: "string", nullable: false },
    { name: "uptime", kind: 'primitive', wire: "int32", nullable: false },
    { name: "warnings", kind: 'list', element: { name: "warnings[]", kind: 'primitive', wire: "string", nullable: false }, nullable: false },
    ],
    fieldNameSet: new Set(["status", "uptime", "warnings"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
    // foryTypeInfo is intentionally null: the current Fory JS API
    // requires user code to build a typeInfo with a `buildTypeInfo`
    // callback (see `ForyCodec.registerTypeGraph`). The scanner
    // doesn't know Fory's internal shape. Follow-up: once the Fory
    // JS binding exposes a declarative schema form, the scanner can
    // emit it here and `registerGenerated` will feed it to Fory
    // directly — no user callback needed.
    foryTypeInfo: null,
  },
  {
    ctor: T2_WatchRequest,
    tag: "sample/WatchRequest",
    fields: [
    { name: "agentId", kind: 'primitive', wire: "string", nullable: false },
    { name: "includeWarnings", kind: 'primitive', wire: "bool", nullable: false },
    ],
    fieldNameSet: new Set(["agentId", "includeWarnings"]),
    nestedTypes: new Map([]),
    elementTypes: new Map([]),
    // foryTypeInfo is intentionally null: the current Fory JS API
    // requires user code to build a typeInfo with a `buildTypeInfo`
    // callback (see `ForyCodec.registerTypeGraph`). The scanner
    // doesn't know Fory's internal shape. Follow-up: once the Fory
    // JS binding exposes a declarative schema form, the scanner can
    // emit it here and `registerGenerated` will feed it to Fory
    // directly — no user callback needed.
    foryTypeInfo: null,
  },
  {
    ctor: T3_StatusEvent,
    tag: "sample/StatusEvent",
    fields: [
    { name: "at", kind: 'primitive', wire: "timestamp", nullable: false },
    { name: "status", kind: 'ref', refTag: "sample/StatusResponse", nullable: false },
    { name: "optionalNote", kind: 'primitive', wire: "string", nullable: true },
    ],
    fieldNameSet: new Set(["at", "status", "optionalNote"]),
    nestedTypes: new Map([["status", T1_StatusResponse]]),
    elementTypes: new Map([]),
    // foryTypeInfo is intentionally null: the current Fory JS API
    // requires user code to build a typeInfo with a `buildTypeInfo`
    // callback (see `ForyCodec.registerTypeGraph`). The scanner
    // doesn't know Fory's internal shape. Follow-up: once the Fory
    // JS binding exposes a declarative schema form, the scanner can
    // emit it here and `registerGenerated` will feed it to Fory
    // directly — no user callback needed.
    foryTypeInfo: null,
  },
] as const;

export const SERVICES = [
  {
    ctor: T4_MissionControlService,
    name: "MissionControl",
    version: 1,
    scoped: "shared",
    serializationModes: [],
    requires: undefined,
    metadata: undefined,
    methods: [
    {
      name: "getStatus",
      pattern: RpcPattern.UNARY,
      requestType: T0_StatusRequest,
      responseType: T1_StatusResponse,
      acceptsCtx: false,
      idempotent: true,
      timeout: 30,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agentId","type":"str","required":true,"default":""},{"name":"nonce","type":"int","required":true,"default":0}],
      responseFields: [{"name":"status","type":"str","required":true,"default":""},{"name":"uptime","type":"int","required":true,"default":0},{"name":"warnings","type":"list","required":true,"default":[]}],
    },
    {
      name: "getStatusWithCtx",
      pattern: RpcPattern.UNARY,
      requestType: T0_StatusRequest,
      responseType: T1_StatusResponse,
      acceptsCtx: true,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agentId","type":"str","required":true,"default":""},{"name":"nonce","type":"int","required":true,"default":0}],
      responseFields: [{"name":"status","type":"str","required":true,"default":""},{"name":"uptime","type":"int","required":true,"default":0},{"name":"warnings","type":"list","required":true,"default":[]}],
    },
    {
      name: "watchStatus",
      pattern: RpcPattern.SERVER_STREAM,
      requestType: T2_WatchRequest,
      responseType: T3_StatusEvent,
      acceptsCtx: false,
      idempotent: false,
      timeout: undefined,
      serialization: undefined,
      requires: undefined,
      metadata: undefined,
      requestFields: [{"name":"agentId","type":"str","required":true,"default":""},{"name":"includeWarnings","type":"bool","required":true,"default":false}],
      responseFields: [{"name":"at","type":"str","required":true,"default":""},{"name":"status","type":"dict","required":true,"default":{}},{"name":"optionalNote","type":"str","required":false,"default":null}],
    },
    ],
  },
] as const;
