//! Contract identity for RPC payload types.
//!
//! `#[derive(AsterType)]` generates [`AsterType`] + [`WireField`] impls that
//! build a `core::contract::TypeDef` via the builders here, so the canonical
//! bytes / BLAKE3 hash match the ContractIdentity spec (§11.3) and are
//! **cross-binding-stable** — identity is computed by core's hand-rolled
//! canonical encoder, independent of the Fory library version.
//!
//! Verified against the Python reference producer
//! (`scripts/cross_lang_echo_contract_id.py`): see `aster/tests/rpc_contract.rs`.

use aster_transport_core::canonical;
use aster_transport_core::contract::{
    canonical_xlang_bytes_service_contract, compute_contract_id, ContainerKind, FieldDef,
    TypeDefKind, TypeKind,
};
use aster_transport_core::contract::{canonical_xlang_bytes_type_def, compute_type_hash};

// Re-exports the generated code + callers reference through `aster::rpc`.
pub use aster_transport_core::contract::{
    ContractManifest, ManifestMethod, MethodDef, MethodPattern, ScopeKind, ServiceContract,
    TypeDef, UnionVariantDef,
};

/// A type that can appear as an RPC payload: it has a contract `TypeDef` and a
/// stable, cross-binding type hash. Generated by `#[derive(AsterType)]`.
pub trait AsterType {
    /// The contract type descriptor for this type.
    fn aster_type_def() -> TypeDef;

    /// BLAKE3 hash of the canonical type bytes — the type's cross-binding
    /// identity (used as `MethodDef.request_type` / `response_type` and as a
    /// `Ref` target).
    fn aster_type_hash() -> [u8; 32] {
        compute_type_hash(&canonical_xlang_bytes_type_def(&Self::aster_type_def()))
    }

    /// Hex form of [`aster_type_hash`](AsterType::aster_type_hash).
    fn aster_type_hash_hex() -> String {
        hex::encode(Self::aster_type_hash())
    }
}

/// Leaf type descriptor — the `(type_kind, type_primitive, type_ref)` a field's
/// element/value/scalar type contributes to a `FieldDef`. Implemented for
/// scalars here and for `#[derive(AsterType)]` structs (as a `Ref`).
pub struct Leaf {
    kind: TypeKind,
    primitive: &'static str,
    type_ref: Vec<u8>,
}

impl Leaf {
    /// A primitive leaf with the given canonical type name (e.g. `"string"`).
    pub fn primitive(name: &'static str) -> Self {
        Leaf {
            kind: TypeKind::Primitive,
            primitive: name,
            type_ref: Vec::new(),
        }
    }

    /// A reference to another contract type, by its 32-byte hash.
    pub fn reference(hash: [u8; 32]) -> Self {
        Leaf {
            kind: TypeKind::Ref,
            primitive: "",
            type_ref: hash.to_vec(),
        }
    }
}

/// Describes how a Rust type appears as a contract field leaf. Implemented for
/// scalars below and for user payload types via `#[derive(AsterType)]`.
pub trait WireField {
    fn leaf() -> Leaf;

    /// Register this type and its **transitive** payload dependencies into a
    /// [`PayloadRegistry`], deduplicating by `TypeId` (so diamonds and
    /// self-referential types terminate). Scalars are a no-op (default);
    /// `#[derive(AsterType)]` structs override this to register themselves by
    /// wire name and recurse into every field's element/value/key type. This is
    /// how nested structs and `Vec<UserStruct>` get registered — the
    /// `#[aster::service]` macro only names each method's top-level
    /// request/response type, and this walk pulls in the rest. (Override
    /// callers require `Self: ForyStruct`.)
    fn register_payload(_reg: &mut PayloadRegistry) {}
}

/// A Fory runtime under construction for **one payload root type** (a method's
/// request or response) and its transitive field tree.
///
/// Apache Fory's `#[derive(ForyStruct)]` allocates each type a
/// `fory_type_index()` from a **per-crate** counter that restarts at 0 in
/// every crate, and registration claims `type_id_index[fory_type_index()]`
/// unconditionally — even for name-based registration. Two types from
/// different crates can therefore collide inside one runtime ("Type index N
/// already registered"). The `#[aster::service]` macro avoids cross-root
/// collisions by building one runtime per payload root; this registry tracks
/// occupied indices so the irreducible case — a collision *within* one root's
/// field tree — fails with a diagnostic naming both wire types instead of
/// Fory's bare index number.
pub struct PayloadRegistry {
    fory: fory_core::Fory,
    seen: std::collections::HashSet<std::any::TypeId>,
    wire_name_by_index: std::collections::HashMap<u32, String>,
}

impl PayloadRegistry {
    #[allow(clippy::new_without_default)]
    pub fn new() -> Self {
        PayloadRegistry {
            fory: super::codec::new_payload_fory(),
            seen: std::collections::HashSet::new(),
            wire_name_by_index: std::collections::HashMap::new(),
        }
    }

    /// Record `T` as visited. Returns `false` when `T` was already walked (the
    /// caller must then skip registration and recursion).
    pub fn mark_seen<T: 'static>(&mut self) -> bool {
        self.seen.insert(std::any::TypeId::of::<T>())
    }

    /// Register `T` under `wire_name`, panicking with an actionable diagnostic
    /// on a Fory type-index collision.
    ///
    /// # Panics
    ///
    /// When another type in this registry already occupies
    /// `T::fory_type_index()`, or when Fory rejects the registration.
    pub fn register<T>(&mut self, wire_name: &str)
    where
        T: fory_core::StructSerializer + fory_core::Serializer + fory_core::ForyDefault + 'static,
    {
        let index = T::fory_type_index();
        if let Some(prev) = self.wire_name_by_index.get(&index) {
            panic!(
                "aster: Fory type-index collision: payload types `{prev}` and `{wire_name}` \
                 both have per-crate Fory type index {index}, so they cannot share one payload \
                 runtime. Fory allocates `fory_type_index()` per crate (restarting at 0), so \
                 this happens when one payload type's field tree spans types defined in two \
                 crates. Workarounds: move both types into the same crate, or reorder the \
                 `#[derive(ForyStruct)]` items in one crate so their indices no longer clash."
            );
        }
        self.fory
            .register_by_name::<T>(wire_name)
            .unwrap_or_else(|e| {
                panic!("aster: failed to register payload type `{wire_name}`: {e}")
            });
        self.wire_name_by_index.insert(index, wire_name.to_string());
    }

    /// Finish registration and yield the configured Fory runtime.
    pub fn into_fory(self) -> fory_core::Fory {
        self.fory
    }
}

macro_rules! prim_wire {
    ($t:ty, $name:literal) => {
        impl WireField for $t {
            fn leaf() -> Leaf {
                Leaf::primitive($name)
            }
        }
    };
}

// Scalar → canonical `type_primitive`. Integer widths map to their Fory wire
// encoding name: `i32`/`i64` are zig-zag varints (`"varint32"`/`"varint64"`,
// matching pyfory's `int32`/`int64`); fixed-width variants are a future add.
// `Vec<u8>` is handled by the derive as `"binary"` (not via this trait).
prim_wire!(bool, "bool");
prim_wire!(String, "string");
prim_wire!(i8, "int8");
prim_wire!(i16, "int16");
prim_wire!(i32, "varint32");
prim_wire!(i64, "varint64");
prim_wire!(u16, "uint16");
prim_wire!(u32, "var_uint32");
prim_wire!(u64, "var_uint64");
prim_wire!(f32, "float32");
prim_wire!(f64, "float64");

/// Build a `TypeDef` for a message (struct). Used by the derive.
pub fn message_type_def(package: &str, name: &str, fields: Vec<FieldDef>) -> TypeDef {
    TypeDef {
        kind: TypeDefKind::Message,
        package: package.to_string(),
        name: name.to_string(),
        fields,
        enum_values: Vec::new(),
        union_variants: Vec::new(),
    }
}

/// Build a `TypeDef` for a union (data-carrying enum). Used by the derive.
/// Per §11.3.3 v1 scope, every variant's payload must itself be a message
/// (`#[derive(AsterType)]` struct) — the variant's `type_ref` is that
/// message's 32-byte type hash.
pub fn union_type_def(package: &str, name: &str, variants: Vec<UnionVariantDef>) -> TypeDef {
    TypeDef {
        kind: TypeDefKind::Union,
        package: package.to_string(),
        name: name.to_string(),
        fields: Vec::new(),
        enum_values: Vec::new(),
        union_variants: variants,
    }
}

/// Build a `UnionVariantDef` from the derive's per-variant inputs. `id` follows
/// the `ForyUnion` case-id scheme (explicit `#[fory(id = N)]`, else 0-based
/// declaration index), so contract identity and Fory wire discriminators agree.
pub fn make_union_variant(name: &str, id: i32, type_ref: [u8; 32]) -> UnionVariantDef {
    UnionVariantDef {
        name: name.to_string(),
        id,
        type_ref: hex::encode(type_ref),
    }
}

fn container_from_u8(c: u8) -> ContainerKind {
    match c {
        1 => ContainerKind::List,
        2 => ContainerKind::Set,
        3 => ContainerKind::Map,
        _ => ContainerKind::None,
    }
}

/// Build a `FieldDef` from the derive's per-field inputs.
///
/// `default_value`: `None` ⇒ `required = true` (no declared default);
/// `Some(bytes)` ⇒ `required = false` with those canonical default bytes
/// (§11.3.2.3). `container`: 0 = none, 1 = list, 2 = set, 3 = map. The field
/// `id` is left 0 — the canonical encoder re-derives it from NFC-sorted name
/// order.
pub fn make_field(
    name: &str,
    leaf: Leaf,
    optional: bool,
    container: u8,
    key: Option<Leaf>,
    default_value: Option<Vec<u8>>,
) -> FieldDef {
    let (ck_kind, ck_prim, ck_ref) = match key {
        Some(k) => (k.kind, k.primitive.to_string(), hex::encode(&k.type_ref)),
        None => (TypeKind::Primitive, String::new(), String::new()),
    };
    let required = default_value.is_none();
    FieldDef {
        id: 0,
        name: name.to_string(),
        type_kind: leaf.kind,
        type_primitive: leaf.primitive.to_string(),
        type_ref: hex::encode(&leaf.type_ref),
        self_ref_name: String::new(),
        optional,
        ref_tracked: false,
        container: container_from_u8(container),
        container_key_kind: ck_kind,
        container_key_primitive: ck_prim,
        container_key_ref: ck_ref,
        required,
        default_value: default_value.map(hex::encode).unwrap_or_default(),
    }
}

/// The cross-binding contract-id (hex BLAKE3) of a service contract.
pub fn contract_id(sc: &ServiceContract) -> String {
    compute_contract_id(&canonical_xlang_bytes_service_contract(sc))
}

/// Canonical XLANG encoding of a scalar default value (§11.3.2.3). Used by the
/// derive for `#[aster(default = ...)]`.
pub fn encode_scalar_default<T: ScalarDefault>(v: &T) -> Vec<u8> {
    v.encode_canonical()
}

/// Scalar types whose default value can be lowered into a contract. Mirrors the
/// canonical wire encoding of each scalar.
pub trait ScalarDefault {
    fn encode_canonical(&self) -> Vec<u8>;
}

impl ScalarDefault for String {
    fn encode_canonical(&self) -> Vec<u8> {
        let mut b = Vec::new();
        canonical::write_string(&mut b, self);
        b
    }
}
impl ScalarDefault for bool {
    fn encode_canonical(&self) -> Vec<u8> {
        let mut b = Vec::new();
        canonical::write_bool(&mut b, *self);
        b
    }
}
impl ScalarDefault for i32 {
    fn encode_canonical(&self) -> Vec<u8> {
        let mut b = Vec::new();
        canonical::write_zigzag_i32(&mut b, *self);
        b
    }
}
impl ScalarDefault for i64 {
    fn encode_canonical(&self) -> Vec<u8> {
        let mut b = Vec::new();
        canonical::write_zigzag_i64(&mut b, *self);
        b
    }
}
impl ScalarDefault for f64 {
    fn encode_canonical(&self) -> Vec<u8> {
        let mut b = Vec::new();
        canonical::write_float64(&mut b, *self);
        b
    }
}
