//! Gateway **projections**: browser-facing media types (JSON, NDJSON) mapped
//! onto the canonical Fory RPC path, *without* touching the wire protocol or the
//! dispatcher. See the "Content negotiation" section of
//! `docs/_internal/working_ideas/aster-http3-transport.md`.
//!
//! Aster RPC is Fory; a projection only **transcodes one payload at a time**
//! between a browser media type and the canonical Fory bytes the dispatcher
//! already speaks. The HTTP transport owns the *outer* body shape (a bare JSON
//! object for unary, NDJSON lines for streams) and feeds/drains the dispatcher
//! as ordinary Fory. `serialization_mode` is never involved.
//!
//! A `Projection` is object-safe (raw bytes in/out) so it lives behind `dyn`.
//! Hand-written today; generated by `#[aster::service(codecs = ["json"])]`
//! later.

use std::collections::HashMap;
use std::sync::Arc;

pub use super::contract::MethodPattern;

/// Per-service transcoder between a browser media type and canonical Fory bytes.
pub trait Projection: Send + Sync + 'static {
    /// Service name (matches `StreamHeader.service`).
    fn service(&self) -> &str;

    /// The call pattern of `method`, or `None` if this projection doesn't know
    /// the method. The transport uses it to pick the body shape and to reject
    /// bidi (not projectable over plain HTTP).
    fn pattern(&self, method: &str) -> Option<MethodPattern>;

    /// Transcode one request payload from `media` (e.g. `application/json`) into
    /// canonical Fory bytes for the dispatcher.
    fn request_to_fory(&self, method: &str, media: &str, body: &[u8]) -> Result<Vec<u8>, String>;

    /// Transcode one response payload from canonical Fory bytes into `media`.
    fn response_from_fory(&self, method: &str, media: &str, fory: &[u8])
        -> Result<Vec<u8>, String>;
}

/// Registry of [`Projection`]s by service name, handed to the HTTP transport via
/// `router_with`. Cheap to clone (each entry is `Arc`-shared).
#[derive(Default, Clone)]
pub struct ProjectionRegistry {
    by_service: HashMap<String, Arc<dyn Projection>>,
}

impl ProjectionRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a service's projection (builder-style; chainable).
    pub fn register(mut self, projection: impl Projection) -> Self {
        self.by_service
            .insert(projection.service().to_string(), Arc::new(projection));
        self
    }

    /// The projection for `service`, if any.
    pub fn get(&self, service: &str) -> Option<&Arc<dyn Projection>> {
        self.by_service.get(service)
    }

    pub fn is_empty(&self) -> bool {
        self.by_service.is_empty()
    }
}
