//! RPC server: the reactor accept+dispatch loop, the [`ServiceDispatch`] trait,
//! and the per-call [`Call`] context.
//!
//! The transport reactor (`core::reactor`) does all the stream plumbing and
//! hands us payload-opaque [`IncomingCall`]s. This module decodes the
//! [`StreamHeader`], routes by `(service, version)` to a registered dispatcher,
//! and gives the handler a [`Call`] to pull requests / emit responses. All four
//! patterns ride the same primitives:
//!
//! | Pattern        | Requests in                          | Responses out                |
//! |----------------|--------------------------------------|------------------------------|
//! | unary          | one ([`Call::recv_request`] once)    | [`Call::respond`]            |
//! | server-stream  | one                                  | N× [`Call::send`] + `finish` |
//! | client-stream  | many (`recv_request` to `None`)      | [`Call::respond`]            |
//! | bidi           | many (concurrent with sends)         | N× `send` + `finish`         |

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use fory_core::Fory;
use tokio::sync::mpsc::{UnboundedReceiver, UnboundedSender};

use aster_transport_core::contract::evaluate_capability;
use aster_transport_core::framing::{encode_frame, FLAG_END_STREAM, FLAG_TRAILER};
use aster_transport_core::reactor::{
    self, IncomingCall, OutgoingFrame, ReactorEvent, RequestFrame,
};
use aster_transport_core::CoreNode;

use super::auth::{AttributeStore, CapabilityRequirement};
use super::codec::{
    decode_stream_header, encode_rpc_status, RpcStatus, SerializationMode, StreamHeader,
};
use super::status::StatusCode;
use super::streaming::{RequestStream, ResponseSink};
use crate::error::{Error, Result};
use crate::Node;

/// The Aster RPC ALPN (`b"aster/1"`). A node must be started with this ALPN
/// registered (e.g. `Node::start_with_alpns(cfg, vec![RPC_ALPN.to_vec()])`) for
/// [`Server`] to accept RPC connections.
pub use reactor::RPC_ALPN;

/// A registered service handler. Hand-written today; generated by
/// `#[aster::service]` in a later step. The instance is shared across all calls
/// (SHARED scope); session-scoped services land later.
#[async_trait::async_trait]
pub trait ServiceDispatch: Send + Sync + 'static {
    /// The service name (matched against `StreamHeader.service`).
    fn name(&self) -> &str;
    /// The service version (matched against `StreamHeader.version`).
    fn version(&self) -> i32;
    /// The method names this service implements. When non-empty, the server
    /// rejects any other method with `UNIMPLEMENTED` **before** [`dispatch`] is
    /// called, so a dispatcher need not handle unknown methods itself. An empty
    /// slice (the default) opts out — then the dispatcher owns method routing,
    /// including returning `UNIMPLEMENTED` for unknown methods. The
    /// `#[aster::service]` macro populates this.
    ///
    /// [`dispatch`]: ServiceDispatch::dispatch
    fn methods(&self) -> &[&str] {
        &[]
    }
    /// A capability requirement enforced on **every** method of this service
    /// (Gate 3), checked before dispatch against the caller's attributes. `None`
    /// (default) = no service-wide requirement.
    fn service_requires(&self) -> Option<CapabilityRequirement> {
        None
    }
    /// A capability requirement for a specific `method` (Gate 3), checked before
    /// dispatch in addition to [`service_requires`](ServiceDispatch::service_requires).
    /// `None` (default) = no method-level requirement. The `#[aster::service]`
    /// macro populates this from `#[rpc(requires = ...)]`.
    fn method_requires(&self, _method: &str) -> Option<CapabilityRequirement> {
        None
    }
    /// Handle one call. `method` is `StreamHeader.method` (guaranteed to be in
    /// [`methods`](ServiceDispatch::methods) when that table is non-empty). The
    /// handler MUST terminate the call by consuming `call` via [`Call::respond`]
    /// or [`Call::finish`]; dropping it without a trailer aborts the stream and
    /// the client observes an error.
    async fn dispatch(&self, method: &str, call: Call);
}

type Registry = HashMap<(String, i32), Arc<dyn ServiceDispatch>>;

/// An RPC server bound to a node. Register services, then [`serve`](Server::serve).
pub struct Server {
    core: CoreNode,
    services: Registry,
    attributes: AttributeStore,
}

impl Server {
    /// Create a server over `node`. The node must have been started with the
    /// [`RPC_ALPN`] registered.
    pub fn new(node: &Node) -> Self {
        Self {
            core: node.core(),
            services: HashMap::new(),
            attributes: AttributeStore::new(),
        }
    }

    /// Register a service dispatcher (builder-style; chainable).
    pub fn register(mut self, svc: impl ServiceDispatch) -> Self {
        self.services
            .insert((svc.name().to_string(), svc.version()), Arc::new(svc));
        self
    }

    /// Register an already-boxed dispatcher. Used by [`AsterServer`](crate::rpc::AsterServer)
    /// to collect heterogeneous services into one registry.
    pub(crate) fn register_arc(mut self, svc: Arc<dyn ServiceDispatch>) -> Self {
        self.services
            .insert((svc.name().to_string(), svc.version()), svc);
        self
    }

    /// Use a shared [`AttributeStore`] for Gate-3 capability checks. Keep a clone
    /// of the same store and populate it from your admission logic (e.g. after
    /// verifying a peer's attestation chain) so per-call `requires` checks see
    /// the peer's roles. Without this, the server uses an empty store (only
    /// no-requirement methods are reachable).
    pub fn attributes(mut self, store: AttributeStore) -> Self {
        self.attributes = store;
        self
    }

    /// Spawn the reactor accept+dispatch loop. The returned [`ServerHandle`]
    /// keeps the loop alive; dropping it detaches (the loop runs until the node
    /// closes), `abort()` stops it.
    pub fn serve(self) -> ServerHandle {
        let services = Arc::new(self.services);
        let attributes = self.attributes;
        let mut handle = reactor::start_reactor(self.core, 256);
        let join = tokio::spawn(async move {
            while let Some(ev) = handle.next_event().await {
                if let ReactorEvent::Call(call) = ev {
                    let services = services.clone();
                    let attributes = attributes.clone();
                    tokio::spawn(async move { handle_call(services, attributes, call).await });
                }
                // ConnectionClosed: per-connection session / attribute reaping
                // lands with session-scoped services (a later step).
            }
        });
        ServerHandle { join }
    }
}

/// Handle to a running [`Server`] loop.
pub struct ServerHandle {
    join: tokio::task::JoinHandle<()>,
}

impl ServerHandle {
    /// Stop the accept+dispatch loop.
    pub fn abort(&self) {
        self.join.abort();
    }

    /// Await the accept+dispatch loop. Resolves when the loop ends (the node
    /// closed, or [`abort`](ServerHandle::abort) was called).
    pub async fn joined(self) {
        let _ = self.join.await;
    }
}

async fn handle_call(services: Arc<Registry>, attributes: AttributeStore, call: IncomingCall) {
    // Pre-dispatch gating, mirroring `bindings/python/aster/server.py`:
    // missing service → INVALID_ARGUMENT, unknown (service, version) → NOT_FOUND,
    // unknown method → UNIMPLEMENTED, unsupported serialization mode →
    // INVALID_ARGUMENT, capability denied → PERMISSION_DENIED (Aster-SPEC §6.5).
    let header = match decode_stream_header(&call.header_payload) {
        Ok(h) => h,
        Err(_) => {
            emit_trailer(
                &call.response_sender,
                StatusCode::Internal,
                "malformed stream header",
            );
            return;
        }
    };

    if header.service.is_empty() {
        emit_trailer(
            &call.response_sender,
            StatusCode::InvalidArgument,
            "missing service name",
        );
        return;
    }

    let svc = match services.get(&(header.service.clone(), header.version)) {
        Some(s) => s.clone(),
        None => {
            emit_trailer(
                &call.response_sender,
                StatusCode::NotFound,
                &format!("service '{}' v{} not found", header.service, header.version),
            );
            return;
        }
    };

    let methods = svc.methods();
    if !methods.is_empty() && !methods.iter().any(|m| *m == header.method) {
        emit_trailer(
            &call.response_sender,
            StatusCode::Unimplemented,
            &format!(
                "method '{}.{}' not implemented",
                header.service, header.method
            ),
        );
        return;
    }

    // Rust speaks XLANG on the wire only (JSON is intentionally unsupported).
    if header.serialization_mode != SerializationMode::Xlang.as_i8() {
        emit_trailer(
            &call.response_sender,
            StatusCode::InvalidArgument,
            &format!(
                "unsupported serialization mode: {}",
                header.serialization_mode
            ),
        );
        return;
    }

    // Gate 3: per-call capability check against the peer's attributes (injected
    // by the application). Service-level requirement first, then method-level —
    // both must pass.
    let attrs = attributes.get(&call.peer_id);
    for req in [svc.service_requires(), svc.method_requires(&header.method)]
        .into_iter()
        .flatten()
    {
        if !evaluate_capability(&req, &attrs) {
            emit_trailer(
                &call.response_sender,
                StatusCode::PermissionDenied,
                &format!(
                    "capability check failed for '{}.{}'",
                    header.service, header.method
                ),
            );
            return;
        }
    }

    let method = header.method.clone();
    svc.dispatch(&method, Call::new(call, header, attrs)).await;
}

/// Send a trailer-only error response (no data frame) before a [`Call`] exists.
fn emit_trailer(sender: &UnboundedSender<OutgoingFrame>, code: StatusCode, message: &str) {
    let status = RpcStatus::error(code, message);
    if let Ok(bytes) = encode_rpc_status(&status) {
        if let Ok(frame) = encode_frame(&bytes, FLAG_TRAILER) {
            let _ = sender.send(OutgoingFrame::Trailer(frame));
        }
    }
}

/// Per-call server context: request input, response output, and the decoded
/// [`StreamHeader`]. Pull requests with [`recv_request`](Call::recv_request),
/// emit streaming items with [`send`](Call::send), and terminate with
/// [`respond`](Call::respond) (unary) or [`finish`](Call::finish) (streaming).
pub struct Call {
    header: StreamHeader,
    attributes: HashMap<String, String>,
    peer_id: String,
    cancelled: Arc<AtomicBool>,
    response_sender: UnboundedSender<OutgoingFrame>,
    /// The first request payload, delivered inline by the reactor (taken once).
    first_request: Option<Vec<u8>>,
    /// Additional request frames (client-stream / bidi). `None` once taken by
    /// [`take_requests`](Call::take_requests).
    request_receiver: Option<UnboundedReceiver<RequestFrame>>,
    /// Whether the first request frame carried `FLAG_END_STREAM` (a single-frame
    /// request stream). The reactor only opens the per-call request channel when
    /// there are *additional* frames to forward; if the first frame already ended
    /// the stream, the channel is never closed, so we must not block reading it.
    first_is_end: bool,
}

impl Call {
    fn new(inner: IncomingCall, header: StreamHeader, attributes: HashMap<String, String>) -> Self {
        let IncomingCall {
            peer_id,
            cancelled,
            response_sender,
            request_payload,
            request_receiver,
            request_flags,
            ..
        } = inner;
        let first_is_end = request_flags & FLAG_END_STREAM != 0;
        Self {
            header,
            attributes,
            peer_id,
            cancelled,
            response_sender,
            first_request: Some(request_payload),
            request_receiver: Some(request_receiver),
            first_is_end,
        }
    }

    /// The decoded request header.
    pub fn header(&self) -> &StreamHeader {
        &self.header
    }

    /// The method being invoked.
    pub fn method(&self) -> &str {
        &self.header.method
    }

    /// The remote peer's id (hex).
    pub fn peer(&self) -> &str {
        &self.peer_id
    }

    /// The peer's authorization attributes (from the server's
    /// [`AttributeStore`](super::auth::AttributeStore)) — e.g. `aster.role`.
    /// Already consulted for the Gate-3 check; exposed for handler-level
    /// decisions. Empty if the peer has no recorded attributes.
    pub fn attributes(&self) -> &HashMap<String, String> {
        &self.attributes
    }

    /// Whether the peer has cancelled the call (or the stream errored). Poll
    /// this from long-running streaming handlers to stop early.
    pub fn is_cancelled(&self) -> bool {
        self.cancelled.load(Ordering::Acquire)
    }

    /// Receive the next request payload. Returns the first request (delivered
    /// inline by the reactor) on the first call, then subsequent client-stream /
    /// bidi frames, then `None` once the request stream ends.
    pub async fn recv_request(&mut self) -> Option<Vec<u8>> {
        if let Some(first) = self.first_request.take() {
            return Some(first);
        }
        // Single-frame request stream: the reactor never closes the request
        // channel in this case, so reading it would block forever.
        if self.first_is_end {
            return None;
        }
        match &mut self.request_receiver {
            Some(rx) => rx.recv().await.map(|f| f.payload),
            None => None,
        }
    }

    /// Emit one streaming response data frame.
    pub fn send(&self, payload: Vec<u8>) -> Result<()> {
        let frame = encode_frame(&payload, 0)?;
        self.response_sender
            .send(OutgoingFrame::Frame(frame))
            .map_err(|_| channel_closed())
    }

    /// Complete a unary (or client-stream) call: one response payload plus the
    /// terminal trailer, in a single write. An empty `payload` sends the trailer
    /// only (a data frame can't carry an empty payload) — the client observes an
    /// empty response with the given status.
    pub fn respond(self, payload: Vec<u8>, status: &RpcStatus) -> Result<()> {
        let trailer = encode_frame(&encode_rpc_status(status)?, FLAG_TRAILER)?;
        let buf = if payload.is_empty() {
            trailer
        } else {
            let mut b = encode_frame(&payload, 0)?;
            b.extend_from_slice(&trailer);
            b
        };
        self.response_sender
            .send(OutgoingFrame::CompleteUnary(buf))
            .map_err(|_| channel_closed())
    }

    /// Finish a streaming call with the terminal trailer (status). Use after the
    /// last [`send`](Call::send), or on its own to fail a call before any data.
    pub fn finish(self, status: &RpcStatus) -> Result<()> {
        let frame = encode_frame(&encode_rpc_status(status)?, FLAG_TRAILER)?;
        self.response_sender
            .send(OutgoingFrame::Trailer(frame))
            .map_err(|_| channel_closed())
    }

    /// A typed output sink sharing this call's response channel (server-stream /
    /// bidi). The call retains the trailer side — `finish` after the handler
    /// returns. Used by `#[aster::service]`-generated dispatchers.
    pub fn response_sink<T>(&self, fory: Arc<Fory>) -> ResponseSink<T> {
        ResponseSink::new(self.response_sender.clone(), fory)
    }

    /// Take the inbound request side as a typed [`RequestStream`] (client-stream /
    /// bidi), leaving the response side intact. Used by generated dispatchers.
    pub fn take_requests<T>(&mut self, fory: Arc<Fory>) -> RequestStream<T> {
        RequestStream::new(
            self.first_request.take(),
            self.request_receiver.take(),
            self.first_is_end,
            fory,
        )
    }
}

fn channel_closed() -> Error {
    Error::Connection("rpc response channel closed (call cancelled or connection gone)".into())
}
