//! RPC server: the reactor accept+dispatch loop, the [`ServiceDispatch`] trait,
//! and the per-call [`Call`] context.
//!
//! The transport reactor (`core::reactor`) does all the stream plumbing and
//! hands us payload-opaque [`IncomingCall`]s. This module decodes the
//! [`StreamHeader`], routes by `(service, version)` to a registered dispatcher,
//! and gives the handler a [`Call`] to pull requests / emit responses. All four
//! patterns ride the same primitives:
//!
//! | Pattern        | Requests in                          | Responses out                |
//! |----------------|--------------------------------------|------------------------------|
//! | unary          | one ([`Call::recv_request`] once)    | [`Call::respond`]            |
//! | server-stream  | one                                  | N× [`Call::send`] + `finish` |
//! | client-stream  | many (`recv_request` to `None`)      | [`Call::respond`]            |
//! | bidi           | many (concurrent with sends)         | N× `send` + `finish`         |

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use fory_core::Fory;
use tokio::sync::mpsc::{UnboundedReceiver, UnboundedSender};

use aster_transport_core::contract::evaluate_capability;
use aster_transport_core::framing::{encode_frame, FLAG_END_STREAM, FLAG_TRAILER};
use aster_transport_core::reactor::{
    self, IncomingCall, OutgoingFrame, ReactorEvent, RequestFrame,
};
use aster_transport_core::CoreNode;

use super::auth::{AttributeStore, AuthContext, Authenticator, CapabilityRequirement};
use super::codec::{
    decode_stream_header, encode_rpc_status, RpcStatus, SerializationMode, StreamHeader,
};
use super::status::StatusCode;
use super::streaming::{RequestStream, ResponseSink};
use crate::error::{Error, Result};
use crate::net::Connection;
use crate::Node;

/// The Aster RPC ALPN (`b"aster/1"`). A node must be started with this ALPN
/// registered (e.g. `Node::start_with_alpns(cfg, vec![RPC_ALPN.to_vec()])`) for
/// [`Server`] to accept RPC connections.
pub use reactor::RPC_ALPN;

/// A registered service handler. Hand-written today; generated by
/// `#[aster::service]` in a later step. The instance is shared across all calls
/// (SHARED scope); session-scoped services land later.
#[async_trait::async_trait]
pub trait ServiceDispatch: Send + Sync + 'static {
    /// The service name (matched against `StreamHeader.service`).
    fn name(&self) -> &str;
    /// The service version (matched against `StreamHeader.version`).
    fn version(&self) -> i32;
    /// The method names this service implements. When non-empty, the server
    /// rejects any other method with `UNIMPLEMENTED` **before** [`dispatch`] is
    /// called, so a dispatcher need not handle unknown methods itself. An empty
    /// slice (the default) opts out — then the dispatcher owns method routing,
    /// including returning `UNIMPLEMENTED` for unknown methods. The
    /// `#[aster::service]` macro populates this.
    ///
    /// [`dispatch`]: ServiceDispatch::dispatch
    fn methods(&self) -> &[&str] {
        &[]
    }
    /// A capability requirement enforced on **every** method of this service
    /// (Gate 3), checked before dispatch against the caller's attributes. `None`
    /// (default) = no service-wide requirement.
    fn service_requires(&self) -> Option<CapabilityRequirement> {
        None
    }
    /// A capability requirement for a specific `method` (Gate 3), checked before
    /// dispatch in addition to [`service_requires`](ServiceDispatch::service_requires).
    /// `None` (default) = no method-level requirement. The `#[aster::service]`
    /// macro populates this from `#[rpc(requires = ...)]`.
    fn method_requires(&self, _method: &str) -> Option<CapabilityRequirement> {
        None
    }
    /// Handle one call. `method` is `StreamHeader.method` (guaranteed to be in
    /// [`methods`](ServiceDispatch::methods) when that table is non-empty). The
    /// handler MUST terminate the call by consuming `call` via [`Call::respond`]
    /// or [`Call::finish`]; dropping it without a trailer aborts the stream and
    /// the client observes an error.
    async fn dispatch(&self, method: &str, call: Call);
}

type Registry = HashMap<(String, i32), Arc<dyn ServiceDispatch>>;

/// Builds a fresh per-session instance of a session-scoped service.
type SessionFactory = Arc<dyn Fn() -> Arc<dyn ServiceDispatch> + Send + Sync>;

type SessionFactories = HashMap<(String, i32), SessionFactory>;
/// Per-session instances, keyed by `(service, version, session-id)`.
type SessionTable = std::sync::RwLock<HashMap<(String, i32, String), Arc<dyn ServiceDispatch>>>;

/// Handler for an inbound connection on a non-`aster/1` ALPN. Invoked once per
/// accepted connection from the reactor's single accept loop, so it **must not
/// block** — hand the connection to a task or channel and return (e.g.
/// [`Expose::handle`](crate::expose::Expose::handle) feeds it to a reactor and
/// returns immediately; a custom protocol should `tokio::spawn` its own loop).
pub type AlpnHandler = Arc<dyn Fn(Connection) + Send + Sync>;

/// ALPN → handler routing table for the non-RPC fan-out.
type AlpnRoutes = HashMap<Vec<u8>, AlpnHandler>;

/// An RPC server bound to a node. Register services, then [`serve`](Server::serve).
pub struct Server {
    core: CoreNode,
    services: Registry,
    session_factories: SessionFactories,
    attributes: AttributeStore,
    authenticator: Option<Arc<dyn Authenticator>>,
    routes: AlpnRoutes,
}

impl Server {
    /// Create a server over `node`. The node must have been started with the
    /// [`RPC_ALPN`] registered.
    pub fn new(node: &Node) -> Self {
        Self {
            core: node.core(),
            services: HashMap::new(),
            session_factories: HashMap::new(),
            attributes: AttributeStore::new(),
            authenticator: None,
            routes: HashMap::new(),
        }
    }

    /// Attach a pre-dispatch [`Authenticator`] (builder-style). It runs on every
    /// call before the Gate-3 capability check, can reject, and can resolve a
    /// principal + attributes (merged with the [`AttributeStore`], enrollment
    /// winning on collision). This is where HTTP Bearer/JWT or any custom auth
    /// lives — it applies to whichever transport drives the dispatcher.
    pub fn authenticator(mut self, auth: impl Authenticator) -> Self {
        self.authenticator = Some(Arc::new(auth));
        self
    }

    /// Set an already-boxed authenticator (used by [`AsterServer`](crate::rpc::AsterServer)).
    pub(crate) fn authenticator_arc(mut self, auth: Arc<dyn Authenticator>) -> Self {
        self.authenticator = Some(auth);
        self
    }

    /// Register a service dispatcher (builder-style; chainable).
    pub fn register(mut self, svc: impl ServiceDispatch) -> Self {
        self.services
            .insert((svc.name().to_string(), svc.version()), Arc::new(svc));
        self
    }

    /// Register an already-boxed dispatcher. Used by [`AsterServer`](crate::rpc::AsterServer)
    /// to collect heterogeneous services into one registry.
    pub(crate) fn register_arc(mut self, svc: Arc<dyn ServiceDispatch>) -> Self {
        self.services
            .insert((svc.name().to_string(), svc.version()), svc);
        self
    }

    /// Register a **session-scoped** service: `factory` builds a fresh instance
    /// per session, keyed by the caller's session id (the `aster-session-id`
    /// header, or `StreamHeader.session_id`). State on the instance is private to
    /// that session — the analogue of Python's `scoped="session"` services. A
    /// call with no session id is rejected with `INVALID_ARGUMENT`.
    ///
    /// (Reaping today: instances are dropped when [`end_session`] is called or,
    /// on Iroh, when the owning connection closes; an idle TTL is a follow-up.)
    ///
    /// [`end_session`]: Dispatcher::end_session
    pub fn register_session<S, F>(mut self, factory: F) -> Self
    where
        S: ServiceDispatch,
        F: Fn() -> S + Send + Sync + 'static,
    {
        let factory: SessionFactory =
            Arc::new(move || Arc::new(factory()) as Arc<dyn ServiceDispatch>);
        // One throwaway instance just to read the (constant) name + version key.
        let probe = factory();
        self.session_factories
            .insert((probe.name().to_string(), probe.version()), factory);
        self
    }

    /// Use a shared [`AttributeStore`] for Gate-3 capability checks. Keep a clone
    /// of the same store and populate it from your admission logic (e.g. after
    /// verifying a peer's attestation chain) so per-call `requires` checks see
    /// the peer's roles. Without this, the server uses an empty store (only
    /// no-requirement methods are reachable).
    pub fn attributes(mut self, store: AttributeStore) -> Self {
        self.attributes = store;
        self
    }

    /// Route inbound connections on a non-`aster/1` `alpn` to `handler`,
    /// instead of dropping them. This is the fan-out that lets one node serve
    /// RPC **and** other protocols on a single accept loop: the reactor owns
    /// `accept()`, sends `aster/1` to the RPC pipeline, and hands every other
    /// ALPN to its registered handler (so a second acceptor — which would split
    /// connections arbitrarily — is never needed).
    ///
    /// The node must also be started with `alpn` registered
    /// ([`start_with_alpns`](crate::Node::start_with_alpns), or
    /// [`AsterServerBuilder::route_alpn`](crate::rpc::AsterServerBuilder::route_alpn)
    /// which registers it for you). `handler` must not block — see
    /// [`AlpnHandler`].
    pub fn route_alpn(
        mut self,
        alpn: impl Into<Vec<u8>>,
        handler: impl Fn(Connection) + Send + Sync + 'static,
    ) -> Self {
        self.routes.insert(alpn.into(), Arc::new(handler));
        self
    }

    /// Register an already-boxed ALPN handler. Used by
    /// [`AsterServer`](crate::rpc::AsterServer) to forward its collected routes.
    pub(crate) fn route_alpn_arc(mut self, alpn: Vec<u8>, handler: AlpnHandler) -> Self {
        self.routes.insert(alpn, handler);
        self
    }

    /// Route inbound connections on `alpn` to an [`Expose`](crate::expose::Expose)
    /// registry: each is attached + fed so its relay streams reach the exposed
    /// services. The convenience over [`route_alpn`](Self::route_alpn) for the
    /// common "RPC + expose on one node" case.
    #[cfg(feature = "expose")]
    pub fn expose_alpn(self, alpn: impl Into<Vec<u8>>, expose: crate::expose::Expose) -> Self {
        self.route_alpn(alpn, move |conn| expose.handle(&conn))
    }

    /// Snapshot the registered services + the Gate-3 attribute store as a
    /// shareable, transport-agnostic [`Dispatcher`]. Each transport (the Iroh
    /// reactor loop, an HTTP listener, …) holds a clone and feeds it
    /// [`IncomingCall`]s. Grab this **before** [`serve`](Server::serve) when you
    /// want to serve the same services over more than one transport:
    ///
    /// ```ignore
    /// let server = Server::new(&node).register(svc).attributes(attrs);
    /// let dispatcher = server.dispatcher(); // hand to a second transport (HTTP)
    /// let handle = server.serve();          // Iroh accept loop
    /// ```
    pub fn dispatcher(&self) -> Dispatcher {
        Dispatcher {
            services: Arc::new(self.services.clone()),
            session_factories: Arc::new(self.session_factories.clone()),
            sessions: Arc::new(SessionTable::default()),
            attributes: self.attributes.clone(),
            authenticator: self.authenticator.clone(),
        }
    }

    /// Spawn the Iroh reactor accept+dispatch loop. The returned [`ServerHandle`]
    /// keeps the loop alive; dropping it detaches (the loop runs until the node
    /// closes), `abort()` stops it. For a multi-transport process, call
    /// [`dispatcher`](Server::dispatcher) first, then `serve`.
    pub fn serve(self) -> ServerHandle {
        let dispatcher = self.dispatcher();
        let handle = reactor::start_reactor(self.core, 256);
        let (mut event_rx, mut non_rpc_rx) = handle.into_parts();

        // RPC pipeline: dispatch each `aster/1` call.
        let rpc_join = tokio::spawn(async move {
            while let Some(ev) = event_rx.recv().await {
                if let ReactorEvent::Call(call) = ev {
                    let dispatcher = dispatcher.clone();
                    tokio::spawn(async move { dispatcher.dispatch_call(call).await });
                }
                // ConnectionClosed: per-connection session / attribute reaping
                // lands with session-scoped services (a later step).
            }
        });

        // Non-RPC fan-out: route every other ALPN to its handler. Always
        // drained (even with no routes) so the accept loop never stalls on a
        // full non-rpc channel.
        let routes = Arc::new(self.routes);
        let route_join = tokio::spawn(async move {
            while let Some((alpn, core)) = non_rpc_rx.recv().await {
                match routes.get(&alpn) {
                    Some(handler) => handler(Connection::new(core)),
                    // No handler for this ALPN: drop `core`, which closes the
                    // connection. The peer observes a closed connection.
                    None => drop(core),
                }
            }
        });

        ServerHandle {
            rpc_join,
            route_join,
        }
    }
}

/// The transport-agnostic RPC dispatcher: the registered services plus the
/// Gate-3 [`AttributeStore`], shareable across transports. Produced by
/// [`Server::dispatcher`]. The Iroh reactor loop uses one internally; a second
/// transport (e.g. HTTP) holds a clone and calls
/// [`dispatch_call`](Dispatcher::dispatch_call) per decoded inbound call.
///
/// Cloning is cheap — the service registry is `Arc`-shared and the attribute
/// store is `Arc`-backed — so all clones see the same services and the same
/// (live, mutable) attributes.
#[derive(Clone)]
pub struct Dispatcher {
    services: Arc<Registry>,
    session_factories: Arc<SessionFactories>,
    /// Live per-session instances, shared across clones of this dispatcher.
    sessions: Arc<SessionTable>,
    attributes: AttributeStore,
    authenticator: Option<Arc<dyn Authenticator>>,
}

impl Dispatcher {
    /// Dispatch one already-decoded inbound [`IncomingCall`]: run the
    /// pre-dispatch gates (service / method / serialization mode / Gate-3
    /// capability) and, if they pass, hand a [`Call`] to the matched service.
    /// Any transport that can produce an `IncomingCall` (peer id, header +
    /// request payload, a response-frame channel) can drive RPC through this.
    pub async fn dispatch_call(&self, call: IncomingCall) {
        self.dispatch_parts(CallParts::from_incoming(call)).await;
    }

    /// Dispatch from connection-agnostic [`CallParts`] — the entry point for a
    /// non-Iroh transport (e.g. HTTP) that has no `CoreConnection`. Builds the
    /// parts itself (peer id, header + request payloads, a response-frame
    /// channel) and calls this. Same gating and handler invocation as
    /// [`dispatch_call`](Dispatcher::dispatch_call).
    pub async fn dispatch_parts(&self, parts: CallParts) {
        handle_call(
            self.services.clone(),
            self.session_factories.clone(),
            self.sessions.clone(),
            self.attributes.clone(),
            self.authenticator.clone(),
            parts,
        )
        .await;
    }

    /// The Gate-3 [`AttributeStore`] this dispatcher checks. A transport's auth
    /// stage writes resolved caller attributes here (keyed by the call's peer
    /// id) before dispatching, so the capability gate sees them.
    pub fn attributes(&self) -> &AttributeStore {
        &self.attributes
    }

    /// Drop all session-scoped instances for `session_id` (e.g. on session
    /// close). Subsequent calls with that id create fresh instances.
    pub fn end_session(&self, session_id: &str) {
        self.sessions
            .write()
            .unwrap()
            .retain(|(_, _, sid), _| sid != session_id);
    }
}

/// A pluggable additional transport for [`AsterServer`] — e.g. the HTTP/Salvo
/// transport. Defined here (in `aster`) so `aster` needn't depend on the
/// transport crate; the transport crate implements it for its config type and
/// `AsterServer::builder().with_http(cfg)` spawns it on the shared
/// [`Dispatcher`]. Off by default — Iroh-only unless one is attached.
pub trait HttpTransport: Send + 'static {
    /// Spawn the transport serving `dispatcher`; the returned handle is held by
    /// the [`AsterServer`] and aborted on shutdown.
    fn serve(self: Box<Self>, dispatcher: Dispatcher) -> tokio::task::JoinHandle<()>;
}

/// The connection-agnostic inputs the dispatcher needs for one call. The Iroh
/// reactor path builds this from an [`IncomingCall`] via
/// [`from_incoming`](CallParts::from_incoming); other transports (HTTP)
/// construct it directly — no `CoreConnection` required, because the dispatch
/// path never touches the connection (only the FFI bindings do).
///
/// A transport wires the two channels: it sends request frames into
/// `request_receiver` (the first inline as `request_payload` / `request_flags`)
/// and drains `response_sender` to write the response. For a unary call:
/// `request_payload` is the lone request frame, `request_flags` has
/// `FLAG_END_STREAM`, and `request_receiver` is an already-closed channel.
pub struct CallParts {
    pub peer_id: String,
    pub header_payload: Vec<u8>,
    pub request_payload: Vec<u8>,
    pub request_flags: u8,
    pub response_sender: UnboundedSender<OutgoingFrame>,
    pub request_receiver: UnboundedReceiver<RequestFrame>,
    pub cancelled: Arc<AtomicBool>,
}

impl CallParts {
    /// Extract the dispatch-relevant parts from a reactor [`IncomingCall`],
    /// dropping the `CoreConnection` and the ids the dispatcher doesn't use.
    pub fn from_incoming(call: IncomingCall) -> Self {
        Self {
            peer_id: call.peer_id,
            header_payload: call.header_payload,
            request_payload: call.request_payload,
            request_flags: call.request_flags,
            response_sender: call.response_sender,
            request_receiver: call.request_receiver,
            cancelled: call.cancelled,
        }
    }
}

/// Handle to a running [`Server`] loop: the RPC dispatch task plus the non-RPC
/// ALPN fan-out task (see [`Server::route_alpn`]).
pub struct ServerHandle {
    rpc_join: tokio::task::JoinHandle<()>,
    route_join: tokio::task::JoinHandle<()>,
}

impl ServerHandle {
    /// Stop both the RPC dispatch and ALPN fan-out loops.
    pub fn abort(&self) {
        self.rpc_join.abort();
        self.route_join.abort();
    }

    /// Await the loops. Resolves when they end (the node closed, or
    /// [`abort`](ServerHandle::abort) was called).
    pub async fn joined(self) {
        let _ = self.rpc_join.await;
        self.route_join.abort();
        let _ = self.route_join.await;
    }
}

#[allow(clippy::too_many_arguments)]
async fn handle_call(
    services: Arc<Registry>,
    session_factories: Arc<SessionFactories>,
    sessions: Arc<SessionTable>,
    attributes: AttributeStore,
    authenticator: Option<Arc<dyn Authenticator>>,
    mut call: CallParts,
) {
    // Pre-dispatch gating, mirroring `bindings/python/aster/server.py`:
    // missing service → INVALID_ARGUMENT, unknown (service, version) → NOT_FOUND,
    // unknown method → UNIMPLEMENTED, unsupported serialization mode →
    // INVALID_ARGUMENT, capability denied → PERMISSION_DENIED (Aster-SPEC §6.5).
    let header = match decode_stream_header(&call.header_payload) {
        Ok(h) => h,
        Err(_) => {
            emit_trailer(
                &call.response_sender,
                StatusCode::Internal,
                "malformed stream header",
            );
            return;
        }
    };

    if header.service.is_empty() {
        emit_trailer(
            &call.response_sender,
            StatusCode::InvalidArgument,
            "missing service name",
        );
        return;
    }

    let key = (header.service.clone(), header.version);
    let svc = if let Some(s) = services.get(&key) {
        // SHARED service: one instance for everyone.
        s.clone()
    } else if let Some(factory) = session_factories.get(&key) {
        // SESSION-scoped service: an instance per session id.
        let sid = session_key(&header);
        if sid.is_empty() {
            emit_trailer(
                &call.response_sender,
                StatusCode::InvalidArgument,
                &format!(
                    "service '{}' v{} is session-scoped; an aster-session-id is required",
                    header.service, header.version
                ),
            );
            return;
        }
        get_or_create_session(&sessions, &key, &sid, factory)
    } else {
        emit_trailer(
            &call.response_sender,
            StatusCode::NotFound,
            &format!("service '{}' v{} not found", header.service, header.version),
        );
        return;
    };

    let methods = svc.methods();
    if !methods.is_empty() && !methods.iter().any(|m| *m == header.method) {
        emit_trailer(
            &call.response_sender,
            StatusCode::Unimplemented,
            &format!(
                "method '{}.{}' not implemented",
                header.service, header.method
            ),
        );
        return;
    }

    // Rust speaks XLANG on the wire only (JSON is intentionally unsupported).
    if header.serialization_mode != SerializationMode::Xlang.as_i8() {
        emit_trailer(
            &call.response_sender,
            StatusCode::InvalidArgument,
            &format!(
                "unsupported serialization mode: {}",
                header.serialization_mode
            ),
        );
        return;
    }

    // Enrollment-derived attributes for this peer (from the application's store).
    let mut attrs = attributes.get(&call.peer_id);

    // Pre-dispatch auth hook: may reject, override the principal, and contribute
    // attributes — merged additively, **enrollment wins on key collision**.
    if let Some(auth) = authenticator.as_ref() {
        let ctx = AuthContext {
            peer_id: call.peer_id.clone(),
            service: header.service.clone(),
            method: header.method.clone(),
            session_id: header.session_id,
            metadata: metadata_map(&header),
        };
        match auth.authenticate(&ctx).await {
            Ok(outcome) => {
                if let Some(principal) = outcome.principal {
                    call.peer_id = principal;
                }
                for (k, v) in outcome.attributes {
                    attrs.entry(k).or_insert(v);
                }
            }
            Err(status) => {
                emit_rpc_status(&call.response_sender, &status);
                return;
            }
        }
    }

    // Gate 3: per-call capability check against the resolved attributes.
    // Service-level requirement first, then method-level — both must pass.
    for req in [svc.service_requires(), svc.method_requires(&header.method)]
        .into_iter()
        .flatten()
    {
        if !evaluate_capability(&req, &attrs) {
            emit_trailer(
                &call.response_sender,
                StatusCode::PermissionDenied,
                &format!(
                    "capability check failed for '{}.{}'",
                    header.service, header.method
                ),
            );
            return;
        }
    }

    let method = header.method.clone();
    svc.dispatch(&method, Call::new(call, header, attrs)).await;
}

/// Send a trailer-only error response (no data frame) before a [`Call`] exists.
fn emit_trailer(sender: &UnboundedSender<OutgoingFrame>, code: StatusCode, message: &str) {
    emit_rpc_status(sender, &RpcStatus::error(code, message));
}

/// Send an already-built [`RpcStatus`] as a trailer-only response. Used by the
/// auth hook to surface its own status (code + message + details).
fn emit_rpc_status(sender: &UnboundedSender<OutgoingFrame>, status: &RpcStatus) {
    if let Ok(bytes) = encode_rpc_status(status) {
        if let Ok(frame) = encode_frame(&bytes, FLAG_TRAILER) {
            let _ = sender.send(OutgoingFrame::Trailer(frame));
        }
    }
}

/// Build a metadata map from a header's parallel key/value vectors.
fn metadata_map(h: &StreamHeader) -> HashMap<String, String> {
    h.metadata_keys
        .iter()
        .cloned()
        .zip(h.metadata_values.iter().cloned())
        .collect()
}

/// The session id for a call: the `aster-session-id` metadata header (HTTP), or
/// the numeric `StreamHeader.session_id` (Iroh) when non-zero. Empty = none.
fn session_key(h: &StreamHeader) -> String {
    for (k, v) in h.metadata_keys.iter().zip(h.metadata_values.iter()) {
        if k == "aster-session-id" && !v.is_empty() {
            return v.clone();
        }
    }
    if h.session_id != 0 {
        return h.session_id.to_string();
    }
    String::new()
}

/// Get (or lazily create) the per-session instance for `(service, session-id)`.
fn get_or_create_session(
    sessions: &SessionTable,
    key: &(String, i32),
    sid: &str,
    factory: &SessionFactory,
) -> Arc<dyn ServiceDispatch> {
    let full = (key.0.clone(), key.1, sid.to_string());
    if let Some(inst) = sessions.read().unwrap().get(&full) {
        return inst.clone();
    }
    let mut guard = sessions.write().unwrap();
    // Re-check under the write lock (another call may have created it).
    guard.entry(full).or_insert_with(|| factory()).clone()
}

/// Per-call server context: request input, response output, and the decoded
/// [`StreamHeader`]. Pull requests with [`recv_request`](Call::recv_request),
/// emit streaming items with [`send`](Call::send), and terminate with
/// [`respond`](Call::respond) (unary) or [`finish`](Call::finish) (streaming).
pub struct Call {
    header: StreamHeader,
    attributes: HashMap<String, String>,
    peer_id: String,
    cancelled: Arc<AtomicBool>,
    response_sender: UnboundedSender<OutgoingFrame>,
    /// The first request payload, delivered inline by the reactor (taken once).
    first_request: Option<Vec<u8>>,
    /// Additional request frames (client-stream / bidi). `None` once taken by
    /// [`take_requests`](Call::take_requests).
    request_receiver: Option<UnboundedReceiver<RequestFrame>>,
    /// Whether the first request frame carried `FLAG_END_STREAM` (a single-frame
    /// request stream). The reactor only opens the per-call request channel when
    /// there are *additional* frames to forward; if the first frame already ended
    /// the stream, the channel is never closed, so we must not block reading it.
    first_is_end: bool,
}

impl Call {
    fn new(inner: CallParts, header: StreamHeader, attributes: HashMap<String, String>) -> Self {
        let CallParts {
            peer_id,
            cancelled,
            response_sender,
            request_payload,
            request_receiver,
            request_flags,
            ..
        } = inner;
        let first_is_end = request_flags & FLAG_END_STREAM != 0;
        Self {
            header,
            attributes,
            peer_id,
            cancelled,
            response_sender,
            first_request: Some(request_payload),
            request_receiver: Some(request_receiver),
            first_is_end,
        }
    }

    /// The decoded request header.
    pub fn header(&self) -> &StreamHeader {
        &self.header
    }

    /// The method being invoked.
    pub fn method(&self) -> &str {
        &self.header.method
    }

    /// The remote peer's id (hex).
    pub fn peer(&self) -> &str {
        &self.peer_id
    }

    /// The peer's authorization attributes (from the server's
    /// [`AttributeStore`](super::auth::AttributeStore)) — e.g. `aster.role`.
    /// Already consulted for the Gate-3 check; exposed for handler-level
    /// decisions. Empty if the peer has no recorded attributes.
    pub fn attributes(&self) -> &HashMap<String, String> {
        &self.attributes
    }

    /// Whether the peer has cancelled the call (or the stream errored). Poll
    /// this from long-running streaming handlers to stop early.
    pub fn is_cancelled(&self) -> bool {
        self.cancelled.load(Ordering::Acquire)
    }

    /// Receive the next request payload. Returns the first request (delivered
    /// inline by the reactor) on the first call, then subsequent client-stream /
    /// bidi frames, then `None` once the request stream ends.
    pub async fn recv_request(&mut self) -> Option<Vec<u8>> {
        if let Some(first) = self.first_request.take() {
            return Some(first);
        }
        // Single-frame request stream: the reactor never closes the request
        // channel in this case, so reading it would block forever.
        if self.first_is_end {
            return None;
        }
        match &mut self.request_receiver {
            Some(rx) => rx.recv().await.map(|f| f.payload),
            None => None,
        }
    }

    /// Emit one streaming response data frame.
    pub fn send(&self, payload: Vec<u8>) -> Result<()> {
        let frame = encode_frame(&payload, 0)?;
        self.response_sender
            .send(OutgoingFrame::Frame(frame))
            .map_err(|_| channel_closed())
    }

    /// Complete a unary (or client-stream) call: one response payload plus the
    /// terminal trailer, in a single write. An empty `payload` sends the trailer
    /// only (a data frame can't carry an empty payload) — the client observes an
    /// empty response with the given status.
    pub fn respond(self, payload: Vec<u8>, status: &RpcStatus) -> Result<()> {
        let trailer = encode_frame(&encode_rpc_status(status)?, FLAG_TRAILER)?;
        let buf = if payload.is_empty() {
            trailer
        } else {
            let mut b = encode_frame(&payload, 0)?;
            b.extend_from_slice(&trailer);
            b
        };
        self.response_sender
            .send(OutgoingFrame::CompleteUnary(buf))
            .map_err(|_| channel_closed())
    }

    /// Finish a streaming call with the terminal trailer (status). Use after the
    /// last [`send`](Call::send), or on its own to fail a call before any data.
    pub fn finish(self, status: &RpcStatus) -> Result<()> {
        let frame = encode_frame(&encode_rpc_status(status)?, FLAG_TRAILER)?;
        self.response_sender
            .send(OutgoingFrame::Trailer(frame))
            .map_err(|_| channel_closed())
    }

    /// A typed output sink sharing this call's response channel (server-stream /
    /// bidi). The call retains the trailer side — `finish` after the handler
    /// returns. Used by `#[aster::service]`-generated dispatchers.
    pub fn response_sink<T>(&self, fory: Arc<Fory>) -> ResponseSink<T> {
        ResponseSink::new(self.response_sender.clone(), fory)
    }

    /// Take the inbound request side as a typed [`RequestStream`] (client-stream /
    /// bidi), leaving the response side intact. Used by generated dispatchers.
    pub fn take_requests<T>(&mut self, fory: Arc<Fory>) -> RequestStream<T> {
        RequestStream::new(
            self.first_request.take(),
            self.request_receiver.take(),
            self.first_is_end,
            fory,
        )
    }
}

fn channel_closed() -> Error {
    Error::Connection("rpc response channel closed (call cancelled or connection gone)".into())
}
